// Code generated by Fern. DO NOT EDIT.

package client

import (
	agents "github.com/DTG-Corp/dtg-sdk-go/agents"
	apikeys "github.com/DTG-Corp/dtg-sdk-go/apikeys"
	cameras "github.com/DTG-Corp/dtg-sdk-go/cameras"
	core "github.com/DTG-Corp/dtg-sdk-go/core"
	gateway "github.com/DTG-Corp/dtg-sdk-go/gateway"
	internal "github.com/DTG-Corp/dtg-sdk-go/internal"
	knowledge "github.com/DTG-Corp/dtg-sdk-go/knowledge"
	mcpservers "github.com/DTG-Corp/dtg-sdk-go/mcpservers"
	option "github.com/DTG-Corp/dtg-sdk-go/option"
	organizations "github.com/DTG-Corp/dtg-sdk-go/organizations"
)

type Client struct {
	Gateway       *gateway.Client
	Agents        *agents.Client
	APIKeys       *apikeys.Client
	Organizations *organizations.Client
	Knowledge     *knowledge.Client
	Cameras       *cameras.Client
	McpServers    *mcpservers.Client

	options *core.RequestOptions
	baseURL string
	caller  *internal.Caller
}

func NewClient(opts ...option.RequestOption) *Client {
	options := core.NewRequestOptions(opts...)
	return &Client{
		Gateway:       gateway.NewClient(options),
		Agents:        agents.NewClient(options),
		APIKeys:       apikeys.NewClient(options),
		Organizations: organizations.NewClient(options),
		Knowledge:     knowledge.NewClient(options),
		Cameras:       cameras.NewClient(options),
		McpServers:    mcpservers.NewClient(options),
		options:       options,
		baseURL:       options.BaseURL,
		caller: internal.NewCaller(
			&internal.CallerParams{
				Client:         options.HTTPClient,
				MaxAttempts:    options.MaxAttempts,
				DisableRetries: options.DisableRetries,
			},
		),
	}
}
