// Code generated by Fern. DO NOT EDIT.

package api

import (
	json "encoding/json"
	fmt "fmt"
	internal "github.com/DTG-Corp/dtg-sdk-go/internal"
	big "math/big"
	time "time"
)

var (
	agentCreateRequestFieldIdempotencyKey       = big.NewInt(1 << 0)
	agentCreateRequestFieldDisplayName          = big.NewInt(1 << 1)
	agentCreateRequestFieldLlmProvider          = big.NewInt(1 << 2)
	agentCreateRequestFieldLlmModel             = big.NewInt(1 << 3)
	agentCreateRequestFieldLlmBaseURL           = big.NewInt(1 << 4)
	agentCreateRequestFieldLlmAPIKey            = big.NewInt(1 << 5)
	agentCreateRequestFieldKnowledgeIDs         = big.NewInt(1 << 6)
	agentCreateRequestFieldEnabledTools         = big.NewInt(1 << 7)
	agentCreateRequestFieldCameraToolIDs        = big.NewInt(1 << 8)
	agentCreateRequestFieldMcpDynamicServerIDs  = big.NewInt(1 << 9)
	agentCreateRequestFieldMcpDynamicToolFilter = big.NewInt(1 << 10)
)

type AgentCreateRequest struct {
	// Idempotency key cho mutation (tránh double-submit).
	IdempotencyKey *string `json:"-" url:"-"`
	DisplayName    string  `json:"display_name" url:"-"`
	LlmProvider    *string `json:"llm_provider,omitempty" url:"-"`
	LlmModel       *string `json:"llm_model,omitempty" url:"-"`
	LlmBaseURL     *string `json:"llm_base_url,omitempty" url:"-"`
	LlmAPIKey      *string `json:"llm_api_key,omitempty" url:"-"`
	// UUID các knowledge item gắn agent (điền vào dtg_knowledge_ids).
	KnowledgeIDs []string `json:"knowledge_ids,omitempty" url:"-"`
	// ID tool từ catalog (dtg_enabled_tools), vd knowledge_rag.
	EnabledTools []string `json:"enabled_tools,omitempty" url:"-"`
	// UUID camera ORG được phép khi bật tool org_cameras (điền vào dtg_camera_tool_ids).
	CameraToolIDs []string `json:"camera_tool_ids,omitempty" url:"-"`
	// UUID MCP server động (apimcp) gắn agent.
	McpDynamicServerIDs []string `json:"mcp_dynamic_server_ids,omitempty" url:"-"`
	// Filter tool expose cho agent (Dai Agent) theo từng MCP server động (khóa = UUID server).
	McpDynamicToolFilter map[string]any `json:"mcp_dynamic_tool_filter,omitempty" url:"-"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
}

func (a *AgentCreateRequest) require(field *big.Int) {
	if a.explicitFields == nil {
		a.explicitFields = big.NewInt(0)
	}
	a.explicitFields.Or(a.explicitFields, field)
}

// SetIdempotencyKey sets the IdempotencyKey field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (a *AgentCreateRequest) SetIdempotencyKey(idempotencyKey *string) {
	a.IdempotencyKey = idempotencyKey
	a.require(agentCreateRequestFieldIdempotencyKey)
}

// SetDisplayName sets the DisplayName field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (a *AgentCreateRequest) SetDisplayName(displayName string) {
	a.DisplayName = displayName
	a.require(agentCreateRequestFieldDisplayName)
}

// SetLlmProvider sets the LlmProvider field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (a *AgentCreateRequest) SetLlmProvider(llmProvider *string) {
	a.LlmProvider = llmProvider
	a.require(agentCreateRequestFieldLlmProvider)
}

// SetLlmModel sets the LlmModel field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (a *AgentCreateRequest) SetLlmModel(llmModel *string) {
	a.LlmModel = llmModel
	a.require(agentCreateRequestFieldLlmModel)
}

// SetLlmBaseURL sets the LlmBaseURL field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (a *AgentCreateRequest) SetLlmBaseURL(llmBaseURL *string) {
	a.LlmBaseURL = llmBaseURL
	a.require(agentCreateRequestFieldLlmBaseURL)
}

// SetLlmAPIKey sets the LlmAPIKey field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (a *AgentCreateRequest) SetLlmAPIKey(llmAPIKey *string) {
	a.LlmAPIKey = llmAPIKey
	a.require(agentCreateRequestFieldLlmAPIKey)
}

// SetKnowledgeIDs sets the KnowledgeIDs field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (a *AgentCreateRequest) SetKnowledgeIDs(knowledgeIDs []string) {
	a.KnowledgeIDs = knowledgeIDs
	a.require(agentCreateRequestFieldKnowledgeIDs)
}

// SetEnabledTools sets the EnabledTools field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (a *AgentCreateRequest) SetEnabledTools(enabledTools []string) {
	a.EnabledTools = enabledTools
	a.require(agentCreateRequestFieldEnabledTools)
}

// SetCameraToolIDs sets the CameraToolIDs field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (a *AgentCreateRequest) SetCameraToolIDs(cameraToolIDs []string) {
	a.CameraToolIDs = cameraToolIDs
	a.require(agentCreateRequestFieldCameraToolIDs)
}

// SetMcpDynamicServerIDs sets the McpDynamicServerIDs field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (a *AgentCreateRequest) SetMcpDynamicServerIDs(mcpDynamicServerIDs []string) {
	a.McpDynamicServerIDs = mcpDynamicServerIDs
	a.require(agentCreateRequestFieldMcpDynamicServerIDs)
}

// SetMcpDynamicToolFilter sets the McpDynamicToolFilter field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (a *AgentCreateRequest) SetMcpDynamicToolFilter(mcpDynamicToolFilter map[string]any) {
	a.McpDynamicToolFilter = mcpDynamicToolFilter
	a.require(agentCreateRequestFieldMcpDynamicToolFilter)
}

func (a *AgentCreateRequest) UnmarshalJSON(data []byte) error {
	type unmarshaler AgentCreateRequest
	var body unmarshaler
	if err := json.Unmarshal(data, &body); err != nil {
		return err
	}
	*a = AgentCreateRequest(body)
	return nil
}

func (a *AgentCreateRequest) MarshalJSON() ([]byte, error) {
	type embed AgentCreateRequest
	var marshaler = struct {
		embed
	}{
		embed: embed(*a),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, a.explicitFields)
	return json.Marshal(explicitMarshaler)
}

var (
	deleteAgentRequestFieldIdempotencyKey = big.NewInt(1 << 0)
	deleteAgentRequestFieldID             = big.NewInt(1 << 1)
)

type DeleteAgentRequest struct {
	// Idempotency key cho mutation (tránh double-submit).
	IdempotencyKey *string `json:"-" url:"-"`
	ID             string  `json:"-" url:"-"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
}

func (d *DeleteAgentRequest) require(field *big.Int) {
	if d.explicitFields == nil {
		d.explicitFields = big.NewInt(0)
	}
	d.explicitFields.Or(d.explicitFields, field)
}

// SetIdempotencyKey sets the IdempotencyKey field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (d *DeleteAgentRequest) SetIdempotencyKey(idempotencyKey *string) {
	d.IdempotencyKey = idempotencyKey
	d.require(deleteAgentRequestFieldIdempotencyKey)
}

// SetID sets the ID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (d *DeleteAgentRequest) SetID(id string) {
	d.ID = id
	d.require(deleteAgentRequestFieldID)
}

var (
	getAgentRequestFieldID = big.NewInt(1 << 0)
)

type GetAgentRequest struct {
	ID string `json:"-" url:"-"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
}

func (g *GetAgentRequest) require(field *big.Int) {
	if g.explicitFields == nil {
		g.explicitFields = big.NewInt(0)
	}
	g.explicitFields.Or(g.explicitFields, field)
}

// SetID sets the ID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GetAgentRequest) SetID(id string) {
	g.ID = id
	g.require(getAgentRequestFieldID)
}

var (
	getAgentChannelsRequestFieldID = big.NewInt(1 << 0)
)

type GetAgentChannelsRequest struct {
	ID string `json:"-" url:"-"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
}

func (g *GetAgentChannelsRequest) require(field *big.Int) {
	if g.explicitFields == nil {
		g.explicitFields = big.NewInt(0)
	}
	g.explicitFields.Or(g.explicitFields, field)
}

// SetID sets the ID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GetAgentChannelsRequest) SetID(id string) {
	g.ID = id
	g.require(getAgentChannelsRequestFieldID)
}

var (
	startAgentRequestFieldIdempotencyKey = big.NewInt(1 << 0)
	startAgentRequestFieldID             = big.NewInt(1 << 1)
)

type StartAgentRequest struct {
	// Idempotency key cho mutation (tránh double-submit).
	IdempotencyKey *string `json:"-" url:"-"`
	ID             string  `json:"-" url:"-"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
}

func (s *StartAgentRequest) require(field *big.Int) {
	if s.explicitFields == nil {
		s.explicitFields = big.NewInt(0)
	}
	s.explicitFields.Or(s.explicitFields, field)
}

// SetIdempotencyKey sets the IdempotencyKey field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (s *StartAgentRequest) SetIdempotencyKey(idempotencyKey *string) {
	s.IdempotencyKey = idempotencyKey
	s.require(startAgentRequestFieldIdempotencyKey)
}

// SetID sets the ID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (s *StartAgentRequest) SetID(id string) {
	s.ID = id
	s.require(startAgentRequestFieldID)
}

var (
	stopAgentRequestFieldIdempotencyKey = big.NewInt(1 << 0)
	stopAgentRequestFieldID             = big.NewInt(1 << 1)
)

type StopAgentRequest struct {
	// Idempotency key cho mutation (tránh double-submit).
	IdempotencyKey *string `json:"-" url:"-"`
	ID             string  `json:"-" url:"-"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
}

func (s *StopAgentRequest) require(field *big.Int) {
	if s.explicitFields == nil {
		s.explicitFields = big.NewInt(0)
	}
	s.explicitFields.Or(s.explicitFields, field)
}

// SetIdempotencyKey sets the IdempotencyKey field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (s *StopAgentRequest) SetIdempotencyKey(idempotencyKey *string) {
	s.IdempotencyKey = idempotencyKey
	s.require(stopAgentRequestFieldIdempotencyKey)
}

// SetID sets the ID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (s *StopAgentRequest) SetID(id string) {
	s.ID = id
	s.require(stopAgentRequestFieldID)
}

var (
	agentFieldID                   = big.NewInt(1 << 0)
	agentFieldDisplayName          = big.NewInt(1 << 1)
	agentFieldStatus               = big.NewInt(1 << 2)
	agentFieldLlmProvider          = big.NewInt(1 << 3)
	agentFieldLlmModel             = big.NewInt(1 << 4)
	agentFieldLlmBaseURL           = big.NewInt(1 << 5)
	agentFieldKnowledgeIDs         = big.NewInt(1 << 6)
	agentFieldEnabledTools         = big.NewInt(1 << 7)
	agentFieldCameraToolIDs        = big.NewInt(1 << 8)
	agentFieldMcpDynamicServerIDs  = big.NewInt(1 << 9)
	agentFieldMcpDynamicToolFilter = big.NewInt(1 << 10)
)

type Agent struct {
	ID           string      `json:"id" url:"id"`
	DisplayName  string      `json:"display_name" url:"display_name"`
	Status       AgentStatus `json:"status" url:"status"`
	LlmProvider  *string     `json:"llm_provider,omitempty" url:"llm_provider,omitempty"`
	LlmModel     *string     `json:"llm_model,omitempty" url:"llm_model,omitempty"`
	LlmBaseURL   *string     `json:"llm_base_url,omitempty" url:"llm_base_url,omitempty"`
	KnowledgeIDs []string    `json:"knowledge_ids,omitempty" url:"knowledge_ids,omitempty"`
	EnabledTools []string    `json:"enabled_tools,omitempty" url:"enabled_tools,omitempty"`
	// UUID camera ORG được phép khi bật tool org_cameras (điền vào dtg_camera_tool_ids).
	CameraToolIDs        []string       `json:"camera_tool_ids,omitempty" url:"camera_tool_ids,omitempty"`
	McpDynamicServerIDs  []string       `json:"mcp_dynamic_server_ids,omitempty" url:"mcp_dynamic_server_ids,omitempty"`
	McpDynamicToolFilter map[string]any `json:"mcp_dynamic_tool_filter,omitempty" url:"mcp_dynamic_tool_filter,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (a *Agent) GetID() string {
	if a == nil {
		return ""
	}
	return a.ID
}

func (a *Agent) GetDisplayName() string {
	if a == nil {
		return ""
	}
	return a.DisplayName
}

func (a *Agent) GetStatus() AgentStatus {
	if a == nil {
		return ""
	}
	return a.Status
}

func (a *Agent) GetLlmProvider() *string {
	if a == nil {
		return nil
	}
	return a.LlmProvider
}

func (a *Agent) GetLlmModel() *string {
	if a == nil {
		return nil
	}
	return a.LlmModel
}

func (a *Agent) GetLlmBaseURL() *string {
	if a == nil {
		return nil
	}
	return a.LlmBaseURL
}

func (a *Agent) GetKnowledgeIDs() []string {
	if a == nil {
		return nil
	}
	return a.KnowledgeIDs
}

func (a *Agent) GetEnabledTools() []string {
	if a == nil {
		return nil
	}
	return a.EnabledTools
}

func (a *Agent) GetCameraToolIDs() []string {
	if a == nil {
		return nil
	}
	return a.CameraToolIDs
}

func (a *Agent) GetMcpDynamicServerIDs() []string {
	if a == nil {
		return nil
	}
	return a.McpDynamicServerIDs
}

func (a *Agent) GetMcpDynamicToolFilter() map[string]any {
	if a == nil {
		return nil
	}
	return a.McpDynamicToolFilter
}

func (a *Agent) GetExtraProperties() map[string]interface{} {
	if a == nil {
		return nil
	}
	return a.extraProperties
}

func (a *Agent) require(field *big.Int) {
	if a.explicitFields == nil {
		a.explicitFields = big.NewInt(0)
	}
	a.explicitFields.Or(a.explicitFields, field)
}

// SetID sets the ID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (a *Agent) SetID(id string) {
	a.ID = id
	a.require(agentFieldID)
}

// SetDisplayName sets the DisplayName field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (a *Agent) SetDisplayName(displayName string) {
	a.DisplayName = displayName
	a.require(agentFieldDisplayName)
}

// SetStatus sets the Status field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (a *Agent) SetStatus(status AgentStatus) {
	a.Status = status
	a.require(agentFieldStatus)
}

// SetLlmProvider sets the LlmProvider field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (a *Agent) SetLlmProvider(llmProvider *string) {
	a.LlmProvider = llmProvider
	a.require(agentFieldLlmProvider)
}

// SetLlmModel sets the LlmModel field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (a *Agent) SetLlmModel(llmModel *string) {
	a.LlmModel = llmModel
	a.require(agentFieldLlmModel)
}

// SetLlmBaseURL sets the LlmBaseURL field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (a *Agent) SetLlmBaseURL(llmBaseURL *string) {
	a.LlmBaseURL = llmBaseURL
	a.require(agentFieldLlmBaseURL)
}

// SetKnowledgeIDs sets the KnowledgeIDs field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (a *Agent) SetKnowledgeIDs(knowledgeIDs []string) {
	a.KnowledgeIDs = knowledgeIDs
	a.require(agentFieldKnowledgeIDs)
}

// SetEnabledTools sets the EnabledTools field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (a *Agent) SetEnabledTools(enabledTools []string) {
	a.EnabledTools = enabledTools
	a.require(agentFieldEnabledTools)
}

// SetCameraToolIDs sets the CameraToolIDs field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (a *Agent) SetCameraToolIDs(cameraToolIDs []string) {
	a.CameraToolIDs = cameraToolIDs
	a.require(agentFieldCameraToolIDs)
}

// SetMcpDynamicServerIDs sets the McpDynamicServerIDs field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (a *Agent) SetMcpDynamicServerIDs(mcpDynamicServerIDs []string) {
	a.McpDynamicServerIDs = mcpDynamicServerIDs
	a.require(agentFieldMcpDynamicServerIDs)
}

// SetMcpDynamicToolFilter sets the McpDynamicToolFilter field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (a *Agent) SetMcpDynamicToolFilter(mcpDynamicToolFilter map[string]any) {
	a.McpDynamicToolFilter = mcpDynamicToolFilter
	a.require(agentFieldMcpDynamicToolFilter)
}

func (a *Agent) UnmarshalJSON(data []byte) error {
	type unmarshaler Agent
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*a = Agent(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *a)
	if err != nil {
		return err
	}
	a.extraProperties = extraProperties
	a.rawJSON = json.RawMessage(data)
	return nil
}

func (a *Agent) MarshalJSON() ([]byte, error) {
	type embed Agent
	var marshaler = struct {
		embed
	}{
		embed: embed(*a),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, a.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (a *Agent) String() string {
	if a == nil {
		return "<nil>"
	}
	if len(a.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(a.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(a); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", a)
}

type AgentStatus string

const (
	AgentStatusCreated AgentStatus = "created"
	AgentStatusRunning AgentStatus = "running"
	AgentStatusStopped AgentStatus = "stopped"
	AgentStatusUnknown AgentStatus = "unknown"
)

func NewAgentStatusFromString(s string) (AgentStatus, error) {
	switch s {
	case "created":
		return AgentStatusCreated, nil
	case "running":
		return AgentStatusRunning, nil
	case "stopped":
		return AgentStatusStopped, nil
	case "unknown":
		return AgentStatusUnknown, nil
	}
	var t AgentStatus
	return "", fmt.Errorf("%s is not a valid %T", s, t)
}

func (a AgentStatus) Ptr() *AgentStatus {
	return &a
}

var (
	channelConfigFieldType = big.NewInt(1 << 0)
	channelConfigFieldEnv  = big.NewInt(1 << 1)
)

type ChannelConfig struct {
	Type ChannelConfigType `json:"type" url:"type"`
	Env  map[string]string `json:"env" url:"env"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (c *ChannelConfig) GetType() ChannelConfigType {
	if c == nil {
		return ""
	}
	return c.Type
}

func (c *ChannelConfig) GetEnv() map[string]string {
	if c == nil {
		return nil
	}
	return c.Env
}

func (c *ChannelConfig) GetExtraProperties() map[string]interface{} {
	if c == nil {
		return nil
	}
	return c.extraProperties
}

func (c *ChannelConfig) require(field *big.Int) {
	if c.explicitFields == nil {
		c.explicitFields = big.NewInt(0)
	}
	c.explicitFields.Or(c.explicitFields, field)
}

// SetType sets the Type field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *ChannelConfig) SetType(type_ ChannelConfigType) {
	c.Type = type_
	c.require(channelConfigFieldType)
}

// SetEnv sets the Env field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *ChannelConfig) SetEnv(env map[string]string) {
	c.Env = env
	c.require(channelConfigFieldEnv)
}

func (c *ChannelConfig) UnmarshalJSON(data []byte) error {
	type unmarshaler ChannelConfig
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*c = ChannelConfig(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *c)
	if err != nil {
		return err
	}
	c.extraProperties = extraProperties
	c.rawJSON = json.RawMessage(data)
	return nil
}

func (c *ChannelConfig) MarshalJSON() ([]byte, error) {
	type embed ChannelConfig
	var marshaler = struct {
		embed
	}{
		embed: embed(*c),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, c.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (c *ChannelConfig) String() string {
	if c == nil {
		return "<nil>"
	}
	if len(c.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(c.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(c); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", c)
}

type ChannelConfigType string

const (
	ChannelConfigTypeTelegram       ChannelConfigType = "telegram"
	ChannelConfigTypeDiscord        ChannelConfigType = "discord"
	ChannelConfigTypeSlack          ChannelConfigType = "slack"
	ChannelConfigTypeGoogleChat     ChannelConfigType = "google_chat"
	ChannelConfigTypeWhatsapp       ChannelConfigType = "whatsapp"
	ChannelConfigTypeSignal         ChannelConfigType = "signal"
	ChannelConfigTypeSms            ChannelConfigType = "sms"
	ChannelConfigTypeEmail          ChannelConfigType = "email"
	ChannelConfigTypeHomeassistant  ChannelConfigType = "homeassistant"
	ChannelConfigTypeMattermost     ChannelConfigType = "mattermost"
	ChannelConfigTypeMatrix         ChannelConfigType = "matrix"
	ChannelConfigTypeDingtalk       ChannelConfigType = "dingtalk"
	ChannelConfigTypeFeishu         ChannelConfigType = "feishu"
	ChannelConfigTypeWecom          ChannelConfigType = "wecom"
	ChannelConfigTypeWecomCallback  ChannelConfigType = "wecom_callback"
	ChannelConfigTypeWeixin         ChannelConfigType = "weixin"
	ChannelConfigTypeBluebubbles    ChannelConfigType = "bluebubbles"
	ChannelConfigTypeQq             ChannelConfigType = "qq"
	ChannelConfigTypeYuanbao        ChannelConfigType = "yuanbao"
	ChannelConfigTypeTeams          ChannelConfigType = "teams"
	ChannelConfigTypeLine           ChannelConfigType = "line"
	ChannelConfigTypeWebhook        ChannelConfigType = "webhook"
	ChannelConfigTypeMsgraphWebhook ChannelConfigType = "msgraph_webhook"
)

func NewChannelConfigTypeFromString(s string) (ChannelConfigType, error) {
	switch s {
	case "telegram":
		return ChannelConfigTypeTelegram, nil
	case "discord":
		return ChannelConfigTypeDiscord, nil
	case "slack":
		return ChannelConfigTypeSlack, nil
	case "google_chat":
		return ChannelConfigTypeGoogleChat, nil
	case "whatsapp":
		return ChannelConfigTypeWhatsapp, nil
	case "signal":
		return ChannelConfigTypeSignal, nil
	case "sms":
		return ChannelConfigTypeSms, nil
	case "email":
		return ChannelConfigTypeEmail, nil
	case "homeassistant":
		return ChannelConfigTypeHomeassistant, nil
	case "mattermost":
		return ChannelConfigTypeMattermost, nil
	case "matrix":
		return ChannelConfigTypeMatrix, nil
	case "dingtalk":
		return ChannelConfigTypeDingtalk, nil
	case "feishu":
		return ChannelConfigTypeFeishu, nil
	case "wecom":
		return ChannelConfigTypeWecom, nil
	case "wecom_callback":
		return ChannelConfigTypeWecomCallback, nil
	case "weixin":
		return ChannelConfigTypeWeixin, nil
	case "bluebubbles":
		return ChannelConfigTypeBluebubbles, nil
	case "qq":
		return ChannelConfigTypeQq, nil
	case "yuanbao":
		return ChannelConfigTypeYuanbao, nil
	case "teams":
		return ChannelConfigTypeTeams, nil
	case "line":
		return ChannelConfigTypeLine, nil
	case "webhook":
		return ChannelConfigTypeWebhook, nil
	case "msgraph_webhook":
		return ChannelConfigTypeMsgraphWebhook, nil
	}
	var t ChannelConfigType
	return "", fmt.Errorf("%s is not a valid %T", s, t)
}

func (c ChannelConfigType) Ptr() *ChannelConfigType {
	return &c
}

var (
	createAgentResponseFieldData      = big.NewInt(1 << 0)
	createAgentResponseFieldStatus    = big.NewInt(1 << 1)
	createAgentResponseFieldCode      = big.NewInt(1 << 2)
	createAgentResponseFieldMessage   = big.NewInt(1 << 3)
	createAgentResponseFieldTraceID   = big.NewInt(1 << 4)
	createAgentResponseFieldTimestamp = big.NewInt(1 << 5)
)

type CreateAgentResponse struct {
	Data      *Agent         `json:"data,omitempty" url:"data,omitempty"`
	Status    EnvelopeStatus `json:"status" url:"status"`
	Code      string         `json:"code" url:"code"`
	Message   string         `json:"message" url:"message"`
	TraceID   string         `json:"trace_id" url:"trace_id"`
	Timestamp time.Time      `json:"timestamp" url:"timestamp"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (c *CreateAgentResponse) GetData() *Agent {
	if c == nil {
		return nil
	}
	return c.Data
}

func (c *CreateAgentResponse) GetStatus() EnvelopeStatus {
	if c == nil {
		return ""
	}
	return c.Status
}

func (c *CreateAgentResponse) GetCode() string {
	if c == nil {
		return ""
	}
	return c.Code
}

func (c *CreateAgentResponse) GetMessage() string {
	if c == nil {
		return ""
	}
	return c.Message
}

func (c *CreateAgentResponse) GetTraceID() string {
	if c == nil {
		return ""
	}
	return c.TraceID
}

func (c *CreateAgentResponse) GetTimestamp() time.Time {
	if c == nil {
		return time.Time{}
	}
	return c.Timestamp
}

func (c *CreateAgentResponse) GetExtraProperties() map[string]interface{} {
	if c == nil {
		return nil
	}
	return c.extraProperties
}

func (c *CreateAgentResponse) require(field *big.Int) {
	if c.explicitFields == nil {
		c.explicitFields = big.NewInt(0)
	}
	c.explicitFields.Or(c.explicitFields, field)
}

// SetData sets the Data field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CreateAgentResponse) SetData(data *Agent) {
	c.Data = data
	c.require(createAgentResponseFieldData)
}

// SetStatus sets the Status field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CreateAgentResponse) SetStatus(status EnvelopeStatus) {
	c.Status = status
	c.require(createAgentResponseFieldStatus)
}

// SetCode sets the Code field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CreateAgentResponse) SetCode(code string) {
	c.Code = code
	c.require(createAgentResponseFieldCode)
}

// SetMessage sets the Message field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CreateAgentResponse) SetMessage(message string) {
	c.Message = message
	c.require(createAgentResponseFieldMessage)
}

// SetTraceID sets the TraceID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CreateAgentResponse) SetTraceID(traceID string) {
	c.TraceID = traceID
	c.require(createAgentResponseFieldTraceID)
}

// SetTimestamp sets the Timestamp field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CreateAgentResponse) SetTimestamp(timestamp time.Time) {
	c.Timestamp = timestamp
	c.require(createAgentResponseFieldTimestamp)
}

func (c *CreateAgentResponse) UnmarshalJSON(data []byte) error {
	type embed CreateAgentResponse
	var unmarshaler = struct {
		embed
		Timestamp *internal.DateTime `json:"timestamp"`
	}{
		embed: embed(*c),
	}
	if err := json.Unmarshal(data, &unmarshaler); err != nil {
		return err
	}
	*c = CreateAgentResponse(unmarshaler.embed)
	c.Timestamp = unmarshaler.Timestamp.Time()
	extraProperties, err := internal.ExtractExtraProperties(data, *c)
	if err != nil {
		return err
	}
	c.extraProperties = extraProperties
	c.rawJSON = json.RawMessage(data)
	return nil
}

func (c *CreateAgentResponse) MarshalJSON() ([]byte, error) {
	type embed CreateAgentResponse
	var marshaler = struct {
		embed
		Timestamp *internal.DateTime `json:"timestamp"`
	}{
		embed:     embed(*c),
		Timestamp: internal.NewDateTime(c.Timestamp),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, c.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (c *CreateAgentResponse) String() string {
	if c == nil {
		return "<nil>"
	}
	if len(c.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(c.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(c); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", c)
}

var (
	deleteAgentResponseFieldData      = big.NewInt(1 << 0)
	deleteAgentResponseFieldStatus    = big.NewInt(1 << 1)
	deleteAgentResponseFieldCode      = big.NewInt(1 << 2)
	deleteAgentResponseFieldMessage   = big.NewInt(1 << 3)
	deleteAgentResponseFieldTraceID   = big.NewInt(1 << 4)
	deleteAgentResponseFieldTimestamp = big.NewInt(1 << 5)
)

type DeleteAgentResponse struct {
	Data      *OkResponse    `json:"data,omitempty" url:"data,omitempty"`
	Status    EnvelopeStatus `json:"status" url:"status"`
	Code      string         `json:"code" url:"code"`
	Message   string         `json:"message" url:"message"`
	TraceID   string         `json:"trace_id" url:"trace_id"`
	Timestamp time.Time      `json:"timestamp" url:"timestamp"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (d *DeleteAgentResponse) GetData() *OkResponse {
	if d == nil {
		return nil
	}
	return d.Data
}

func (d *DeleteAgentResponse) GetStatus() EnvelopeStatus {
	if d == nil {
		return ""
	}
	return d.Status
}

func (d *DeleteAgentResponse) GetCode() string {
	if d == nil {
		return ""
	}
	return d.Code
}

func (d *DeleteAgentResponse) GetMessage() string {
	if d == nil {
		return ""
	}
	return d.Message
}

func (d *DeleteAgentResponse) GetTraceID() string {
	if d == nil {
		return ""
	}
	return d.TraceID
}

func (d *DeleteAgentResponse) GetTimestamp() time.Time {
	if d == nil {
		return time.Time{}
	}
	return d.Timestamp
}

func (d *DeleteAgentResponse) GetExtraProperties() map[string]interface{} {
	if d == nil {
		return nil
	}
	return d.extraProperties
}

func (d *DeleteAgentResponse) require(field *big.Int) {
	if d.explicitFields == nil {
		d.explicitFields = big.NewInt(0)
	}
	d.explicitFields.Or(d.explicitFields, field)
}

// SetData sets the Data field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (d *DeleteAgentResponse) SetData(data *OkResponse) {
	d.Data = data
	d.require(deleteAgentResponseFieldData)
}

// SetStatus sets the Status field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (d *DeleteAgentResponse) SetStatus(status EnvelopeStatus) {
	d.Status = status
	d.require(deleteAgentResponseFieldStatus)
}

// SetCode sets the Code field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (d *DeleteAgentResponse) SetCode(code string) {
	d.Code = code
	d.require(deleteAgentResponseFieldCode)
}

// SetMessage sets the Message field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (d *DeleteAgentResponse) SetMessage(message string) {
	d.Message = message
	d.require(deleteAgentResponseFieldMessage)
}

// SetTraceID sets the TraceID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (d *DeleteAgentResponse) SetTraceID(traceID string) {
	d.TraceID = traceID
	d.require(deleteAgentResponseFieldTraceID)
}

// SetTimestamp sets the Timestamp field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (d *DeleteAgentResponse) SetTimestamp(timestamp time.Time) {
	d.Timestamp = timestamp
	d.require(deleteAgentResponseFieldTimestamp)
}

func (d *DeleteAgentResponse) UnmarshalJSON(data []byte) error {
	type embed DeleteAgentResponse
	var unmarshaler = struct {
		embed
		Timestamp *internal.DateTime `json:"timestamp"`
	}{
		embed: embed(*d),
	}
	if err := json.Unmarshal(data, &unmarshaler); err != nil {
		return err
	}
	*d = DeleteAgentResponse(unmarshaler.embed)
	d.Timestamp = unmarshaler.Timestamp.Time()
	extraProperties, err := internal.ExtractExtraProperties(data, *d)
	if err != nil {
		return err
	}
	d.extraProperties = extraProperties
	d.rawJSON = json.RawMessage(data)
	return nil
}

func (d *DeleteAgentResponse) MarshalJSON() ([]byte, error) {
	type embed DeleteAgentResponse
	var marshaler = struct {
		embed
		Timestamp *internal.DateTime `json:"timestamp"`
	}{
		embed:     embed(*d),
		Timestamp: internal.NewDateTime(d.Timestamp),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, d.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (d *DeleteAgentResponse) String() string {
	if d == nil {
		return "<nil>"
	}
	if len(d.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(d.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(d); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", d)
}

var (
	getAgentChannelsResponseFieldData      = big.NewInt(1 << 0)
	getAgentChannelsResponseFieldStatus    = big.NewInt(1 << 1)
	getAgentChannelsResponseFieldCode      = big.NewInt(1 << 2)
	getAgentChannelsResponseFieldMessage   = big.NewInt(1 << 3)
	getAgentChannelsResponseFieldTraceID   = big.NewInt(1 << 4)
	getAgentChannelsResponseFieldTimestamp = big.NewInt(1 << 5)
)

type GetAgentChannelsResponse struct {
	Data      []*ChannelConfig `json:"data,omitempty" url:"data,omitempty"`
	Status    EnvelopeStatus   `json:"status" url:"status"`
	Code      string           `json:"code" url:"code"`
	Message   string           `json:"message" url:"message"`
	TraceID   string           `json:"trace_id" url:"trace_id"`
	Timestamp time.Time        `json:"timestamp" url:"timestamp"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (g *GetAgentChannelsResponse) GetData() []*ChannelConfig {
	if g == nil {
		return nil
	}
	return g.Data
}

func (g *GetAgentChannelsResponse) GetStatus() EnvelopeStatus {
	if g == nil {
		return ""
	}
	return g.Status
}

func (g *GetAgentChannelsResponse) GetCode() string {
	if g == nil {
		return ""
	}
	return g.Code
}

func (g *GetAgentChannelsResponse) GetMessage() string {
	if g == nil {
		return ""
	}
	return g.Message
}

func (g *GetAgentChannelsResponse) GetTraceID() string {
	if g == nil {
		return ""
	}
	return g.TraceID
}

func (g *GetAgentChannelsResponse) GetTimestamp() time.Time {
	if g == nil {
		return time.Time{}
	}
	return g.Timestamp
}

func (g *GetAgentChannelsResponse) GetExtraProperties() map[string]interface{} {
	if g == nil {
		return nil
	}
	return g.extraProperties
}

func (g *GetAgentChannelsResponse) require(field *big.Int) {
	if g.explicitFields == nil {
		g.explicitFields = big.NewInt(0)
	}
	g.explicitFields.Or(g.explicitFields, field)
}

// SetData sets the Data field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GetAgentChannelsResponse) SetData(data []*ChannelConfig) {
	g.Data = data
	g.require(getAgentChannelsResponseFieldData)
}

// SetStatus sets the Status field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GetAgentChannelsResponse) SetStatus(status EnvelopeStatus) {
	g.Status = status
	g.require(getAgentChannelsResponseFieldStatus)
}

// SetCode sets the Code field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GetAgentChannelsResponse) SetCode(code string) {
	g.Code = code
	g.require(getAgentChannelsResponseFieldCode)
}

// SetMessage sets the Message field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GetAgentChannelsResponse) SetMessage(message string) {
	g.Message = message
	g.require(getAgentChannelsResponseFieldMessage)
}

// SetTraceID sets the TraceID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GetAgentChannelsResponse) SetTraceID(traceID string) {
	g.TraceID = traceID
	g.require(getAgentChannelsResponseFieldTraceID)
}

// SetTimestamp sets the Timestamp field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GetAgentChannelsResponse) SetTimestamp(timestamp time.Time) {
	g.Timestamp = timestamp
	g.require(getAgentChannelsResponseFieldTimestamp)
}

func (g *GetAgentChannelsResponse) UnmarshalJSON(data []byte) error {
	type embed GetAgentChannelsResponse
	var unmarshaler = struct {
		embed
		Timestamp *internal.DateTime `json:"timestamp"`
	}{
		embed: embed(*g),
	}
	if err := json.Unmarshal(data, &unmarshaler); err != nil {
		return err
	}
	*g = GetAgentChannelsResponse(unmarshaler.embed)
	g.Timestamp = unmarshaler.Timestamp.Time()
	extraProperties, err := internal.ExtractExtraProperties(data, *g)
	if err != nil {
		return err
	}
	g.extraProperties = extraProperties
	g.rawJSON = json.RawMessage(data)
	return nil
}

func (g *GetAgentChannelsResponse) MarshalJSON() ([]byte, error) {
	type embed GetAgentChannelsResponse
	var marshaler = struct {
		embed
		Timestamp *internal.DateTime `json:"timestamp"`
	}{
		embed:     embed(*g),
		Timestamp: internal.NewDateTime(g.Timestamp),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, g.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (g *GetAgentChannelsResponse) String() string {
	if g == nil {
		return "<nil>"
	}
	if len(g.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(g.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(g); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", g)
}

var (
	getAgentResponseFieldData      = big.NewInt(1 << 0)
	getAgentResponseFieldStatus    = big.NewInt(1 << 1)
	getAgentResponseFieldCode      = big.NewInt(1 << 2)
	getAgentResponseFieldMessage   = big.NewInt(1 << 3)
	getAgentResponseFieldTraceID   = big.NewInt(1 << 4)
	getAgentResponseFieldTimestamp = big.NewInt(1 << 5)
)

type GetAgentResponse struct {
	Data      *Agent         `json:"data,omitempty" url:"data,omitempty"`
	Status    EnvelopeStatus `json:"status" url:"status"`
	Code      string         `json:"code" url:"code"`
	Message   string         `json:"message" url:"message"`
	TraceID   string         `json:"trace_id" url:"trace_id"`
	Timestamp time.Time      `json:"timestamp" url:"timestamp"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (g *GetAgentResponse) GetData() *Agent {
	if g == nil {
		return nil
	}
	return g.Data
}

func (g *GetAgentResponse) GetStatus() EnvelopeStatus {
	if g == nil {
		return ""
	}
	return g.Status
}

func (g *GetAgentResponse) GetCode() string {
	if g == nil {
		return ""
	}
	return g.Code
}

func (g *GetAgentResponse) GetMessage() string {
	if g == nil {
		return ""
	}
	return g.Message
}

func (g *GetAgentResponse) GetTraceID() string {
	if g == nil {
		return ""
	}
	return g.TraceID
}

func (g *GetAgentResponse) GetTimestamp() time.Time {
	if g == nil {
		return time.Time{}
	}
	return g.Timestamp
}

func (g *GetAgentResponse) GetExtraProperties() map[string]interface{} {
	if g == nil {
		return nil
	}
	return g.extraProperties
}

func (g *GetAgentResponse) require(field *big.Int) {
	if g.explicitFields == nil {
		g.explicitFields = big.NewInt(0)
	}
	g.explicitFields.Or(g.explicitFields, field)
}

// SetData sets the Data field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GetAgentResponse) SetData(data *Agent) {
	g.Data = data
	g.require(getAgentResponseFieldData)
}

// SetStatus sets the Status field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GetAgentResponse) SetStatus(status EnvelopeStatus) {
	g.Status = status
	g.require(getAgentResponseFieldStatus)
}

// SetCode sets the Code field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GetAgentResponse) SetCode(code string) {
	g.Code = code
	g.require(getAgentResponseFieldCode)
}

// SetMessage sets the Message field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GetAgentResponse) SetMessage(message string) {
	g.Message = message
	g.require(getAgentResponseFieldMessage)
}

// SetTraceID sets the TraceID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GetAgentResponse) SetTraceID(traceID string) {
	g.TraceID = traceID
	g.require(getAgentResponseFieldTraceID)
}

// SetTimestamp sets the Timestamp field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GetAgentResponse) SetTimestamp(timestamp time.Time) {
	g.Timestamp = timestamp
	g.require(getAgentResponseFieldTimestamp)
}

func (g *GetAgentResponse) UnmarshalJSON(data []byte) error {
	type embed GetAgentResponse
	var unmarshaler = struct {
		embed
		Timestamp *internal.DateTime `json:"timestamp"`
	}{
		embed: embed(*g),
	}
	if err := json.Unmarshal(data, &unmarshaler); err != nil {
		return err
	}
	*g = GetAgentResponse(unmarshaler.embed)
	g.Timestamp = unmarshaler.Timestamp.Time()
	extraProperties, err := internal.ExtractExtraProperties(data, *g)
	if err != nil {
		return err
	}
	g.extraProperties = extraProperties
	g.rawJSON = json.RawMessage(data)
	return nil
}

func (g *GetAgentResponse) MarshalJSON() ([]byte, error) {
	type embed GetAgentResponse
	var marshaler = struct {
		embed
		Timestamp *internal.DateTime `json:"timestamp"`
	}{
		embed:     embed(*g),
		Timestamp: internal.NewDateTime(g.Timestamp),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, g.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (g *GetAgentResponse) String() string {
	if g == nil {
		return "<nil>"
	}
	if len(g.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(g.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(g); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", g)
}

var (
	listAgentsResponseFieldData      = big.NewInt(1 << 0)
	listAgentsResponseFieldStatus    = big.NewInt(1 << 1)
	listAgentsResponseFieldCode      = big.NewInt(1 << 2)
	listAgentsResponseFieldMessage   = big.NewInt(1 << 3)
	listAgentsResponseFieldTraceID   = big.NewInt(1 << 4)
	listAgentsResponseFieldTimestamp = big.NewInt(1 << 5)
)

type ListAgentsResponse struct {
	Data      []*Agent       `json:"data,omitempty" url:"data,omitempty"`
	Status    EnvelopeStatus `json:"status" url:"status"`
	Code      string         `json:"code" url:"code"`
	Message   string         `json:"message" url:"message"`
	TraceID   string         `json:"trace_id" url:"trace_id"`
	Timestamp time.Time      `json:"timestamp" url:"timestamp"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (l *ListAgentsResponse) GetData() []*Agent {
	if l == nil {
		return nil
	}
	return l.Data
}

func (l *ListAgentsResponse) GetStatus() EnvelopeStatus {
	if l == nil {
		return ""
	}
	return l.Status
}

func (l *ListAgentsResponse) GetCode() string {
	if l == nil {
		return ""
	}
	return l.Code
}

func (l *ListAgentsResponse) GetMessage() string {
	if l == nil {
		return ""
	}
	return l.Message
}

func (l *ListAgentsResponse) GetTraceID() string {
	if l == nil {
		return ""
	}
	return l.TraceID
}

func (l *ListAgentsResponse) GetTimestamp() time.Time {
	if l == nil {
		return time.Time{}
	}
	return l.Timestamp
}

func (l *ListAgentsResponse) GetExtraProperties() map[string]interface{} {
	if l == nil {
		return nil
	}
	return l.extraProperties
}

func (l *ListAgentsResponse) require(field *big.Int) {
	if l.explicitFields == nil {
		l.explicitFields = big.NewInt(0)
	}
	l.explicitFields.Or(l.explicitFields, field)
}

// SetData sets the Data field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *ListAgentsResponse) SetData(data []*Agent) {
	l.Data = data
	l.require(listAgentsResponseFieldData)
}

// SetStatus sets the Status field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *ListAgentsResponse) SetStatus(status EnvelopeStatus) {
	l.Status = status
	l.require(listAgentsResponseFieldStatus)
}

// SetCode sets the Code field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *ListAgentsResponse) SetCode(code string) {
	l.Code = code
	l.require(listAgentsResponseFieldCode)
}

// SetMessage sets the Message field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *ListAgentsResponse) SetMessage(message string) {
	l.Message = message
	l.require(listAgentsResponseFieldMessage)
}

// SetTraceID sets the TraceID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *ListAgentsResponse) SetTraceID(traceID string) {
	l.TraceID = traceID
	l.require(listAgentsResponseFieldTraceID)
}

// SetTimestamp sets the Timestamp field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *ListAgentsResponse) SetTimestamp(timestamp time.Time) {
	l.Timestamp = timestamp
	l.require(listAgentsResponseFieldTimestamp)
}

func (l *ListAgentsResponse) UnmarshalJSON(data []byte) error {
	type embed ListAgentsResponse
	var unmarshaler = struct {
		embed
		Timestamp *internal.DateTime `json:"timestamp"`
	}{
		embed: embed(*l),
	}
	if err := json.Unmarshal(data, &unmarshaler); err != nil {
		return err
	}
	*l = ListAgentsResponse(unmarshaler.embed)
	l.Timestamp = unmarshaler.Timestamp.Time()
	extraProperties, err := internal.ExtractExtraProperties(data, *l)
	if err != nil {
		return err
	}
	l.extraProperties = extraProperties
	l.rawJSON = json.RawMessage(data)
	return nil
}

func (l *ListAgentsResponse) MarshalJSON() ([]byte, error) {
	type embed ListAgentsResponse
	var marshaler = struct {
		embed
		Timestamp *internal.DateTime `json:"timestamp"`
	}{
		embed:     embed(*l),
		Timestamp: internal.NewDateTime(l.Timestamp),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, l.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (l *ListAgentsResponse) String() string {
	if l == nil {
		return "<nil>"
	}
	if len(l.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(l.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(l); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", l)
}

var (
	startAgentResponseFieldData      = big.NewInt(1 << 0)
	startAgentResponseFieldStatus    = big.NewInt(1 << 1)
	startAgentResponseFieldCode      = big.NewInt(1 << 2)
	startAgentResponseFieldMessage   = big.NewInt(1 << 3)
	startAgentResponseFieldTraceID   = big.NewInt(1 << 4)
	startAgentResponseFieldTimestamp = big.NewInt(1 << 5)
)

type StartAgentResponse struct {
	Data      *OkResponse    `json:"data,omitempty" url:"data,omitempty"`
	Status    EnvelopeStatus `json:"status" url:"status"`
	Code      string         `json:"code" url:"code"`
	Message   string         `json:"message" url:"message"`
	TraceID   string         `json:"trace_id" url:"trace_id"`
	Timestamp time.Time      `json:"timestamp" url:"timestamp"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (s *StartAgentResponse) GetData() *OkResponse {
	if s == nil {
		return nil
	}
	return s.Data
}

func (s *StartAgentResponse) GetStatus() EnvelopeStatus {
	if s == nil {
		return ""
	}
	return s.Status
}

func (s *StartAgentResponse) GetCode() string {
	if s == nil {
		return ""
	}
	return s.Code
}

func (s *StartAgentResponse) GetMessage() string {
	if s == nil {
		return ""
	}
	return s.Message
}

func (s *StartAgentResponse) GetTraceID() string {
	if s == nil {
		return ""
	}
	return s.TraceID
}

func (s *StartAgentResponse) GetTimestamp() time.Time {
	if s == nil {
		return time.Time{}
	}
	return s.Timestamp
}

func (s *StartAgentResponse) GetExtraProperties() map[string]interface{} {
	if s == nil {
		return nil
	}
	return s.extraProperties
}

func (s *StartAgentResponse) require(field *big.Int) {
	if s.explicitFields == nil {
		s.explicitFields = big.NewInt(0)
	}
	s.explicitFields.Or(s.explicitFields, field)
}

// SetData sets the Data field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (s *StartAgentResponse) SetData(data *OkResponse) {
	s.Data = data
	s.require(startAgentResponseFieldData)
}

// SetStatus sets the Status field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (s *StartAgentResponse) SetStatus(status EnvelopeStatus) {
	s.Status = status
	s.require(startAgentResponseFieldStatus)
}

// SetCode sets the Code field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (s *StartAgentResponse) SetCode(code string) {
	s.Code = code
	s.require(startAgentResponseFieldCode)
}

// SetMessage sets the Message field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (s *StartAgentResponse) SetMessage(message string) {
	s.Message = message
	s.require(startAgentResponseFieldMessage)
}

// SetTraceID sets the TraceID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (s *StartAgentResponse) SetTraceID(traceID string) {
	s.TraceID = traceID
	s.require(startAgentResponseFieldTraceID)
}

// SetTimestamp sets the Timestamp field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (s *StartAgentResponse) SetTimestamp(timestamp time.Time) {
	s.Timestamp = timestamp
	s.require(startAgentResponseFieldTimestamp)
}

func (s *StartAgentResponse) UnmarshalJSON(data []byte) error {
	type embed StartAgentResponse
	var unmarshaler = struct {
		embed
		Timestamp *internal.DateTime `json:"timestamp"`
	}{
		embed: embed(*s),
	}
	if err := json.Unmarshal(data, &unmarshaler); err != nil {
		return err
	}
	*s = StartAgentResponse(unmarshaler.embed)
	s.Timestamp = unmarshaler.Timestamp.Time()
	extraProperties, err := internal.ExtractExtraProperties(data, *s)
	if err != nil {
		return err
	}
	s.extraProperties = extraProperties
	s.rawJSON = json.RawMessage(data)
	return nil
}

func (s *StartAgentResponse) MarshalJSON() ([]byte, error) {
	type embed StartAgentResponse
	var marshaler = struct {
		embed
		Timestamp *internal.DateTime `json:"timestamp"`
	}{
		embed:     embed(*s),
		Timestamp: internal.NewDateTime(s.Timestamp),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, s.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (s *StartAgentResponse) String() string {
	if s == nil {
		return "<nil>"
	}
	if len(s.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(s.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(s); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", s)
}

var (
	stopAgentResponseFieldData      = big.NewInt(1 << 0)
	stopAgentResponseFieldStatus    = big.NewInt(1 << 1)
	stopAgentResponseFieldCode      = big.NewInt(1 << 2)
	stopAgentResponseFieldMessage   = big.NewInt(1 << 3)
	stopAgentResponseFieldTraceID   = big.NewInt(1 << 4)
	stopAgentResponseFieldTimestamp = big.NewInt(1 << 5)
)

type StopAgentResponse struct {
	Data      *OkResponse    `json:"data,omitempty" url:"data,omitempty"`
	Status    EnvelopeStatus `json:"status" url:"status"`
	Code      string         `json:"code" url:"code"`
	Message   string         `json:"message" url:"message"`
	TraceID   string         `json:"trace_id" url:"trace_id"`
	Timestamp time.Time      `json:"timestamp" url:"timestamp"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (s *StopAgentResponse) GetData() *OkResponse {
	if s == nil {
		return nil
	}
	return s.Data
}

func (s *StopAgentResponse) GetStatus() EnvelopeStatus {
	if s == nil {
		return ""
	}
	return s.Status
}

func (s *StopAgentResponse) GetCode() string {
	if s == nil {
		return ""
	}
	return s.Code
}

func (s *StopAgentResponse) GetMessage() string {
	if s == nil {
		return ""
	}
	return s.Message
}

func (s *StopAgentResponse) GetTraceID() string {
	if s == nil {
		return ""
	}
	return s.TraceID
}

func (s *StopAgentResponse) GetTimestamp() time.Time {
	if s == nil {
		return time.Time{}
	}
	return s.Timestamp
}

func (s *StopAgentResponse) GetExtraProperties() map[string]interface{} {
	if s == nil {
		return nil
	}
	return s.extraProperties
}

func (s *StopAgentResponse) require(field *big.Int) {
	if s.explicitFields == nil {
		s.explicitFields = big.NewInt(0)
	}
	s.explicitFields.Or(s.explicitFields, field)
}

// SetData sets the Data field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (s *StopAgentResponse) SetData(data *OkResponse) {
	s.Data = data
	s.require(stopAgentResponseFieldData)
}

// SetStatus sets the Status field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (s *StopAgentResponse) SetStatus(status EnvelopeStatus) {
	s.Status = status
	s.require(stopAgentResponseFieldStatus)
}

// SetCode sets the Code field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (s *StopAgentResponse) SetCode(code string) {
	s.Code = code
	s.require(stopAgentResponseFieldCode)
}

// SetMessage sets the Message field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (s *StopAgentResponse) SetMessage(message string) {
	s.Message = message
	s.require(stopAgentResponseFieldMessage)
}

// SetTraceID sets the TraceID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (s *StopAgentResponse) SetTraceID(traceID string) {
	s.TraceID = traceID
	s.require(stopAgentResponseFieldTraceID)
}

// SetTimestamp sets the Timestamp field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (s *StopAgentResponse) SetTimestamp(timestamp time.Time) {
	s.Timestamp = timestamp
	s.require(stopAgentResponseFieldTimestamp)
}

func (s *StopAgentResponse) UnmarshalJSON(data []byte) error {
	type embed StopAgentResponse
	var unmarshaler = struct {
		embed
		Timestamp *internal.DateTime `json:"timestamp"`
	}{
		embed: embed(*s),
	}
	if err := json.Unmarshal(data, &unmarshaler); err != nil {
		return err
	}
	*s = StopAgentResponse(unmarshaler.embed)
	s.Timestamp = unmarshaler.Timestamp.Time()
	extraProperties, err := internal.ExtractExtraProperties(data, *s)
	if err != nil {
		return err
	}
	s.extraProperties = extraProperties
	s.rawJSON = json.RawMessage(data)
	return nil
}

func (s *StopAgentResponse) MarshalJSON() ([]byte, error) {
	type embed StopAgentResponse
	var marshaler = struct {
		embed
		Timestamp *internal.DateTime `json:"timestamp"`
	}{
		embed:     embed(*s),
		Timestamp: internal.NewDateTime(s.Timestamp),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, s.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (s *StopAgentResponse) String() string {
	if s == nil {
		return "<nil>"
	}
	if len(s.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(s.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(s); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", s)
}

var (
	updateAgentChannelsResponseFieldData      = big.NewInt(1 << 0)
	updateAgentChannelsResponseFieldStatus    = big.NewInt(1 << 1)
	updateAgentChannelsResponseFieldCode      = big.NewInt(1 << 2)
	updateAgentChannelsResponseFieldMessage   = big.NewInt(1 << 3)
	updateAgentChannelsResponseFieldTraceID   = big.NewInt(1 << 4)
	updateAgentChannelsResponseFieldTimestamp = big.NewInt(1 << 5)
)

type UpdateAgentChannelsResponse struct {
	Data      []*ChannelConfig `json:"data,omitempty" url:"data,omitempty"`
	Status    EnvelopeStatus   `json:"status" url:"status"`
	Code      string           `json:"code" url:"code"`
	Message   string           `json:"message" url:"message"`
	TraceID   string           `json:"trace_id" url:"trace_id"`
	Timestamp time.Time        `json:"timestamp" url:"timestamp"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (u *UpdateAgentChannelsResponse) GetData() []*ChannelConfig {
	if u == nil {
		return nil
	}
	return u.Data
}

func (u *UpdateAgentChannelsResponse) GetStatus() EnvelopeStatus {
	if u == nil {
		return ""
	}
	return u.Status
}

func (u *UpdateAgentChannelsResponse) GetCode() string {
	if u == nil {
		return ""
	}
	return u.Code
}

func (u *UpdateAgentChannelsResponse) GetMessage() string {
	if u == nil {
		return ""
	}
	return u.Message
}

func (u *UpdateAgentChannelsResponse) GetTraceID() string {
	if u == nil {
		return ""
	}
	return u.TraceID
}

func (u *UpdateAgentChannelsResponse) GetTimestamp() time.Time {
	if u == nil {
		return time.Time{}
	}
	return u.Timestamp
}

func (u *UpdateAgentChannelsResponse) GetExtraProperties() map[string]interface{} {
	if u == nil {
		return nil
	}
	return u.extraProperties
}

func (u *UpdateAgentChannelsResponse) require(field *big.Int) {
	if u.explicitFields == nil {
		u.explicitFields = big.NewInt(0)
	}
	u.explicitFields.Or(u.explicitFields, field)
}

// SetData sets the Data field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (u *UpdateAgentChannelsResponse) SetData(data []*ChannelConfig) {
	u.Data = data
	u.require(updateAgentChannelsResponseFieldData)
}

// SetStatus sets the Status field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (u *UpdateAgentChannelsResponse) SetStatus(status EnvelopeStatus) {
	u.Status = status
	u.require(updateAgentChannelsResponseFieldStatus)
}

// SetCode sets the Code field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (u *UpdateAgentChannelsResponse) SetCode(code string) {
	u.Code = code
	u.require(updateAgentChannelsResponseFieldCode)
}

// SetMessage sets the Message field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (u *UpdateAgentChannelsResponse) SetMessage(message string) {
	u.Message = message
	u.require(updateAgentChannelsResponseFieldMessage)
}

// SetTraceID sets the TraceID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (u *UpdateAgentChannelsResponse) SetTraceID(traceID string) {
	u.TraceID = traceID
	u.require(updateAgentChannelsResponseFieldTraceID)
}

// SetTimestamp sets the Timestamp field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (u *UpdateAgentChannelsResponse) SetTimestamp(timestamp time.Time) {
	u.Timestamp = timestamp
	u.require(updateAgentChannelsResponseFieldTimestamp)
}

func (u *UpdateAgentChannelsResponse) UnmarshalJSON(data []byte) error {
	type embed UpdateAgentChannelsResponse
	var unmarshaler = struct {
		embed
		Timestamp *internal.DateTime `json:"timestamp"`
	}{
		embed: embed(*u),
	}
	if err := json.Unmarshal(data, &unmarshaler); err != nil {
		return err
	}
	*u = UpdateAgentChannelsResponse(unmarshaler.embed)
	u.Timestamp = unmarshaler.Timestamp.Time()
	extraProperties, err := internal.ExtractExtraProperties(data, *u)
	if err != nil {
		return err
	}
	u.extraProperties = extraProperties
	u.rawJSON = json.RawMessage(data)
	return nil
}

func (u *UpdateAgentChannelsResponse) MarshalJSON() ([]byte, error) {
	type embed UpdateAgentChannelsResponse
	var marshaler = struct {
		embed
		Timestamp *internal.DateTime `json:"timestamp"`
	}{
		embed:     embed(*u),
		Timestamp: internal.NewDateTime(u.Timestamp),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, u.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (u *UpdateAgentChannelsResponse) String() string {
	if u == nil {
		return "<nil>"
	}
	if len(u.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(u.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(u); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", u)
}

var (
	updateAgentResponseFieldData      = big.NewInt(1 << 0)
	updateAgentResponseFieldStatus    = big.NewInt(1 << 1)
	updateAgentResponseFieldCode      = big.NewInt(1 << 2)
	updateAgentResponseFieldMessage   = big.NewInt(1 << 3)
	updateAgentResponseFieldTraceID   = big.NewInt(1 << 4)
	updateAgentResponseFieldTimestamp = big.NewInt(1 << 5)
)

type UpdateAgentResponse struct {
	Data      *Agent         `json:"data,omitempty" url:"data,omitempty"`
	Status    EnvelopeStatus `json:"status" url:"status"`
	Code      string         `json:"code" url:"code"`
	Message   string         `json:"message" url:"message"`
	TraceID   string         `json:"trace_id" url:"trace_id"`
	Timestamp time.Time      `json:"timestamp" url:"timestamp"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (u *UpdateAgentResponse) GetData() *Agent {
	if u == nil {
		return nil
	}
	return u.Data
}

func (u *UpdateAgentResponse) GetStatus() EnvelopeStatus {
	if u == nil {
		return ""
	}
	return u.Status
}

func (u *UpdateAgentResponse) GetCode() string {
	if u == nil {
		return ""
	}
	return u.Code
}

func (u *UpdateAgentResponse) GetMessage() string {
	if u == nil {
		return ""
	}
	return u.Message
}

func (u *UpdateAgentResponse) GetTraceID() string {
	if u == nil {
		return ""
	}
	return u.TraceID
}

func (u *UpdateAgentResponse) GetTimestamp() time.Time {
	if u == nil {
		return time.Time{}
	}
	return u.Timestamp
}

func (u *UpdateAgentResponse) GetExtraProperties() map[string]interface{} {
	if u == nil {
		return nil
	}
	return u.extraProperties
}

func (u *UpdateAgentResponse) require(field *big.Int) {
	if u.explicitFields == nil {
		u.explicitFields = big.NewInt(0)
	}
	u.explicitFields.Or(u.explicitFields, field)
}

// SetData sets the Data field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (u *UpdateAgentResponse) SetData(data *Agent) {
	u.Data = data
	u.require(updateAgentResponseFieldData)
}

// SetStatus sets the Status field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (u *UpdateAgentResponse) SetStatus(status EnvelopeStatus) {
	u.Status = status
	u.require(updateAgentResponseFieldStatus)
}

// SetCode sets the Code field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (u *UpdateAgentResponse) SetCode(code string) {
	u.Code = code
	u.require(updateAgentResponseFieldCode)
}

// SetMessage sets the Message field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (u *UpdateAgentResponse) SetMessage(message string) {
	u.Message = message
	u.require(updateAgentResponseFieldMessage)
}

// SetTraceID sets the TraceID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (u *UpdateAgentResponse) SetTraceID(traceID string) {
	u.TraceID = traceID
	u.require(updateAgentResponseFieldTraceID)
}

// SetTimestamp sets the Timestamp field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (u *UpdateAgentResponse) SetTimestamp(timestamp time.Time) {
	u.Timestamp = timestamp
	u.require(updateAgentResponseFieldTimestamp)
}

func (u *UpdateAgentResponse) UnmarshalJSON(data []byte) error {
	type embed UpdateAgentResponse
	var unmarshaler = struct {
		embed
		Timestamp *internal.DateTime `json:"timestamp"`
	}{
		embed: embed(*u),
	}
	if err := json.Unmarshal(data, &unmarshaler); err != nil {
		return err
	}
	*u = UpdateAgentResponse(unmarshaler.embed)
	u.Timestamp = unmarshaler.Timestamp.Time()
	extraProperties, err := internal.ExtractExtraProperties(data, *u)
	if err != nil {
		return err
	}
	u.extraProperties = extraProperties
	u.rawJSON = json.RawMessage(data)
	return nil
}

func (u *UpdateAgentResponse) MarshalJSON() ([]byte, error) {
	type embed UpdateAgentResponse
	var marshaler = struct {
		embed
		Timestamp *internal.DateTime `json:"timestamp"`
	}{
		embed:     embed(*u),
		Timestamp: internal.NewDateTime(u.Timestamp),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, u.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (u *UpdateAgentResponse) String() string {
	if u == nil {
		return "<nil>"
	}
	if len(u.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(u.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(u); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", u)
}

var (
	agentUpdateRequestFieldIdempotencyKey       = big.NewInt(1 << 0)
	agentUpdateRequestFieldID                   = big.NewInt(1 << 1)
	agentUpdateRequestFieldDisplayName          = big.NewInt(1 << 2)
	agentUpdateRequestFieldLlmProvider          = big.NewInt(1 << 3)
	agentUpdateRequestFieldLlmModel             = big.NewInt(1 << 4)
	agentUpdateRequestFieldLlmBaseURL           = big.NewInt(1 << 5)
	agentUpdateRequestFieldLlmAPIKey            = big.NewInt(1 << 6)
	agentUpdateRequestFieldKnowledgeIDs         = big.NewInt(1 << 7)
	agentUpdateRequestFieldEnabledTools         = big.NewInt(1 << 8)
	agentUpdateRequestFieldCameraToolIDs        = big.NewInt(1 << 9)
	agentUpdateRequestFieldMcpDynamicServerIDs  = big.NewInt(1 << 10)
	agentUpdateRequestFieldMcpDynamicToolFilter = big.NewInt(1 << 11)
)

type AgentUpdateRequest struct {
	// Idempotency key cho mutation (tránh double-submit).
	IdempotencyKey *string `json:"-" url:"-"`
	ID             string  `json:"-" url:"-"`
	DisplayName    *string `json:"display_name,omitempty" url:"-"`
	LlmProvider    *string `json:"llm_provider,omitempty" url:"-"`
	LlmModel       *string `json:"llm_model,omitempty" url:"-"`
	LlmBaseURL     *string `json:"llm_base_url,omitempty" url:"-"`
	LlmAPIKey      *string `json:"llm_api_key,omitempty" url:"-"`
	// Omit/null = giữ nguyên; [] = xoá.
	KnowledgeIDs []string `json:"knowledge_ids,omitempty" url:"-"`
	// Omit/null = giữ nguyên; [] = xoá.
	EnabledTools []string `json:"enabled_tools,omitempty" url:"-"`
	// Omit/null = giữ nguyên; [] = xoá. Chỉ hiệu lực khi tool org_cameras được bật.
	CameraToolIDs []string `json:"camera_tool_ids,omitempty" url:"-"`
	// Omit/null = giữ nguyên; [] = xoá.
	McpDynamicServerIDs []string `json:"mcp_dynamic_server_ids,omitempty" url:"-"`
	// Omit/null = giữ nguyên; {} = xoá.
	McpDynamicToolFilter map[string]any `json:"mcp_dynamic_tool_filter,omitempty" url:"-"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
}

func (a *AgentUpdateRequest) require(field *big.Int) {
	if a.explicitFields == nil {
		a.explicitFields = big.NewInt(0)
	}
	a.explicitFields.Or(a.explicitFields, field)
}

// SetIdempotencyKey sets the IdempotencyKey field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (a *AgentUpdateRequest) SetIdempotencyKey(idempotencyKey *string) {
	a.IdempotencyKey = idempotencyKey
	a.require(agentUpdateRequestFieldIdempotencyKey)
}

// SetID sets the ID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (a *AgentUpdateRequest) SetID(id string) {
	a.ID = id
	a.require(agentUpdateRequestFieldID)
}

// SetDisplayName sets the DisplayName field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (a *AgentUpdateRequest) SetDisplayName(displayName *string) {
	a.DisplayName = displayName
	a.require(agentUpdateRequestFieldDisplayName)
}

// SetLlmProvider sets the LlmProvider field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (a *AgentUpdateRequest) SetLlmProvider(llmProvider *string) {
	a.LlmProvider = llmProvider
	a.require(agentUpdateRequestFieldLlmProvider)
}

// SetLlmModel sets the LlmModel field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (a *AgentUpdateRequest) SetLlmModel(llmModel *string) {
	a.LlmModel = llmModel
	a.require(agentUpdateRequestFieldLlmModel)
}

// SetLlmBaseURL sets the LlmBaseURL field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (a *AgentUpdateRequest) SetLlmBaseURL(llmBaseURL *string) {
	a.LlmBaseURL = llmBaseURL
	a.require(agentUpdateRequestFieldLlmBaseURL)
}

// SetLlmAPIKey sets the LlmAPIKey field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (a *AgentUpdateRequest) SetLlmAPIKey(llmAPIKey *string) {
	a.LlmAPIKey = llmAPIKey
	a.require(agentUpdateRequestFieldLlmAPIKey)
}

// SetKnowledgeIDs sets the KnowledgeIDs field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (a *AgentUpdateRequest) SetKnowledgeIDs(knowledgeIDs []string) {
	a.KnowledgeIDs = knowledgeIDs
	a.require(agentUpdateRequestFieldKnowledgeIDs)
}

// SetEnabledTools sets the EnabledTools field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (a *AgentUpdateRequest) SetEnabledTools(enabledTools []string) {
	a.EnabledTools = enabledTools
	a.require(agentUpdateRequestFieldEnabledTools)
}

// SetCameraToolIDs sets the CameraToolIDs field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (a *AgentUpdateRequest) SetCameraToolIDs(cameraToolIDs []string) {
	a.CameraToolIDs = cameraToolIDs
	a.require(agentUpdateRequestFieldCameraToolIDs)
}

// SetMcpDynamicServerIDs sets the McpDynamicServerIDs field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (a *AgentUpdateRequest) SetMcpDynamicServerIDs(mcpDynamicServerIDs []string) {
	a.McpDynamicServerIDs = mcpDynamicServerIDs
	a.require(agentUpdateRequestFieldMcpDynamicServerIDs)
}

// SetMcpDynamicToolFilter sets the McpDynamicToolFilter field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (a *AgentUpdateRequest) SetMcpDynamicToolFilter(mcpDynamicToolFilter map[string]any) {
	a.McpDynamicToolFilter = mcpDynamicToolFilter
	a.require(agentUpdateRequestFieldMcpDynamicToolFilter)
}

func (a *AgentUpdateRequest) UnmarshalJSON(data []byte) error {
	type unmarshaler AgentUpdateRequest
	var body unmarshaler
	if err := json.Unmarshal(data, &body); err != nil {
		return err
	}
	*a = AgentUpdateRequest(body)
	return nil
}

func (a *AgentUpdateRequest) MarshalJSON() ([]byte, error) {
	type embed AgentUpdateRequest
	var marshaler = struct {
		embed
	}{
		embed: embed(*a),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, a.explicitFields)
	return json.Marshal(explicitMarshaler)
}

var (
	updateAgentChannelsRequestFieldIdempotencyKey = big.NewInt(1 << 0)
	updateAgentChannelsRequestFieldID             = big.NewInt(1 << 1)
	updateAgentChannelsRequestFieldChannels       = big.NewInt(1 << 2)
)

type UpdateAgentChannelsRequest struct {
	// Idempotency key cho mutation (tránh double-submit).
	IdempotencyKey *string          `json:"-" url:"-"`
	ID             string           `json:"-" url:"-"`
	Channels       []*ChannelConfig `json:"channels,omitempty" url:"-"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
}

func (u *UpdateAgentChannelsRequest) require(field *big.Int) {
	if u.explicitFields == nil {
		u.explicitFields = big.NewInt(0)
	}
	u.explicitFields.Or(u.explicitFields, field)
}

// SetIdempotencyKey sets the IdempotencyKey field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (u *UpdateAgentChannelsRequest) SetIdempotencyKey(idempotencyKey *string) {
	u.IdempotencyKey = idempotencyKey
	u.require(updateAgentChannelsRequestFieldIdempotencyKey)
}

// SetID sets the ID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (u *UpdateAgentChannelsRequest) SetID(id string) {
	u.ID = id
	u.require(updateAgentChannelsRequestFieldID)
}

// SetChannels sets the Channels field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (u *UpdateAgentChannelsRequest) SetChannels(channels []*ChannelConfig) {
	u.Channels = channels
	u.require(updateAgentChannelsRequestFieldChannels)
}

func (u *UpdateAgentChannelsRequest) UnmarshalJSON(data []byte) error {
	type unmarshaler UpdateAgentChannelsRequest
	var body unmarshaler
	if err := json.Unmarshal(data, &body); err != nil {
		return err
	}
	*u = UpdateAgentChannelsRequest(body)
	return nil
}

func (u *UpdateAgentChannelsRequest) MarshalJSON() ([]byte, error) {
	type embed UpdateAgentChannelsRequest
	var marshaler = struct {
		embed
	}{
		embed: embed(*u),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, u.explicitFields)
	return json.Marshal(explicitMarshaler)
}
