// Code generated by Fern. DO NOT EDIT.

package api

import (
	json "encoding/json"
	fmt "fmt"
	internal "github.com/DTG-Corp/dtg-sdk-go/internal"
	big "math/big"
	time "time"
)

var (
	aPIKeyCreateRequestFieldIdempotencyKey = big.NewInt(1 << 0)
	aPIKeyCreateRequestFieldName           = big.NewInt(1 << 1)
)

type APIKeyCreateRequest struct {
	// Idempotency key cho mutation (tránh double-submit).
	IdempotencyKey *string `json:"-" url:"-"`
	Name           string  `json:"name" url:"-"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
}

func (a *APIKeyCreateRequest) require(field *big.Int) {
	if a.explicitFields == nil {
		a.explicitFields = big.NewInt(0)
	}
	a.explicitFields.Or(a.explicitFields, field)
}

// SetIdempotencyKey sets the IdempotencyKey field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (a *APIKeyCreateRequest) SetIdempotencyKey(idempotencyKey *string) {
	a.IdempotencyKey = idempotencyKey
	a.require(aPIKeyCreateRequestFieldIdempotencyKey)
}

// SetName sets the Name field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (a *APIKeyCreateRequest) SetName(name string) {
	a.Name = name
	a.require(aPIKeyCreateRequestFieldName)
}

func (a *APIKeyCreateRequest) UnmarshalJSON(data []byte) error {
	type unmarshaler APIKeyCreateRequest
	var body unmarshaler
	if err := json.Unmarshal(data, &body); err != nil {
		return err
	}
	*a = APIKeyCreateRequest(body)
	return nil
}

func (a *APIKeyCreateRequest) MarshalJSON() ([]byte, error) {
	type embed APIKeyCreateRequest
	var marshaler = struct {
		embed
	}{
		embed: embed(*a),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, a.explicitFields)
	return json.Marshal(explicitMarshaler)
}

var (
	revokeAPIKeyRequestFieldIdempotencyKey = big.NewInt(1 << 0)
	revokeAPIKeyRequestFieldID             = big.NewInt(1 << 1)
)

type RevokeAPIKeyRequest struct {
	// Idempotency key cho mutation (tránh double-submit).
	IdempotencyKey *string `json:"-" url:"-"`
	ID             string  `json:"-" url:"-"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
}

func (r *RevokeAPIKeyRequest) require(field *big.Int) {
	if r.explicitFields == nil {
		r.explicitFields = big.NewInt(0)
	}
	r.explicitFields.Or(r.explicitFields, field)
}

// SetIdempotencyKey sets the IdempotencyKey field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (r *RevokeAPIKeyRequest) SetIdempotencyKey(idempotencyKey *string) {
	r.IdempotencyKey = idempotencyKey
	r.require(revokeAPIKeyRequestFieldIdempotencyKey)
}

// SetID sets the ID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (r *RevokeAPIKeyRequest) SetID(id string) {
	r.ID = id
	r.require(revokeAPIKeyRequestFieldID)
}

var (
	aPIKeyFieldID          = big.NewInt(1 << 0)
	aPIKeyFieldName        = big.NewInt(1 << 1)
	aPIKeyFieldTokenPrefix = big.NewInt(1 << 2)
	aPIKeyFieldCreatedAt   = big.NewInt(1 << 3)
	aPIKeyFieldLastUsedAt  = big.NewInt(1 << 4)
)

type APIKey struct {
	ID          *string    `json:"id,omitempty" url:"id,omitempty"`
	Name        *string    `json:"name,omitempty" url:"name,omitempty"`
	TokenPrefix *string    `json:"token_prefix,omitempty" url:"token_prefix,omitempty"`
	CreatedAt   *time.Time `json:"created_at,omitempty" url:"created_at,omitempty"`
	LastUsedAt  *time.Time `json:"last_used_at,omitempty" url:"last_used_at,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (a *APIKey) GetID() *string {
	if a == nil {
		return nil
	}
	return a.ID
}

func (a *APIKey) GetName() *string {
	if a == nil {
		return nil
	}
	return a.Name
}

func (a *APIKey) GetTokenPrefix() *string {
	if a == nil {
		return nil
	}
	return a.TokenPrefix
}

func (a *APIKey) GetCreatedAt() *time.Time {
	if a == nil {
		return nil
	}
	return a.CreatedAt
}

func (a *APIKey) GetLastUsedAt() *time.Time {
	if a == nil {
		return nil
	}
	return a.LastUsedAt
}

func (a *APIKey) GetExtraProperties() map[string]interface{} {
	if a == nil {
		return nil
	}
	return a.extraProperties
}

func (a *APIKey) require(field *big.Int) {
	if a.explicitFields == nil {
		a.explicitFields = big.NewInt(0)
	}
	a.explicitFields.Or(a.explicitFields, field)
}

// SetID sets the ID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (a *APIKey) SetID(id *string) {
	a.ID = id
	a.require(aPIKeyFieldID)
}

// SetName sets the Name field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (a *APIKey) SetName(name *string) {
	a.Name = name
	a.require(aPIKeyFieldName)
}

// SetTokenPrefix sets the TokenPrefix field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (a *APIKey) SetTokenPrefix(tokenPrefix *string) {
	a.TokenPrefix = tokenPrefix
	a.require(aPIKeyFieldTokenPrefix)
}

// SetCreatedAt sets the CreatedAt field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (a *APIKey) SetCreatedAt(createdAt *time.Time) {
	a.CreatedAt = createdAt
	a.require(aPIKeyFieldCreatedAt)
}

// SetLastUsedAt sets the LastUsedAt field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (a *APIKey) SetLastUsedAt(lastUsedAt *time.Time) {
	a.LastUsedAt = lastUsedAt
	a.require(aPIKeyFieldLastUsedAt)
}

func (a *APIKey) UnmarshalJSON(data []byte) error {
	type embed APIKey
	var unmarshaler = struct {
		embed
		CreatedAt  *internal.DateTime `json:"created_at,omitempty"`
		LastUsedAt *internal.DateTime `json:"last_used_at,omitempty"`
	}{
		embed: embed(*a),
	}
	if err := json.Unmarshal(data, &unmarshaler); err != nil {
		return err
	}
	*a = APIKey(unmarshaler.embed)
	a.CreatedAt = unmarshaler.CreatedAt.TimePtr()
	a.LastUsedAt = unmarshaler.LastUsedAt.TimePtr()
	extraProperties, err := internal.ExtractExtraProperties(data, *a)
	if err != nil {
		return err
	}
	a.extraProperties = extraProperties
	a.rawJSON = json.RawMessage(data)
	return nil
}

func (a *APIKey) MarshalJSON() ([]byte, error) {
	type embed APIKey
	var marshaler = struct {
		embed
		CreatedAt  *internal.DateTime `json:"created_at,omitempty"`
		LastUsedAt *internal.DateTime `json:"last_used_at,omitempty"`
	}{
		embed:      embed(*a),
		CreatedAt:  internal.NewOptionalDateTime(a.CreatedAt),
		LastUsedAt: internal.NewOptionalDateTime(a.LastUsedAt),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, a.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (a *APIKey) String() string {
	if a == nil {
		return "<nil>"
	}
	if len(a.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(a.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(a); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", a)
}

var (
	aPIKeyCreateResponseFieldID     = big.NewInt(1 << 0)
	aPIKeyCreateResponseFieldName   = big.NewInt(1 << 1)
	aPIKeyCreateResponseFieldSecret = big.NewInt(1 << 2)
)

type APIKeyCreateResponse struct {
	ID     *string `json:"id,omitempty" url:"id,omitempty"`
	Name   *string `json:"name,omitempty" url:"name,omitempty"`
	Secret *string `json:"secret,omitempty" url:"secret,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (a *APIKeyCreateResponse) GetID() *string {
	if a == nil {
		return nil
	}
	return a.ID
}

func (a *APIKeyCreateResponse) GetName() *string {
	if a == nil {
		return nil
	}
	return a.Name
}

func (a *APIKeyCreateResponse) GetSecret() *string {
	if a == nil {
		return nil
	}
	return a.Secret
}

func (a *APIKeyCreateResponse) GetExtraProperties() map[string]interface{} {
	if a == nil {
		return nil
	}
	return a.extraProperties
}

func (a *APIKeyCreateResponse) require(field *big.Int) {
	if a.explicitFields == nil {
		a.explicitFields = big.NewInt(0)
	}
	a.explicitFields.Or(a.explicitFields, field)
}

// SetID sets the ID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (a *APIKeyCreateResponse) SetID(id *string) {
	a.ID = id
	a.require(aPIKeyCreateResponseFieldID)
}

// SetName sets the Name field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (a *APIKeyCreateResponse) SetName(name *string) {
	a.Name = name
	a.require(aPIKeyCreateResponseFieldName)
}

// SetSecret sets the Secret field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (a *APIKeyCreateResponse) SetSecret(secret *string) {
	a.Secret = secret
	a.require(aPIKeyCreateResponseFieldSecret)
}

func (a *APIKeyCreateResponse) UnmarshalJSON(data []byte) error {
	type unmarshaler APIKeyCreateResponse
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*a = APIKeyCreateResponse(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *a)
	if err != nil {
		return err
	}
	a.extraProperties = extraProperties
	a.rawJSON = json.RawMessage(data)
	return nil
}

func (a *APIKeyCreateResponse) MarshalJSON() ([]byte, error) {
	type embed APIKeyCreateResponse
	var marshaler = struct {
		embed
	}{
		embed: embed(*a),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, a.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (a *APIKeyCreateResponse) String() string {
	if a == nil {
		return "<nil>"
	}
	if len(a.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(a.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(a); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", a)
}

var (
	createAPIKeyResponseFieldData      = big.NewInt(1 << 0)
	createAPIKeyResponseFieldStatus    = big.NewInt(1 << 1)
	createAPIKeyResponseFieldCode      = big.NewInt(1 << 2)
	createAPIKeyResponseFieldMessage   = big.NewInt(1 << 3)
	createAPIKeyResponseFieldTraceID   = big.NewInt(1 << 4)
	createAPIKeyResponseFieldTimestamp = big.NewInt(1 << 5)
)

type CreateAPIKeyResponse struct {
	Data      *APIKeyCreateResponse `json:"data,omitempty" url:"data,omitempty"`
	Status    EnvelopeStatus        `json:"status" url:"status"`
	Code      string                `json:"code" url:"code"`
	Message   string                `json:"message" url:"message"`
	TraceID   string                `json:"trace_id" url:"trace_id"`
	Timestamp time.Time             `json:"timestamp" url:"timestamp"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (c *CreateAPIKeyResponse) GetData() *APIKeyCreateResponse {
	if c == nil {
		return nil
	}
	return c.Data
}

func (c *CreateAPIKeyResponse) GetStatus() EnvelopeStatus {
	if c == nil {
		return ""
	}
	return c.Status
}

func (c *CreateAPIKeyResponse) GetCode() string {
	if c == nil {
		return ""
	}
	return c.Code
}

func (c *CreateAPIKeyResponse) GetMessage() string {
	if c == nil {
		return ""
	}
	return c.Message
}

func (c *CreateAPIKeyResponse) GetTraceID() string {
	if c == nil {
		return ""
	}
	return c.TraceID
}

func (c *CreateAPIKeyResponse) GetTimestamp() time.Time {
	if c == nil {
		return time.Time{}
	}
	return c.Timestamp
}

func (c *CreateAPIKeyResponse) GetExtraProperties() map[string]interface{} {
	if c == nil {
		return nil
	}
	return c.extraProperties
}

func (c *CreateAPIKeyResponse) require(field *big.Int) {
	if c.explicitFields == nil {
		c.explicitFields = big.NewInt(0)
	}
	c.explicitFields.Or(c.explicitFields, field)
}

// SetData sets the Data field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CreateAPIKeyResponse) SetData(data *APIKeyCreateResponse) {
	c.Data = data
	c.require(createAPIKeyResponseFieldData)
}

// SetStatus sets the Status field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CreateAPIKeyResponse) SetStatus(status EnvelopeStatus) {
	c.Status = status
	c.require(createAPIKeyResponseFieldStatus)
}

// SetCode sets the Code field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CreateAPIKeyResponse) SetCode(code string) {
	c.Code = code
	c.require(createAPIKeyResponseFieldCode)
}

// SetMessage sets the Message field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CreateAPIKeyResponse) SetMessage(message string) {
	c.Message = message
	c.require(createAPIKeyResponseFieldMessage)
}

// SetTraceID sets the TraceID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CreateAPIKeyResponse) SetTraceID(traceID string) {
	c.TraceID = traceID
	c.require(createAPIKeyResponseFieldTraceID)
}

// SetTimestamp sets the Timestamp field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CreateAPIKeyResponse) SetTimestamp(timestamp time.Time) {
	c.Timestamp = timestamp
	c.require(createAPIKeyResponseFieldTimestamp)
}

func (c *CreateAPIKeyResponse) UnmarshalJSON(data []byte) error {
	type embed CreateAPIKeyResponse
	var unmarshaler = struct {
		embed
		Timestamp *internal.DateTime `json:"timestamp"`
	}{
		embed: embed(*c),
	}
	if err := json.Unmarshal(data, &unmarshaler); err != nil {
		return err
	}
	*c = CreateAPIKeyResponse(unmarshaler.embed)
	c.Timestamp = unmarshaler.Timestamp.Time()
	extraProperties, err := internal.ExtractExtraProperties(data, *c)
	if err != nil {
		return err
	}
	c.extraProperties = extraProperties
	c.rawJSON = json.RawMessage(data)
	return nil
}

func (c *CreateAPIKeyResponse) MarshalJSON() ([]byte, error) {
	type embed CreateAPIKeyResponse
	var marshaler = struct {
		embed
		Timestamp *internal.DateTime `json:"timestamp"`
	}{
		embed:     embed(*c),
		Timestamp: internal.NewDateTime(c.Timestamp),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, c.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (c *CreateAPIKeyResponse) String() string {
	if c == nil {
		return "<nil>"
	}
	if len(c.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(c.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(c); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", c)
}

var (
	listAPIKeysResponseFieldData      = big.NewInt(1 << 0)
	listAPIKeysResponseFieldStatus    = big.NewInt(1 << 1)
	listAPIKeysResponseFieldCode      = big.NewInt(1 << 2)
	listAPIKeysResponseFieldMessage   = big.NewInt(1 << 3)
	listAPIKeysResponseFieldTraceID   = big.NewInt(1 << 4)
	listAPIKeysResponseFieldTimestamp = big.NewInt(1 << 5)
)

type ListAPIKeysResponse struct {
	Data      []*APIKey      `json:"data,omitempty" url:"data,omitempty"`
	Status    EnvelopeStatus `json:"status" url:"status"`
	Code      string         `json:"code" url:"code"`
	Message   string         `json:"message" url:"message"`
	TraceID   string         `json:"trace_id" url:"trace_id"`
	Timestamp time.Time      `json:"timestamp" url:"timestamp"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (l *ListAPIKeysResponse) GetData() []*APIKey {
	if l == nil {
		return nil
	}
	return l.Data
}

func (l *ListAPIKeysResponse) GetStatus() EnvelopeStatus {
	if l == nil {
		return ""
	}
	return l.Status
}

func (l *ListAPIKeysResponse) GetCode() string {
	if l == nil {
		return ""
	}
	return l.Code
}

func (l *ListAPIKeysResponse) GetMessage() string {
	if l == nil {
		return ""
	}
	return l.Message
}

func (l *ListAPIKeysResponse) GetTraceID() string {
	if l == nil {
		return ""
	}
	return l.TraceID
}

func (l *ListAPIKeysResponse) GetTimestamp() time.Time {
	if l == nil {
		return time.Time{}
	}
	return l.Timestamp
}

func (l *ListAPIKeysResponse) GetExtraProperties() map[string]interface{} {
	if l == nil {
		return nil
	}
	return l.extraProperties
}

func (l *ListAPIKeysResponse) require(field *big.Int) {
	if l.explicitFields == nil {
		l.explicitFields = big.NewInt(0)
	}
	l.explicitFields.Or(l.explicitFields, field)
}

// SetData sets the Data field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *ListAPIKeysResponse) SetData(data []*APIKey) {
	l.Data = data
	l.require(listAPIKeysResponseFieldData)
}

// SetStatus sets the Status field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *ListAPIKeysResponse) SetStatus(status EnvelopeStatus) {
	l.Status = status
	l.require(listAPIKeysResponseFieldStatus)
}

// SetCode sets the Code field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *ListAPIKeysResponse) SetCode(code string) {
	l.Code = code
	l.require(listAPIKeysResponseFieldCode)
}

// SetMessage sets the Message field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *ListAPIKeysResponse) SetMessage(message string) {
	l.Message = message
	l.require(listAPIKeysResponseFieldMessage)
}

// SetTraceID sets the TraceID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *ListAPIKeysResponse) SetTraceID(traceID string) {
	l.TraceID = traceID
	l.require(listAPIKeysResponseFieldTraceID)
}

// SetTimestamp sets the Timestamp field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *ListAPIKeysResponse) SetTimestamp(timestamp time.Time) {
	l.Timestamp = timestamp
	l.require(listAPIKeysResponseFieldTimestamp)
}

func (l *ListAPIKeysResponse) UnmarshalJSON(data []byte) error {
	type embed ListAPIKeysResponse
	var unmarshaler = struct {
		embed
		Timestamp *internal.DateTime `json:"timestamp"`
	}{
		embed: embed(*l),
	}
	if err := json.Unmarshal(data, &unmarshaler); err != nil {
		return err
	}
	*l = ListAPIKeysResponse(unmarshaler.embed)
	l.Timestamp = unmarshaler.Timestamp.Time()
	extraProperties, err := internal.ExtractExtraProperties(data, *l)
	if err != nil {
		return err
	}
	l.extraProperties = extraProperties
	l.rawJSON = json.RawMessage(data)
	return nil
}

func (l *ListAPIKeysResponse) MarshalJSON() ([]byte, error) {
	type embed ListAPIKeysResponse
	var marshaler = struct {
		embed
		Timestamp *internal.DateTime `json:"timestamp"`
	}{
		embed:     embed(*l),
		Timestamp: internal.NewDateTime(l.Timestamp),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, l.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (l *ListAPIKeysResponse) String() string {
	if l == nil {
		return "<nil>"
	}
	if len(l.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(l.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(l); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", l)
}

var (
	revokeAPIKeyResponseFieldData      = big.NewInt(1 << 0)
	revokeAPIKeyResponseFieldStatus    = big.NewInt(1 << 1)
	revokeAPIKeyResponseFieldCode      = big.NewInt(1 << 2)
	revokeAPIKeyResponseFieldMessage   = big.NewInt(1 << 3)
	revokeAPIKeyResponseFieldTraceID   = big.NewInt(1 << 4)
	revokeAPIKeyResponseFieldTimestamp = big.NewInt(1 << 5)
)

type RevokeAPIKeyResponse struct {
	Data      *OkResponse    `json:"data,omitempty" url:"data,omitempty"`
	Status    EnvelopeStatus `json:"status" url:"status"`
	Code      string         `json:"code" url:"code"`
	Message   string         `json:"message" url:"message"`
	TraceID   string         `json:"trace_id" url:"trace_id"`
	Timestamp time.Time      `json:"timestamp" url:"timestamp"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (r *RevokeAPIKeyResponse) GetData() *OkResponse {
	if r == nil {
		return nil
	}
	return r.Data
}

func (r *RevokeAPIKeyResponse) GetStatus() EnvelopeStatus {
	if r == nil {
		return ""
	}
	return r.Status
}

func (r *RevokeAPIKeyResponse) GetCode() string {
	if r == nil {
		return ""
	}
	return r.Code
}

func (r *RevokeAPIKeyResponse) GetMessage() string {
	if r == nil {
		return ""
	}
	return r.Message
}

func (r *RevokeAPIKeyResponse) GetTraceID() string {
	if r == nil {
		return ""
	}
	return r.TraceID
}

func (r *RevokeAPIKeyResponse) GetTimestamp() time.Time {
	if r == nil {
		return time.Time{}
	}
	return r.Timestamp
}

func (r *RevokeAPIKeyResponse) GetExtraProperties() map[string]interface{} {
	if r == nil {
		return nil
	}
	return r.extraProperties
}

func (r *RevokeAPIKeyResponse) require(field *big.Int) {
	if r.explicitFields == nil {
		r.explicitFields = big.NewInt(0)
	}
	r.explicitFields.Or(r.explicitFields, field)
}

// SetData sets the Data field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (r *RevokeAPIKeyResponse) SetData(data *OkResponse) {
	r.Data = data
	r.require(revokeAPIKeyResponseFieldData)
}

// SetStatus sets the Status field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (r *RevokeAPIKeyResponse) SetStatus(status EnvelopeStatus) {
	r.Status = status
	r.require(revokeAPIKeyResponseFieldStatus)
}

// SetCode sets the Code field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (r *RevokeAPIKeyResponse) SetCode(code string) {
	r.Code = code
	r.require(revokeAPIKeyResponseFieldCode)
}

// SetMessage sets the Message field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (r *RevokeAPIKeyResponse) SetMessage(message string) {
	r.Message = message
	r.require(revokeAPIKeyResponseFieldMessage)
}

// SetTraceID sets the TraceID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (r *RevokeAPIKeyResponse) SetTraceID(traceID string) {
	r.TraceID = traceID
	r.require(revokeAPIKeyResponseFieldTraceID)
}

// SetTimestamp sets the Timestamp field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (r *RevokeAPIKeyResponse) SetTimestamp(timestamp time.Time) {
	r.Timestamp = timestamp
	r.require(revokeAPIKeyResponseFieldTimestamp)
}

func (r *RevokeAPIKeyResponse) UnmarshalJSON(data []byte) error {
	type embed RevokeAPIKeyResponse
	var unmarshaler = struct {
		embed
		Timestamp *internal.DateTime `json:"timestamp"`
	}{
		embed: embed(*r),
	}
	if err := json.Unmarshal(data, &unmarshaler); err != nil {
		return err
	}
	*r = RevokeAPIKeyResponse(unmarshaler.embed)
	r.Timestamp = unmarshaler.Timestamp.Time()
	extraProperties, err := internal.ExtractExtraProperties(data, *r)
	if err != nil {
		return err
	}
	r.extraProperties = extraProperties
	r.rawJSON = json.RawMessage(data)
	return nil
}

func (r *RevokeAPIKeyResponse) MarshalJSON() ([]byte, error) {
	type embed RevokeAPIKeyResponse
	var marshaler = struct {
		embed
		Timestamp *internal.DateTime `json:"timestamp"`
	}{
		embed:     embed(*r),
		Timestamp: internal.NewDateTime(r.Timestamp),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, r.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (r *RevokeAPIKeyResponse) String() string {
	if r == nil {
		return "<nil>"
	}
	if len(r.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(r.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(r); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", r)
}
