// Code generated by Fern. DO NOT EDIT.

package api

import (
	json "encoding/json"
	fmt "fmt"
	internal "github.com/DTG-Corp/dtg-agent-sdk/internal"
	big "math/big"
)

var (
	chatCompletionRequestFieldHermesSessionID = big.NewInt(1 << 0)
	chatCompletionRequestFieldHermesThreadID  = big.NewInt(1 << 1)
	chatCompletionRequestFieldModel           = big.NewInt(1 << 2)
	chatCompletionRequestFieldMessages        = big.NewInt(1 << 3)
	chatCompletionRequestFieldTemperature     = big.NewInt(1 << 4)
	chatCompletionRequestFieldStream          = big.NewInt(1 << 5)
	chatCompletionRequestFieldSessionID       = big.NewInt(1 << 6)
	chatCompletionRequestFieldThreadID        = big.NewInt(1 << 7)
)

type ChatCompletionRequest struct {
	// Session tùy chỉnh phía client.
	HermesSessionID *string `json:"-" url:"-"`
	// Thread tùy chỉnh phía client.
	HermesThreadID *string `json:"-" url:"-"`
	// ID của agent (UUID).
	Model       string         `json:"model" url:"-"`
	Messages    []*ChatMessage `json:"messages" url:"-"`
	Temperature *float64       `json:"temperature,omitempty" url:"-"`
	Stream      *bool          `json:"stream,omitempty" url:"-"`
	SessionID   *string        `json:"session_id,omitempty" url:"-"`
	ThreadID    *string        `json:"thread_id,omitempty" url:"-"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
}

func (c *ChatCompletionRequest) require(field *big.Int) {
	if c.explicitFields == nil {
		c.explicitFields = big.NewInt(0)
	}
	c.explicitFields.Or(c.explicitFields, field)
}

// SetHermesSessionID sets the HermesSessionID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *ChatCompletionRequest) SetHermesSessionID(hermesSessionID *string) {
	c.HermesSessionID = hermesSessionID
	c.require(chatCompletionRequestFieldHermesSessionID)
}

// SetHermesThreadID sets the HermesThreadID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *ChatCompletionRequest) SetHermesThreadID(hermesThreadID *string) {
	c.HermesThreadID = hermesThreadID
	c.require(chatCompletionRequestFieldHermesThreadID)
}

// SetModel sets the Model field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *ChatCompletionRequest) SetModel(model string) {
	c.Model = model
	c.require(chatCompletionRequestFieldModel)
}

// SetMessages sets the Messages field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *ChatCompletionRequest) SetMessages(messages []*ChatMessage) {
	c.Messages = messages
	c.require(chatCompletionRequestFieldMessages)
}

// SetTemperature sets the Temperature field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *ChatCompletionRequest) SetTemperature(temperature *float64) {
	c.Temperature = temperature
	c.require(chatCompletionRequestFieldTemperature)
}

// SetStream sets the Stream field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *ChatCompletionRequest) SetStream(stream *bool) {
	c.Stream = stream
	c.require(chatCompletionRequestFieldStream)
}

// SetSessionID sets the SessionID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *ChatCompletionRequest) SetSessionID(sessionID *string) {
	c.SessionID = sessionID
	c.require(chatCompletionRequestFieldSessionID)
}

// SetThreadID sets the ThreadID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *ChatCompletionRequest) SetThreadID(threadID *string) {
	c.ThreadID = threadID
	c.require(chatCompletionRequestFieldThreadID)
}

func (c *ChatCompletionRequest) UnmarshalJSON(data []byte) error {
	type unmarshaler ChatCompletionRequest
	var body unmarshaler
	if err := json.Unmarshal(data, &body); err != nil {
		return err
	}
	*c = ChatCompletionRequest(body)
	return nil
}

func (c *ChatCompletionRequest) MarshalJSON() ([]byte, error) {
	type embed ChatCompletionRequest
	var marshaler = struct {
		embed
	}{
		embed: embed(*c),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, c.explicitFields)
	return json.Marshal(explicitMarshaler)
}

var (
	chatCompletionFieldID      = big.NewInt(1 << 0)
	chatCompletionFieldObject  = big.NewInt(1 << 1)
	chatCompletionFieldCreated = big.NewInt(1 << 2)
	chatCompletionFieldModel   = big.NewInt(1 << 3)
	chatCompletionFieldChoices = big.NewInt(1 << 4)
	chatCompletionFieldUsage   = big.NewInt(1 << 5)
)

type ChatCompletion struct {
	ID      *string              `json:"id,omitempty" url:"id,omitempty"`
	Object  *string              `json:"object,omitempty" url:"object,omitempty"`
	Created *int                 `json:"created,omitempty" url:"created,omitempty"`
	Model   *string              `json:"model,omitempty" url:"model,omitempty"`
	Choices []map[string]any     `json:"choices,omitempty" url:"choices,omitempty"`
	Usage   *ChatCompletionUsage `json:"usage,omitempty" url:"usage,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (c *ChatCompletion) GetID() *string {
	if c == nil {
		return nil
	}
	return c.ID
}

func (c *ChatCompletion) GetObject() *string {
	if c == nil {
		return nil
	}
	return c.Object
}

func (c *ChatCompletion) GetCreated() *int {
	if c == nil {
		return nil
	}
	return c.Created
}

func (c *ChatCompletion) GetModel() *string {
	if c == nil {
		return nil
	}
	return c.Model
}

func (c *ChatCompletion) GetChoices() []map[string]any {
	if c == nil {
		return nil
	}
	return c.Choices
}

func (c *ChatCompletion) GetUsage() *ChatCompletionUsage {
	if c == nil {
		return nil
	}
	return c.Usage
}

func (c *ChatCompletion) GetExtraProperties() map[string]interface{} {
	if c == nil {
		return nil
	}
	return c.extraProperties
}

func (c *ChatCompletion) require(field *big.Int) {
	if c.explicitFields == nil {
		c.explicitFields = big.NewInt(0)
	}
	c.explicitFields.Or(c.explicitFields, field)
}

// SetID sets the ID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *ChatCompletion) SetID(id *string) {
	c.ID = id
	c.require(chatCompletionFieldID)
}

// SetObject sets the Object field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *ChatCompletion) SetObject(object *string) {
	c.Object = object
	c.require(chatCompletionFieldObject)
}

// SetCreated sets the Created field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *ChatCompletion) SetCreated(created *int) {
	c.Created = created
	c.require(chatCompletionFieldCreated)
}

// SetModel sets the Model field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *ChatCompletion) SetModel(model *string) {
	c.Model = model
	c.require(chatCompletionFieldModel)
}

// SetChoices sets the Choices field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *ChatCompletion) SetChoices(choices []map[string]any) {
	c.Choices = choices
	c.require(chatCompletionFieldChoices)
}

// SetUsage sets the Usage field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *ChatCompletion) SetUsage(usage *ChatCompletionUsage) {
	c.Usage = usage
	c.require(chatCompletionFieldUsage)
}

func (c *ChatCompletion) UnmarshalJSON(data []byte) error {
	type unmarshaler ChatCompletion
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*c = ChatCompletion(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *c)
	if err != nil {
		return err
	}
	c.extraProperties = extraProperties
	c.rawJSON = json.RawMessage(data)
	return nil
}

func (c *ChatCompletion) MarshalJSON() ([]byte, error) {
	type embed ChatCompletion
	var marshaler = struct {
		embed
	}{
		embed: embed(*c),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, c.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (c *ChatCompletion) String() string {
	if c == nil {
		return "<nil>"
	}
	if len(c.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(c.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(c); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", c)
}

var (
	chatCompletionUsageFieldPromptTokens     = big.NewInt(1 << 0)
	chatCompletionUsageFieldCompletionTokens = big.NewInt(1 << 1)
	chatCompletionUsageFieldTotalTokens      = big.NewInt(1 << 2)
)

type ChatCompletionUsage struct {
	PromptTokens     *int `json:"prompt_tokens,omitempty" url:"prompt_tokens,omitempty"`
	CompletionTokens *int `json:"completion_tokens,omitempty" url:"completion_tokens,omitempty"`
	TotalTokens      *int `json:"total_tokens,omitempty" url:"total_tokens,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (c *ChatCompletionUsage) GetPromptTokens() *int {
	if c == nil {
		return nil
	}
	return c.PromptTokens
}

func (c *ChatCompletionUsage) GetCompletionTokens() *int {
	if c == nil {
		return nil
	}
	return c.CompletionTokens
}

func (c *ChatCompletionUsage) GetTotalTokens() *int {
	if c == nil {
		return nil
	}
	return c.TotalTokens
}

func (c *ChatCompletionUsage) GetExtraProperties() map[string]interface{} {
	if c == nil {
		return nil
	}
	return c.extraProperties
}

func (c *ChatCompletionUsage) require(field *big.Int) {
	if c.explicitFields == nil {
		c.explicitFields = big.NewInt(0)
	}
	c.explicitFields.Or(c.explicitFields, field)
}

// SetPromptTokens sets the PromptTokens field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *ChatCompletionUsage) SetPromptTokens(promptTokens *int) {
	c.PromptTokens = promptTokens
	c.require(chatCompletionUsageFieldPromptTokens)
}

// SetCompletionTokens sets the CompletionTokens field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *ChatCompletionUsage) SetCompletionTokens(completionTokens *int) {
	c.CompletionTokens = completionTokens
	c.require(chatCompletionUsageFieldCompletionTokens)
}

// SetTotalTokens sets the TotalTokens field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *ChatCompletionUsage) SetTotalTokens(totalTokens *int) {
	c.TotalTokens = totalTokens
	c.require(chatCompletionUsageFieldTotalTokens)
}

func (c *ChatCompletionUsage) UnmarshalJSON(data []byte) error {
	type unmarshaler ChatCompletionUsage
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*c = ChatCompletionUsage(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *c)
	if err != nil {
		return err
	}
	c.extraProperties = extraProperties
	c.rawJSON = json.RawMessage(data)
	return nil
}

func (c *ChatCompletionUsage) MarshalJSON() ([]byte, error) {
	type embed ChatCompletionUsage
	var marshaler = struct {
		embed
	}{
		embed: embed(*c),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, c.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (c *ChatCompletionUsage) String() string {
	if c == nil {
		return "<nil>"
	}
	if len(c.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(c.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(c); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", c)
}

var (
	chatMessageFieldRole    = big.NewInt(1 << 0)
	chatMessageFieldContent = big.NewInt(1 << 1)
)

type ChatMessage struct {
	Role    ChatMessageRole `json:"role" url:"role"`
	Content string          `json:"content" url:"content"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (c *ChatMessage) GetRole() ChatMessageRole {
	if c == nil {
		return ""
	}
	return c.Role
}

func (c *ChatMessage) GetContent() string {
	if c == nil {
		return ""
	}
	return c.Content
}

func (c *ChatMessage) GetExtraProperties() map[string]interface{} {
	if c == nil {
		return nil
	}
	return c.extraProperties
}

func (c *ChatMessage) require(field *big.Int) {
	if c.explicitFields == nil {
		c.explicitFields = big.NewInt(0)
	}
	c.explicitFields.Or(c.explicitFields, field)
}

// SetRole sets the Role field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *ChatMessage) SetRole(role ChatMessageRole) {
	c.Role = role
	c.require(chatMessageFieldRole)
}

// SetContent sets the Content field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *ChatMessage) SetContent(content string) {
	c.Content = content
	c.require(chatMessageFieldContent)
}

func (c *ChatMessage) UnmarshalJSON(data []byte) error {
	type unmarshaler ChatMessage
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*c = ChatMessage(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *c)
	if err != nil {
		return err
	}
	c.extraProperties = extraProperties
	c.rawJSON = json.RawMessage(data)
	return nil
}

func (c *ChatMessage) MarshalJSON() ([]byte, error) {
	type embed ChatMessage
	var marshaler = struct {
		embed
	}{
		embed: embed(*c),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, c.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (c *ChatMessage) String() string {
	if c == nil {
		return "<nil>"
	}
	if len(c.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(c.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(c); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", c)
}

type ChatMessageRole string

const (
	ChatMessageRoleSystem    ChatMessageRole = "system"
	ChatMessageRoleUser      ChatMessageRole = "user"
	ChatMessageRoleAssistant ChatMessageRole = "assistant"
	ChatMessageRoleTool      ChatMessageRole = "tool"
)

func NewChatMessageRoleFromString(s string) (ChatMessageRole, error) {
	switch s {
	case "system":
		return ChatMessageRoleSystem, nil
	case "user":
		return ChatMessageRoleUser, nil
	case "assistant":
		return ChatMessageRoleAssistant, nil
	case "tool":
		return ChatMessageRoleTool, nil
	}
	var t ChatMessageRole
	return "", fmt.Errorf("%s is not a valid %T", s, t)
}

func (c ChatMessageRole) Ptr() *ChatMessageRole {
	return &c
}
