// Code generated by Fern. DO NOT EDIT.

package api

import (
	json "encoding/json"
	fmt "fmt"
	internal "github.com/DTG-Corp/dtg-sdk-go/internal"
	big "math/big"
	time "time"
)

var (
	knowledgeCreateRequestFieldIdempotencyKey = big.NewInt(1 << 0)
	knowledgeCreateRequestFieldTitle          = big.NewInt(1 << 1)
	knowledgeCreateRequestFieldContent        = big.NewInt(1 << 2)
	knowledgeCreateRequestFieldContentType    = big.NewInt(1 << 3)
	knowledgeCreateRequestFieldTags           = big.NewInt(1 << 4)
)

type KnowledgeCreateRequest struct {
	// Idempotency key cho mutation (tránh double-submit).
	IdempotencyKey *string `json:"-" url:"-"`
	Title          string  `json:"title" url:"-"`
	// Tối đa 4 MiB
	Content     string                             `json:"content" url:"-"`
	ContentType *KnowledgeCreateRequestContentType `json:"content_type,omitempty" url:"-"`
	Tags        []string                           `json:"tags,omitempty" url:"-"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
}

func (k *KnowledgeCreateRequest) require(field *big.Int) {
	if k.explicitFields == nil {
		k.explicitFields = big.NewInt(0)
	}
	k.explicitFields.Or(k.explicitFields, field)
}

// SetIdempotencyKey sets the IdempotencyKey field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (k *KnowledgeCreateRequest) SetIdempotencyKey(idempotencyKey *string) {
	k.IdempotencyKey = idempotencyKey
	k.require(knowledgeCreateRequestFieldIdempotencyKey)
}

// SetTitle sets the Title field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (k *KnowledgeCreateRequest) SetTitle(title string) {
	k.Title = title
	k.require(knowledgeCreateRequestFieldTitle)
}

// SetContent sets the Content field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (k *KnowledgeCreateRequest) SetContent(content string) {
	k.Content = content
	k.require(knowledgeCreateRequestFieldContent)
}

// SetContentType sets the ContentType field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (k *KnowledgeCreateRequest) SetContentType(contentType *KnowledgeCreateRequestContentType) {
	k.ContentType = contentType
	k.require(knowledgeCreateRequestFieldContentType)
}

// SetTags sets the Tags field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (k *KnowledgeCreateRequest) SetTags(tags []string) {
	k.Tags = tags
	k.require(knowledgeCreateRequestFieldTags)
}

func (k *KnowledgeCreateRequest) UnmarshalJSON(data []byte) error {
	type unmarshaler KnowledgeCreateRequest
	var body unmarshaler
	if err := json.Unmarshal(data, &body); err != nil {
		return err
	}
	*k = KnowledgeCreateRequest(body)
	return nil
}

func (k *KnowledgeCreateRequest) MarshalJSON() ([]byte, error) {
	type embed KnowledgeCreateRequest
	var marshaler = struct {
		embed
	}{
		embed: embed(*k),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, k.explicitFields)
	return json.Marshal(explicitMarshaler)
}

var (
	deleteKnowledgeRequestFieldIdempotencyKey = big.NewInt(1 << 0)
	deleteKnowledgeRequestFieldID             = big.NewInt(1 << 1)
)

type DeleteKnowledgeRequest struct {
	// Idempotency key cho mutation (tránh double-submit).
	IdempotencyKey *string `json:"-" url:"-"`
	ID             string  `json:"-" url:"-"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
}

func (d *DeleteKnowledgeRequest) require(field *big.Int) {
	if d.explicitFields == nil {
		d.explicitFields = big.NewInt(0)
	}
	d.explicitFields.Or(d.explicitFields, field)
}

// SetIdempotencyKey sets the IdempotencyKey field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (d *DeleteKnowledgeRequest) SetIdempotencyKey(idempotencyKey *string) {
	d.IdempotencyKey = idempotencyKey
	d.require(deleteKnowledgeRequestFieldIdempotencyKey)
}

// SetID sets the ID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (d *DeleteKnowledgeRequest) SetID(id string) {
	d.ID = id
	d.require(deleteKnowledgeRequestFieldID)
}

var (
	getKnowledgeRequestFieldID = big.NewInt(1 << 0)
)

type GetKnowledgeRequest struct {
	ID string `json:"-" url:"-"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
}

func (g *GetKnowledgeRequest) require(field *big.Int) {
	if g.explicitFields == nil {
		g.explicitFields = big.NewInt(0)
	}
	g.explicitFields.Or(g.explicitFields, field)
}

// SetID sets the ID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GetKnowledgeRequest) SetID(id string) {
	g.ID = id
	g.require(getKnowledgeRequestFieldID)
}

var (
	knowledgeFieldID          = big.NewInt(1 << 0)
	knowledgeFieldTitle       = big.NewInt(1 << 1)
	knowledgeFieldContentType = big.NewInt(1 << 2)
	knowledgeFieldTags        = big.NewInt(1 << 3)
	knowledgeFieldCreatedAt   = big.NewInt(1 << 4)
	knowledgeFieldUpdatedAt   = big.NewInt(1 << 5)
)

type Knowledge struct {
	ID          *string               `json:"id,omitempty" url:"id,omitempty"`
	Title       *string               `json:"title,omitempty" url:"title,omitempty"`
	ContentType *KnowledgeContentType `json:"content_type,omitempty" url:"content_type,omitempty"`
	Tags        []string              `json:"tags,omitempty" url:"tags,omitempty"`
	CreatedAt   *time.Time            `json:"created_at,omitempty" url:"created_at,omitempty"`
	UpdatedAt   *time.Time            `json:"updated_at,omitempty" url:"updated_at,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (k *Knowledge) GetID() *string {
	if k == nil {
		return nil
	}
	return k.ID
}

func (k *Knowledge) GetTitle() *string {
	if k == nil {
		return nil
	}
	return k.Title
}

func (k *Knowledge) GetContentType() *KnowledgeContentType {
	if k == nil {
		return nil
	}
	return k.ContentType
}

func (k *Knowledge) GetTags() []string {
	if k == nil {
		return nil
	}
	return k.Tags
}

func (k *Knowledge) GetCreatedAt() *time.Time {
	if k == nil {
		return nil
	}
	return k.CreatedAt
}

func (k *Knowledge) GetUpdatedAt() *time.Time {
	if k == nil {
		return nil
	}
	return k.UpdatedAt
}

func (k *Knowledge) GetExtraProperties() map[string]interface{} {
	if k == nil {
		return nil
	}
	return k.extraProperties
}

func (k *Knowledge) require(field *big.Int) {
	if k.explicitFields == nil {
		k.explicitFields = big.NewInt(0)
	}
	k.explicitFields.Or(k.explicitFields, field)
}

// SetID sets the ID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (k *Knowledge) SetID(id *string) {
	k.ID = id
	k.require(knowledgeFieldID)
}

// SetTitle sets the Title field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (k *Knowledge) SetTitle(title *string) {
	k.Title = title
	k.require(knowledgeFieldTitle)
}

// SetContentType sets the ContentType field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (k *Knowledge) SetContentType(contentType *KnowledgeContentType) {
	k.ContentType = contentType
	k.require(knowledgeFieldContentType)
}

// SetTags sets the Tags field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (k *Knowledge) SetTags(tags []string) {
	k.Tags = tags
	k.require(knowledgeFieldTags)
}

// SetCreatedAt sets the CreatedAt field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (k *Knowledge) SetCreatedAt(createdAt *time.Time) {
	k.CreatedAt = createdAt
	k.require(knowledgeFieldCreatedAt)
}

// SetUpdatedAt sets the UpdatedAt field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (k *Knowledge) SetUpdatedAt(updatedAt *time.Time) {
	k.UpdatedAt = updatedAt
	k.require(knowledgeFieldUpdatedAt)
}

func (k *Knowledge) UnmarshalJSON(data []byte) error {
	type embed Knowledge
	var unmarshaler = struct {
		embed
		CreatedAt *internal.DateTime `json:"created_at,omitempty"`
		UpdatedAt *internal.DateTime `json:"updated_at,omitempty"`
	}{
		embed: embed(*k),
	}
	if err := json.Unmarshal(data, &unmarshaler); err != nil {
		return err
	}
	*k = Knowledge(unmarshaler.embed)
	k.CreatedAt = unmarshaler.CreatedAt.TimePtr()
	k.UpdatedAt = unmarshaler.UpdatedAt.TimePtr()
	extraProperties, err := internal.ExtractExtraProperties(data, *k)
	if err != nil {
		return err
	}
	k.extraProperties = extraProperties
	k.rawJSON = json.RawMessage(data)
	return nil
}

func (k *Knowledge) MarshalJSON() ([]byte, error) {
	type embed Knowledge
	var marshaler = struct {
		embed
		CreatedAt *internal.DateTime `json:"created_at,omitempty"`
		UpdatedAt *internal.DateTime `json:"updated_at,omitempty"`
	}{
		embed:     embed(*k),
		CreatedAt: internal.NewOptionalDateTime(k.CreatedAt),
		UpdatedAt: internal.NewOptionalDateTime(k.UpdatedAt),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, k.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (k *Knowledge) String() string {
	if k == nil {
		return "<nil>"
	}
	if len(k.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(k.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(k); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", k)
}

type KnowledgeContentType string

const (
	KnowledgeContentTypeText     KnowledgeContentType = "text"
	KnowledgeContentTypeMarkdown KnowledgeContentType = "markdown"
	KnowledgeContentTypeURL      KnowledgeContentType = "url"
	KnowledgeContentTypeFile     KnowledgeContentType = "file"
)

func NewKnowledgeContentTypeFromString(s string) (KnowledgeContentType, error) {
	switch s {
	case "text":
		return KnowledgeContentTypeText, nil
	case "markdown":
		return KnowledgeContentTypeMarkdown, nil
	case "url":
		return KnowledgeContentTypeURL, nil
	case "file":
		return KnowledgeContentTypeFile, nil
	}
	var t KnowledgeContentType
	return "", fmt.Errorf("%s is not a valid %T", s, t)
}

func (k KnowledgeContentType) Ptr() *KnowledgeContentType {
	return &k
}

var (
	knowledgeDetailFieldID          = big.NewInt(1 << 0)
	knowledgeDetailFieldTitle       = big.NewInt(1 << 1)
	knowledgeDetailFieldContentType = big.NewInt(1 << 2)
	knowledgeDetailFieldTags        = big.NewInt(1 << 3)
	knowledgeDetailFieldCreatedAt   = big.NewInt(1 << 4)
	knowledgeDetailFieldUpdatedAt   = big.NewInt(1 << 5)
	knowledgeDetailFieldContent     = big.NewInt(1 << 6)
)

type KnowledgeDetail struct {
	ID          *string               `json:"id,omitempty" url:"id,omitempty"`
	Title       *string               `json:"title,omitempty" url:"title,omitempty"`
	ContentType *KnowledgeContentType `json:"content_type,omitempty" url:"content_type,omitempty"`
	Tags        []string              `json:"tags,omitempty" url:"tags,omitempty"`
	CreatedAt   *time.Time            `json:"created_at,omitempty" url:"created_at,omitempty"`
	UpdatedAt   *time.Time            `json:"updated_at,omitempty" url:"updated_at,omitempty"`
	Content     *string               `json:"content,omitempty" url:"content,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (k *KnowledgeDetail) GetID() *string {
	if k == nil {
		return nil
	}
	return k.ID
}

func (k *KnowledgeDetail) GetTitle() *string {
	if k == nil {
		return nil
	}
	return k.Title
}

func (k *KnowledgeDetail) GetContentType() *KnowledgeContentType {
	if k == nil {
		return nil
	}
	return k.ContentType
}

func (k *KnowledgeDetail) GetTags() []string {
	if k == nil {
		return nil
	}
	return k.Tags
}

func (k *KnowledgeDetail) GetCreatedAt() *time.Time {
	if k == nil {
		return nil
	}
	return k.CreatedAt
}

func (k *KnowledgeDetail) GetUpdatedAt() *time.Time {
	if k == nil {
		return nil
	}
	return k.UpdatedAt
}

func (k *KnowledgeDetail) GetContent() *string {
	if k == nil {
		return nil
	}
	return k.Content
}

func (k *KnowledgeDetail) GetExtraProperties() map[string]interface{} {
	if k == nil {
		return nil
	}
	return k.extraProperties
}

func (k *KnowledgeDetail) require(field *big.Int) {
	if k.explicitFields == nil {
		k.explicitFields = big.NewInt(0)
	}
	k.explicitFields.Or(k.explicitFields, field)
}

// SetID sets the ID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (k *KnowledgeDetail) SetID(id *string) {
	k.ID = id
	k.require(knowledgeDetailFieldID)
}

// SetTitle sets the Title field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (k *KnowledgeDetail) SetTitle(title *string) {
	k.Title = title
	k.require(knowledgeDetailFieldTitle)
}

// SetContentType sets the ContentType field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (k *KnowledgeDetail) SetContentType(contentType *KnowledgeContentType) {
	k.ContentType = contentType
	k.require(knowledgeDetailFieldContentType)
}

// SetTags sets the Tags field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (k *KnowledgeDetail) SetTags(tags []string) {
	k.Tags = tags
	k.require(knowledgeDetailFieldTags)
}

// SetCreatedAt sets the CreatedAt field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (k *KnowledgeDetail) SetCreatedAt(createdAt *time.Time) {
	k.CreatedAt = createdAt
	k.require(knowledgeDetailFieldCreatedAt)
}

// SetUpdatedAt sets the UpdatedAt field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (k *KnowledgeDetail) SetUpdatedAt(updatedAt *time.Time) {
	k.UpdatedAt = updatedAt
	k.require(knowledgeDetailFieldUpdatedAt)
}

// SetContent sets the Content field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (k *KnowledgeDetail) SetContent(content *string) {
	k.Content = content
	k.require(knowledgeDetailFieldContent)
}

func (k *KnowledgeDetail) UnmarshalJSON(data []byte) error {
	type embed KnowledgeDetail
	var unmarshaler = struct {
		embed
		CreatedAt *internal.DateTime `json:"created_at,omitempty"`
		UpdatedAt *internal.DateTime `json:"updated_at,omitempty"`
	}{
		embed: embed(*k),
	}
	if err := json.Unmarshal(data, &unmarshaler); err != nil {
		return err
	}
	*k = KnowledgeDetail(unmarshaler.embed)
	k.CreatedAt = unmarshaler.CreatedAt.TimePtr()
	k.UpdatedAt = unmarshaler.UpdatedAt.TimePtr()
	extraProperties, err := internal.ExtractExtraProperties(data, *k)
	if err != nil {
		return err
	}
	k.extraProperties = extraProperties
	k.rawJSON = json.RawMessage(data)
	return nil
}

func (k *KnowledgeDetail) MarshalJSON() ([]byte, error) {
	type embed KnowledgeDetail
	var marshaler = struct {
		embed
		CreatedAt *internal.DateTime `json:"created_at,omitempty"`
		UpdatedAt *internal.DateTime `json:"updated_at,omitempty"`
	}{
		embed:     embed(*k),
		CreatedAt: internal.NewOptionalDateTime(k.CreatedAt),
		UpdatedAt: internal.NewOptionalDateTime(k.UpdatedAt),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, k.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (k *KnowledgeDetail) String() string {
	if k == nil {
		return "<nil>"
	}
	if len(k.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(k.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(k); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", k)
}

var (
	createKnowledgeResponseFieldData      = big.NewInt(1 << 0)
	createKnowledgeResponseFieldStatus    = big.NewInt(1 << 1)
	createKnowledgeResponseFieldCode      = big.NewInt(1 << 2)
	createKnowledgeResponseFieldMessage   = big.NewInt(1 << 3)
	createKnowledgeResponseFieldTraceID   = big.NewInt(1 << 4)
	createKnowledgeResponseFieldTimestamp = big.NewInt(1 << 5)
)

type CreateKnowledgeResponse struct {
	Data      *Knowledge     `json:"data,omitempty" url:"data,omitempty"`
	Status    EnvelopeStatus `json:"status" url:"status"`
	Code      string         `json:"code" url:"code"`
	Message   string         `json:"message" url:"message"`
	TraceID   string         `json:"trace_id" url:"trace_id"`
	Timestamp time.Time      `json:"timestamp" url:"timestamp"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (c *CreateKnowledgeResponse) GetData() *Knowledge {
	if c == nil {
		return nil
	}
	return c.Data
}

func (c *CreateKnowledgeResponse) GetStatus() EnvelopeStatus {
	if c == nil {
		return ""
	}
	return c.Status
}

func (c *CreateKnowledgeResponse) GetCode() string {
	if c == nil {
		return ""
	}
	return c.Code
}

func (c *CreateKnowledgeResponse) GetMessage() string {
	if c == nil {
		return ""
	}
	return c.Message
}

func (c *CreateKnowledgeResponse) GetTraceID() string {
	if c == nil {
		return ""
	}
	return c.TraceID
}

func (c *CreateKnowledgeResponse) GetTimestamp() time.Time {
	if c == nil {
		return time.Time{}
	}
	return c.Timestamp
}

func (c *CreateKnowledgeResponse) GetExtraProperties() map[string]interface{} {
	if c == nil {
		return nil
	}
	return c.extraProperties
}

func (c *CreateKnowledgeResponse) require(field *big.Int) {
	if c.explicitFields == nil {
		c.explicitFields = big.NewInt(0)
	}
	c.explicitFields.Or(c.explicitFields, field)
}

// SetData sets the Data field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CreateKnowledgeResponse) SetData(data *Knowledge) {
	c.Data = data
	c.require(createKnowledgeResponseFieldData)
}

// SetStatus sets the Status field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CreateKnowledgeResponse) SetStatus(status EnvelopeStatus) {
	c.Status = status
	c.require(createKnowledgeResponseFieldStatus)
}

// SetCode sets the Code field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CreateKnowledgeResponse) SetCode(code string) {
	c.Code = code
	c.require(createKnowledgeResponseFieldCode)
}

// SetMessage sets the Message field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CreateKnowledgeResponse) SetMessage(message string) {
	c.Message = message
	c.require(createKnowledgeResponseFieldMessage)
}

// SetTraceID sets the TraceID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CreateKnowledgeResponse) SetTraceID(traceID string) {
	c.TraceID = traceID
	c.require(createKnowledgeResponseFieldTraceID)
}

// SetTimestamp sets the Timestamp field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CreateKnowledgeResponse) SetTimestamp(timestamp time.Time) {
	c.Timestamp = timestamp
	c.require(createKnowledgeResponseFieldTimestamp)
}

func (c *CreateKnowledgeResponse) UnmarshalJSON(data []byte) error {
	type embed CreateKnowledgeResponse
	var unmarshaler = struct {
		embed
		Timestamp *internal.DateTime `json:"timestamp"`
	}{
		embed: embed(*c),
	}
	if err := json.Unmarshal(data, &unmarshaler); err != nil {
		return err
	}
	*c = CreateKnowledgeResponse(unmarshaler.embed)
	c.Timestamp = unmarshaler.Timestamp.Time()
	extraProperties, err := internal.ExtractExtraProperties(data, *c)
	if err != nil {
		return err
	}
	c.extraProperties = extraProperties
	c.rawJSON = json.RawMessage(data)
	return nil
}

func (c *CreateKnowledgeResponse) MarshalJSON() ([]byte, error) {
	type embed CreateKnowledgeResponse
	var marshaler = struct {
		embed
		Timestamp *internal.DateTime `json:"timestamp"`
	}{
		embed:     embed(*c),
		Timestamp: internal.NewDateTime(c.Timestamp),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, c.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (c *CreateKnowledgeResponse) String() string {
	if c == nil {
		return "<nil>"
	}
	if len(c.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(c.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(c); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", c)
}

var (
	deleteKnowledgeResponseFieldData      = big.NewInt(1 << 0)
	deleteKnowledgeResponseFieldStatus    = big.NewInt(1 << 1)
	deleteKnowledgeResponseFieldCode      = big.NewInt(1 << 2)
	deleteKnowledgeResponseFieldMessage   = big.NewInt(1 << 3)
	deleteKnowledgeResponseFieldTraceID   = big.NewInt(1 << 4)
	deleteKnowledgeResponseFieldTimestamp = big.NewInt(1 << 5)
)

type DeleteKnowledgeResponse struct {
	Data      *OkResponse    `json:"data,omitempty" url:"data,omitempty"`
	Status    EnvelopeStatus `json:"status" url:"status"`
	Code      string         `json:"code" url:"code"`
	Message   string         `json:"message" url:"message"`
	TraceID   string         `json:"trace_id" url:"trace_id"`
	Timestamp time.Time      `json:"timestamp" url:"timestamp"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (d *DeleteKnowledgeResponse) GetData() *OkResponse {
	if d == nil {
		return nil
	}
	return d.Data
}

func (d *DeleteKnowledgeResponse) GetStatus() EnvelopeStatus {
	if d == nil {
		return ""
	}
	return d.Status
}

func (d *DeleteKnowledgeResponse) GetCode() string {
	if d == nil {
		return ""
	}
	return d.Code
}

func (d *DeleteKnowledgeResponse) GetMessage() string {
	if d == nil {
		return ""
	}
	return d.Message
}

func (d *DeleteKnowledgeResponse) GetTraceID() string {
	if d == nil {
		return ""
	}
	return d.TraceID
}

func (d *DeleteKnowledgeResponse) GetTimestamp() time.Time {
	if d == nil {
		return time.Time{}
	}
	return d.Timestamp
}

func (d *DeleteKnowledgeResponse) GetExtraProperties() map[string]interface{} {
	if d == nil {
		return nil
	}
	return d.extraProperties
}

func (d *DeleteKnowledgeResponse) require(field *big.Int) {
	if d.explicitFields == nil {
		d.explicitFields = big.NewInt(0)
	}
	d.explicitFields.Or(d.explicitFields, field)
}

// SetData sets the Data field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (d *DeleteKnowledgeResponse) SetData(data *OkResponse) {
	d.Data = data
	d.require(deleteKnowledgeResponseFieldData)
}

// SetStatus sets the Status field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (d *DeleteKnowledgeResponse) SetStatus(status EnvelopeStatus) {
	d.Status = status
	d.require(deleteKnowledgeResponseFieldStatus)
}

// SetCode sets the Code field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (d *DeleteKnowledgeResponse) SetCode(code string) {
	d.Code = code
	d.require(deleteKnowledgeResponseFieldCode)
}

// SetMessage sets the Message field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (d *DeleteKnowledgeResponse) SetMessage(message string) {
	d.Message = message
	d.require(deleteKnowledgeResponseFieldMessage)
}

// SetTraceID sets the TraceID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (d *DeleteKnowledgeResponse) SetTraceID(traceID string) {
	d.TraceID = traceID
	d.require(deleteKnowledgeResponseFieldTraceID)
}

// SetTimestamp sets the Timestamp field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (d *DeleteKnowledgeResponse) SetTimestamp(timestamp time.Time) {
	d.Timestamp = timestamp
	d.require(deleteKnowledgeResponseFieldTimestamp)
}

func (d *DeleteKnowledgeResponse) UnmarshalJSON(data []byte) error {
	type embed DeleteKnowledgeResponse
	var unmarshaler = struct {
		embed
		Timestamp *internal.DateTime `json:"timestamp"`
	}{
		embed: embed(*d),
	}
	if err := json.Unmarshal(data, &unmarshaler); err != nil {
		return err
	}
	*d = DeleteKnowledgeResponse(unmarshaler.embed)
	d.Timestamp = unmarshaler.Timestamp.Time()
	extraProperties, err := internal.ExtractExtraProperties(data, *d)
	if err != nil {
		return err
	}
	d.extraProperties = extraProperties
	d.rawJSON = json.RawMessage(data)
	return nil
}

func (d *DeleteKnowledgeResponse) MarshalJSON() ([]byte, error) {
	type embed DeleteKnowledgeResponse
	var marshaler = struct {
		embed
		Timestamp *internal.DateTime `json:"timestamp"`
	}{
		embed:     embed(*d),
		Timestamp: internal.NewDateTime(d.Timestamp),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, d.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (d *DeleteKnowledgeResponse) String() string {
	if d == nil {
		return "<nil>"
	}
	if len(d.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(d.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(d); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", d)
}

var (
	getKnowledgeResponseFieldData      = big.NewInt(1 << 0)
	getKnowledgeResponseFieldStatus    = big.NewInt(1 << 1)
	getKnowledgeResponseFieldCode      = big.NewInt(1 << 2)
	getKnowledgeResponseFieldMessage   = big.NewInt(1 << 3)
	getKnowledgeResponseFieldTraceID   = big.NewInt(1 << 4)
	getKnowledgeResponseFieldTimestamp = big.NewInt(1 << 5)
)

type GetKnowledgeResponse struct {
	Data      *KnowledgeDetail `json:"data,omitempty" url:"data,omitempty"`
	Status    EnvelopeStatus   `json:"status" url:"status"`
	Code      string           `json:"code" url:"code"`
	Message   string           `json:"message" url:"message"`
	TraceID   string           `json:"trace_id" url:"trace_id"`
	Timestamp time.Time        `json:"timestamp" url:"timestamp"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (g *GetKnowledgeResponse) GetData() *KnowledgeDetail {
	if g == nil {
		return nil
	}
	return g.Data
}

func (g *GetKnowledgeResponse) GetStatus() EnvelopeStatus {
	if g == nil {
		return ""
	}
	return g.Status
}

func (g *GetKnowledgeResponse) GetCode() string {
	if g == nil {
		return ""
	}
	return g.Code
}

func (g *GetKnowledgeResponse) GetMessage() string {
	if g == nil {
		return ""
	}
	return g.Message
}

func (g *GetKnowledgeResponse) GetTraceID() string {
	if g == nil {
		return ""
	}
	return g.TraceID
}

func (g *GetKnowledgeResponse) GetTimestamp() time.Time {
	if g == nil {
		return time.Time{}
	}
	return g.Timestamp
}

func (g *GetKnowledgeResponse) GetExtraProperties() map[string]interface{} {
	if g == nil {
		return nil
	}
	return g.extraProperties
}

func (g *GetKnowledgeResponse) require(field *big.Int) {
	if g.explicitFields == nil {
		g.explicitFields = big.NewInt(0)
	}
	g.explicitFields.Or(g.explicitFields, field)
}

// SetData sets the Data field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GetKnowledgeResponse) SetData(data *KnowledgeDetail) {
	g.Data = data
	g.require(getKnowledgeResponseFieldData)
}

// SetStatus sets the Status field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GetKnowledgeResponse) SetStatus(status EnvelopeStatus) {
	g.Status = status
	g.require(getKnowledgeResponseFieldStatus)
}

// SetCode sets the Code field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GetKnowledgeResponse) SetCode(code string) {
	g.Code = code
	g.require(getKnowledgeResponseFieldCode)
}

// SetMessage sets the Message field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GetKnowledgeResponse) SetMessage(message string) {
	g.Message = message
	g.require(getKnowledgeResponseFieldMessage)
}

// SetTraceID sets the TraceID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GetKnowledgeResponse) SetTraceID(traceID string) {
	g.TraceID = traceID
	g.require(getKnowledgeResponseFieldTraceID)
}

// SetTimestamp sets the Timestamp field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GetKnowledgeResponse) SetTimestamp(timestamp time.Time) {
	g.Timestamp = timestamp
	g.require(getKnowledgeResponseFieldTimestamp)
}

func (g *GetKnowledgeResponse) UnmarshalJSON(data []byte) error {
	type embed GetKnowledgeResponse
	var unmarshaler = struct {
		embed
		Timestamp *internal.DateTime `json:"timestamp"`
	}{
		embed: embed(*g),
	}
	if err := json.Unmarshal(data, &unmarshaler); err != nil {
		return err
	}
	*g = GetKnowledgeResponse(unmarshaler.embed)
	g.Timestamp = unmarshaler.Timestamp.Time()
	extraProperties, err := internal.ExtractExtraProperties(data, *g)
	if err != nil {
		return err
	}
	g.extraProperties = extraProperties
	g.rawJSON = json.RawMessage(data)
	return nil
}

func (g *GetKnowledgeResponse) MarshalJSON() ([]byte, error) {
	type embed GetKnowledgeResponse
	var marshaler = struct {
		embed
		Timestamp *internal.DateTime `json:"timestamp"`
	}{
		embed:     embed(*g),
		Timestamp: internal.NewDateTime(g.Timestamp),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, g.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (g *GetKnowledgeResponse) String() string {
	if g == nil {
		return "<nil>"
	}
	if len(g.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(g.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(g); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", g)
}

type KnowledgeCreateRequestContentType string

const (
	KnowledgeCreateRequestContentTypeText     KnowledgeCreateRequestContentType = "text"
	KnowledgeCreateRequestContentTypeMarkdown KnowledgeCreateRequestContentType = "markdown"
	KnowledgeCreateRequestContentTypeURL      KnowledgeCreateRequestContentType = "url"
	KnowledgeCreateRequestContentTypeFile     KnowledgeCreateRequestContentType = "file"
)

func NewKnowledgeCreateRequestContentTypeFromString(s string) (KnowledgeCreateRequestContentType, error) {
	switch s {
	case "text":
		return KnowledgeCreateRequestContentTypeText, nil
	case "markdown":
		return KnowledgeCreateRequestContentTypeMarkdown, nil
	case "url":
		return KnowledgeCreateRequestContentTypeURL, nil
	case "file":
		return KnowledgeCreateRequestContentTypeFile, nil
	}
	var t KnowledgeCreateRequestContentType
	return "", fmt.Errorf("%s is not a valid %T", s, t)
}

func (k KnowledgeCreateRequestContentType) Ptr() *KnowledgeCreateRequestContentType {
	return &k
}

var (
	listKnowledgeResponseFieldData      = big.NewInt(1 << 0)
	listKnowledgeResponseFieldStatus    = big.NewInt(1 << 1)
	listKnowledgeResponseFieldCode      = big.NewInt(1 << 2)
	listKnowledgeResponseFieldMessage   = big.NewInt(1 << 3)
	listKnowledgeResponseFieldTraceID   = big.NewInt(1 << 4)
	listKnowledgeResponseFieldTimestamp = big.NewInt(1 << 5)
)

type ListKnowledgeResponse struct {
	Data      []*Knowledge   `json:"data,omitempty" url:"data,omitempty"`
	Status    EnvelopeStatus `json:"status" url:"status"`
	Code      string         `json:"code" url:"code"`
	Message   string         `json:"message" url:"message"`
	TraceID   string         `json:"trace_id" url:"trace_id"`
	Timestamp time.Time      `json:"timestamp" url:"timestamp"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (l *ListKnowledgeResponse) GetData() []*Knowledge {
	if l == nil {
		return nil
	}
	return l.Data
}

func (l *ListKnowledgeResponse) GetStatus() EnvelopeStatus {
	if l == nil {
		return ""
	}
	return l.Status
}

func (l *ListKnowledgeResponse) GetCode() string {
	if l == nil {
		return ""
	}
	return l.Code
}

func (l *ListKnowledgeResponse) GetMessage() string {
	if l == nil {
		return ""
	}
	return l.Message
}

func (l *ListKnowledgeResponse) GetTraceID() string {
	if l == nil {
		return ""
	}
	return l.TraceID
}

func (l *ListKnowledgeResponse) GetTimestamp() time.Time {
	if l == nil {
		return time.Time{}
	}
	return l.Timestamp
}

func (l *ListKnowledgeResponse) GetExtraProperties() map[string]interface{} {
	if l == nil {
		return nil
	}
	return l.extraProperties
}

func (l *ListKnowledgeResponse) require(field *big.Int) {
	if l.explicitFields == nil {
		l.explicitFields = big.NewInt(0)
	}
	l.explicitFields.Or(l.explicitFields, field)
}

// SetData sets the Data field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *ListKnowledgeResponse) SetData(data []*Knowledge) {
	l.Data = data
	l.require(listKnowledgeResponseFieldData)
}

// SetStatus sets the Status field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *ListKnowledgeResponse) SetStatus(status EnvelopeStatus) {
	l.Status = status
	l.require(listKnowledgeResponseFieldStatus)
}

// SetCode sets the Code field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *ListKnowledgeResponse) SetCode(code string) {
	l.Code = code
	l.require(listKnowledgeResponseFieldCode)
}

// SetMessage sets the Message field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *ListKnowledgeResponse) SetMessage(message string) {
	l.Message = message
	l.require(listKnowledgeResponseFieldMessage)
}

// SetTraceID sets the TraceID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *ListKnowledgeResponse) SetTraceID(traceID string) {
	l.TraceID = traceID
	l.require(listKnowledgeResponseFieldTraceID)
}

// SetTimestamp sets the Timestamp field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *ListKnowledgeResponse) SetTimestamp(timestamp time.Time) {
	l.Timestamp = timestamp
	l.require(listKnowledgeResponseFieldTimestamp)
}

func (l *ListKnowledgeResponse) UnmarshalJSON(data []byte) error {
	type embed ListKnowledgeResponse
	var unmarshaler = struct {
		embed
		Timestamp *internal.DateTime `json:"timestamp"`
	}{
		embed: embed(*l),
	}
	if err := json.Unmarshal(data, &unmarshaler); err != nil {
		return err
	}
	*l = ListKnowledgeResponse(unmarshaler.embed)
	l.Timestamp = unmarshaler.Timestamp.Time()
	extraProperties, err := internal.ExtractExtraProperties(data, *l)
	if err != nil {
		return err
	}
	l.extraProperties = extraProperties
	l.rawJSON = json.RawMessage(data)
	return nil
}

func (l *ListKnowledgeResponse) MarshalJSON() ([]byte, error) {
	type embed ListKnowledgeResponse
	var marshaler = struct {
		embed
		Timestamp *internal.DateTime `json:"timestamp"`
	}{
		embed:     embed(*l),
		Timestamp: internal.NewDateTime(l.Timestamp),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, l.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (l *ListKnowledgeResponse) String() string {
	if l == nil {
		return "<nil>"
	}
	if len(l.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(l.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(l); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", l)
}
