// Code generated by Fern. DO NOT EDIT.

package api

import (
	json "encoding/json"
	fmt "fmt"
	internal "github.com/DTG-Corp/dtg-agent-sdk/internal"
	big "math/big"
	time "time"
)

var (
	mcpServerCreateRequestFieldIdempotencyKey = big.NewInt(1 << 0)
	mcpServerCreateRequestFieldName           = big.NewInt(1 << 1)
	mcpServerCreateRequestFieldDescription    = big.NewInt(1 << 2)
)

type McpServerCreateRequest struct {
	// Idempotency key cho mutation (tránh double-submit).
	IdempotencyKey *string `json:"-" url:"-"`
	Name           string  `json:"name" url:"-"`
	Description    *string `json:"description,omitempty" url:"-"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
}

func (m *McpServerCreateRequest) require(field *big.Int) {
	if m.explicitFields == nil {
		m.explicitFields = big.NewInt(0)
	}
	m.explicitFields.Or(m.explicitFields, field)
}

// SetIdempotencyKey sets the IdempotencyKey field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (m *McpServerCreateRequest) SetIdempotencyKey(idempotencyKey *string) {
	m.IdempotencyKey = idempotencyKey
	m.require(mcpServerCreateRequestFieldIdempotencyKey)
}

// SetName sets the Name field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (m *McpServerCreateRequest) SetName(name string) {
	m.Name = name
	m.require(mcpServerCreateRequestFieldName)
}

// SetDescription sets the Description field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (m *McpServerCreateRequest) SetDescription(description *string) {
	m.Description = description
	m.require(mcpServerCreateRequestFieldDescription)
}

func (m *McpServerCreateRequest) UnmarshalJSON(data []byte) error {
	type unmarshaler McpServerCreateRequest
	var body unmarshaler
	if err := json.Unmarshal(data, &body); err != nil {
		return err
	}
	*m = McpServerCreateRequest(body)
	return nil
}

func (m *McpServerCreateRequest) MarshalJSON() ([]byte, error) {
	type embed McpServerCreateRequest
	var marshaler = struct {
		embed
	}{
		embed: embed(*m),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, m.explicitFields)
	return json.Marshal(explicitMarshaler)
}

var (
	createMcpServerToolRequestFieldIdempotencyKey = big.NewInt(1 << 0)
	createMcpServerToolRequestFieldID             = big.NewInt(1 << 1)
)

type CreateMcpServerToolRequest struct {
	// Idempotency key cho mutation (tránh double-submit).
	IdempotencyKey *string        `json:"-" url:"-"`
	ID             string         `json:"-" url:"-"`
	Body           *McpServerTool `json:"-" url:"-"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
}

func (c *CreateMcpServerToolRequest) require(field *big.Int) {
	if c.explicitFields == nil {
		c.explicitFields = big.NewInt(0)
	}
	c.explicitFields.Or(c.explicitFields, field)
}

// SetIdempotencyKey sets the IdempotencyKey field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CreateMcpServerToolRequest) SetIdempotencyKey(idempotencyKey *string) {
	c.IdempotencyKey = idempotencyKey
	c.require(createMcpServerToolRequestFieldIdempotencyKey)
}

// SetID sets the ID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CreateMcpServerToolRequest) SetID(id string) {
	c.ID = id
	c.require(createMcpServerToolRequestFieldID)
}

func (c *CreateMcpServerToolRequest) UnmarshalJSON(data []byte) error {
	body := new(McpServerTool)
	if err := json.Unmarshal(data, &body); err != nil {
		return err
	}
	c.Body = body
	return nil
}

func (c *CreateMcpServerToolRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(c.Body)
}

var (
	listMcpServerToolsRequestFieldID = big.NewInt(1 << 0)
)

type ListMcpServerToolsRequest struct {
	ID string `json:"-" url:"-"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
}

func (l *ListMcpServerToolsRequest) require(field *big.Int) {
	if l.explicitFields == nil {
		l.explicitFields = big.NewInt(0)
	}
	l.explicitFields.Or(l.explicitFields, field)
}

// SetID sets the ID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *ListMcpServerToolsRequest) SetID(id string) {
	l.ID = id
	l.require(listMcpServerToolsRequestFieldID)
}

var (
	mcpServerFieldID          = big.NewInt(1 << 0)
	mcpServerFieldName        = big.NewInt(1 << 1)
	mcpServerFieldDescription = big.NewInt(1 << 2)
	mcpServerFieldToolCount   = big.NewInt(1 << 3)
	mcpServerFieldCreatedAt   = big.NewInt(1 << 4)
	mcpServerFieldUpdatedAt   = big.NewInt(1 << 5)
)

type McpServer struct {
	ID          *string    `json:"id,omitempty" url:"id,omitempty"`
	Name        *string    `json:"name,omitempty" url:"name,omitempty"`
	Description *string    `json:"description,omitempty" url:"description,omitempty"`
	ToolCount   *int       `json:"tool_count,omitempty" url:"tool_count,omitempty"`
	CreatedAt   *time.Time `json:"created_at,omitempty" url:"created_at,omitempty"`
	UpdatedAt   *time.Time `json:"updated_at,omitempty" url:"updated_at,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (m *McpServer) GetID() *string {
	if m == nil {
		return nil
	}
	return m.ID
}

func (m *McpServer) GetName() *string {
	if m == nil {
		return nil
	}
	return m.Name
}

func (m *McpServer) GetDescription() *string {
	if m == nil {
		return nil
	}
	return m.Description
}

func (m *McpServer) GetToolCount() *int {
	if m == nil {
		return nil
	}
	return m.ToolCount
}

func (m *McpServer) GetCreatedAt() *time.Time {
	if m == nil {
		return nil
	}
	return m.CreatedAt
}

func (m *McpServer) GetUpdatedAt() *time.Time {
	if m == nil {
		return nil
	}
	return m.UpdatedAt
}

func (m *McpServer) GetExtraProperties() map[string]interface{} {
	if m == nil {
		return nil
	}
	return m.extraProperties
}

func (m *McpServer) require(field *big.Int) {
	if m.explicitFields == nil {
		m.explicitFields = big.NewInt(0)
	}
	m.explicitFields.Or(m.explicitFields, field)
}

// SetID sets the ID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (m *McpServer) SetID(id *string) {
	m.ID = id
	m.require(mcpServerFieldID)
}

// SetName sets the Name field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (m *McpServer) SetName(name *string) {
	m.Name = name
	m.require(mcpServerFieldName)
}

// SetDescription sets the Description field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (m *McpServer) SetDescription(description *string) {
	m.Description = description
	m.require(mcpServerFieldDescription)
}

// SetToolCount sets the ToolCount field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (m *McpServer) SetToolCount(toolCount *int) {
	m.ToolCount = toolCount
	m.require(mcpServerFieldToolCount)
}

// SetCreatedAt sets the CreatedAt field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (m *McpServer) SetCreatedAt(createdAt *time.Time) {
	m.CreatedAt = createdAt
	m.require(mcpServerFieldCreatedAt)
}

// SetUpdatedAt sets the UpdatedAt field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (m *McpServer) SetUpdatedAt(updatedAt *time.Time) {
	m.UpdatedAt = updatedAt
	m.require(mcpServerFieldUpdatedAt)
}

func (m *McpServer) UnmarshalJSON(data []byte) error {
	type embed McpServer
	var unmarshaler = struct {
		embed
		CreatedAt *internal.DateTime `json:"created_at,omitempty"`
		UpdatedAt *internal.DateTime `json:"updated_at,omitempty"`
	}{
		embed: embed(*m),
	}
	if err := json.Unmarshal(data, &unmarshaler); err != nil {
		return err
	}
	*m = McpServer(unmarshaler.embed)
	m.CreatedAt = unmarshaler.CreatedAt.TimePtr()
	m.UpdatedAt = unmarshaler.UpdatedAt.TimePtr()
	extraProperties, err := internal.ExtractExtraProperties(data, *m)
	if err != nil {
		return err
	}
	m.extraProperties = extraProperties
	m.rawJSON = json.RawMessage(data)
	return nil
}

func (m *McpServer) MarshalJSON() ([]byte, error) {
	type embed McpServer
	var marshaler = struct {
		embed
		CreatedAt *internal.DateTime `json:"created_at,omitempty"`
		UpdatedAt *internal.DateTime `json:"updated_at,omitempty"`
	}{
		embed:     embed(*m),
		CreatedAt: internal.NewOptionalDateTime(m.CreatedAt),
		UpdatedAt: internal.NewOptionalDateTime(m.UpdatedAt),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, m.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (m *McpServer) String() string {
	if m == nil {
		return "<nil>"
	}
	if len(m.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(m.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(m); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", m)
}

var (
	mcpServerToolFieldID          = big.NewInt(1 << 0)
	mcpServerToolFieldMcpServerID = big.NewInt(1 << 1)
	mcpServerToolFieldKind        = big.NewInt(1 << 2)
	mcpServerToolFieldSlug        = big.NewInt(1 << 3)
	mcpServerToolFieldDisplayName = big.NewInt(1 << 4)
	mcpServerToolFieldDescription = big.NewInt(1 << 5)
	mcpServerToolFieldBaseURL     = big.NewInt(1 << 6)
	mcpServerToolFieldAuthType    = big.NewInt(1 << 7)
	mcpServerToolFieldAuthConfig  = big.NewInt(1 << 8)
	mcpServerToolFieldEndpoints   = big.NewInt(1 << 9)
	mcpServerToolFieldSortOrder   = big.NewInt(1 << 10)
	mcpServerToolFieldIsActive    = big.NewInt(1 << 11)
	mcpServerToolFieldCreatedAt   = big.NewInt(1 << 12)
	mcpServerToolFieldUpdatedAt   = big.NewInt(1 << 13)
)

type McpServerTool struct {
	ID          *string                `json:"id,omitempty" url:"id,omitempty"`
	McpServerID *string                `json:"mcp_server_id,omitempty" url:"mcp_server_id,omitempty"`
	Kind        *McpServerToolKind     `json:"kind,omitempty" url:"kind,omitempty"`
	Slug        *string                `json:"slug,omitempty" url:"slug,omitempty"`
	DisplayName *string                `json:"display_name,omitempty" url:"display_name,omitempty"`
	Description *string                `json:"description,omitempty" url:"description,omitempty"`
	BaseURL     *string                `json:"base_url,omitempty" url:"base_url,omitempty"`
	AuthType    *McpServerToolAuthType `json:"auth_type,omitempty" url:"auth_type,omitempty"`
	// Thông tin xác thực (có thể chứa secret — không phơi raw token ở list).
	AuthConfig map[string]any   `json:"auth_config,omitempty" url:"auth_config,omitempty"`
	Endpoints  []map[string]any `json:"endpoints,omitempty" url:"endpoints,omitempty"`
	SortOrder  *int             `json:"sort_order,omitempty" url:"sort_order,omitempty"`
	IsActive   *bool            `json:"is_active,omitempty" url:"is_active,omitempty"`
	CreatedAt  *time.Time       `json:"created_at,omitempty" url:"created_at,omitempty"`
	UpdatedAt  *time.Time       `json:"updated_at,omitempty" url:"updated_at,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (m *McpServerTool) GetID() *string {
	if m == nil {
		return nil
	}
	return m.ID
}

func (m *McpServerTool) GetMcpServerID() *string {
	if m == nil {
		return nil
	}
	return m.McpServerID
}

func (m *McpServerTool) GetKind() *McpServerToolKind {
	if m == nil {
		return nil
	}
	return m.Kind
}

func (m *McpServerTool) GetSlug() *string {
	if m == nil {
		return nil
	}
	return m.Slug
}

func (m *McpServerTool) GetDisplayName() *string {
	if m == nil {
		return nil
	}
	return m.DisplayName
}

func (m *McpServerTool) GetDescription() *string {
	if m == nil {
		return nil
	}
	return m.Description
}

func (m *McpServerTool) GetBaseURL() *string {
	if m == nil {
		return nil
	}
	return m.BaseURL
}

func (m *McpServerTool) GetAuthType() *McpServerToolAuthType {
	if m == nil {
		return nil
	}
	return m.AuthType
}

func (m *McpServerTool) GetAuthConfig() map[string]any {
	if m == nil {
		return nil
	}
	return m.AuthConfig
}

func (m *McpServerTool) GetEndpoints() []map[string]any {
	if m == nil {
		return nil
	}
	return m.Endpoints
}

func (m *McpServerTool) GetSortOrder() *int {
	if m == nil {
		return nil
	}
	return m.SortOrder
}

func (m *McpServerTool) GetIsActive() *bool {
	if m == nil {
		return nil
	}
	return m.IsActive
}

func (m *McpServerTool) GetCreatedAt() *time.Time {
	if m == nil {
		return nil
	}
	return m.CreatedAt
}

func (m *McpServerTool) GetUpdatedAt() *time.Time {
	if m == nil {
		return nil
	}
	return m.UpdatedAt
}

func (m *McpServerTool) GetExtraProperties() map[string]interface{} {
	if m == nil {
		return nil
	}
	return m.extraProperties
}

func (m *McpServerTool) require(field *big.Int) {
	if m.explicitFields == nil {
		m.explicitFields = big.NewInt(0)
	}
	m.explicitFields.Or(m.explicitFields, field)
}

// SetID sets the ID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (m *McpServerTool) SetID(id *string) {
	m.ID = id
	m.require(mcpServerToolFieldID)
}

// SetMcpServerID sets the McpServerID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (m *McpServerTool) SetMcpServerID(mcpServerID *string) {
	m.McpServerID = mcpServerID
	m.require(mcpServerToolFieldMcpServerID)
}

// SetKind sets the Kind field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (m *McpServerTool) SetKind(kind *McpServerToolKind) {
	m.Kind = kind
	m.require(mcpServerToolFieldKind)
}

// SetSlug sets the Slug field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (m *McpServerTool) SetSlug(slug *string) {
	m.Slug = slug
	m.require(mcpServerToolFieldSlug)
}

// SetDisplayName sets the DisplayName field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (m *McpServerTool) SetDisplayName(displayName *string) {
	m.DisplayName = displayName
	m.require(mcpServerToolFieldDisplayName)
}

// SetDescription sets the Description field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (m *McpServerTool) SetDescription(description *string) {
	m.Description = description
	m.require(mcpServerToolFieldDescription)
}

// SetBaseURL sets the BaseURL field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (m *McpServerTool) SetBaseURL(baseURL *string) {
	m.BaseURL = baseURL
	m.require(mcpServerToolFieldBaseURL)
}

// SetAuthType sets the AuthType field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (m *McpServerTool) SetAuthType(authType *McpServerToolAuthType) {
	m.AuthType = authType
	m.require(mcpServerToolFieldAuthType)
}

// SetAuthConfig sets the AuthConfig field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (m *McpServerTool) SetAuthConfig(authConfig map[string]any) {
	m.AuthConfig = authConfig
	m.require(mcpServerToolFieldAuthConfig)
}

// SetEndpoints sets the Endpoints field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (m *McpServerTool) SetEndpoints(endpoints []map[string]any) {
	m.Endpoints = endpoints
	m.require(mcpServerToolFieldEndpoints)
}

// SetSortOrder sets the SortOrder field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (m *McpServerTool) SetSortOrder(sortOrder *int) {
	m.SortOrder = sortOrder
	m.require(mcpServerToolFieldSortOrder)
}

// SetIsActive sets the IsActive field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (m *McpServerTool) SetIsActive(isActive *bool) {
	m.IsActive = isActive
	m.require(mcpServerToolFieldIsActive)
}

// SetCreatedAt sets the CreatedAt field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (m *McpServerTool) SetCreatedAt(createdAt *time.Time) {
	m.CreatedAt = createdAt
	m.require(mcpServerToolFieldCreatedAt)
}

// SetUpdatedAt sets the UpdatedAt field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (m *McpServerTool) SetUpdatedAt(updatedAt *time.Time) {
	m.UpdatedAt = updatedAt
	m.require(mcpServerToolFieldUpdatedAt)
}

func (m *McpServerTool) UnmarshalJSON(data []byte) error {
	type embed McpServerTool
	var unmarshaler = struct {
		embed
		CreatedAt *internal.DateTime `json:"created_at,omitempty"`
		UpdatedAt *internal.DateTime `json:"updated_at,omitempty"`
	}{
		embed: embed(*m),
	}
	if err := json.Unmarshal(data, &unmarshaler); err != nil {
		return err
	}
	*m = McpServerTool(unmarshaler.embed)
	m.CreatedAt = unmarshaler.CreatedAt.TimePtr()
	m.UpdatedAt = unmarshaler.UpdatedAt.TimePtr()
	extraProperties, err := internal.ExtractExtraProperties(data, *m)
	if err != nil {
		return err
	}
	m.extraProperties = extraProperties
	m.rawJSON = json.RawMessage(data)
	return nil
}

func (m *McpServerTool) MarshalJSON() ([]byte, error) {
	type embed McpServerTool
	var marshaler = struct {
		embed
		CreatedAt *internal.DateTime `json:"created_at,omitempty"`
		UpdatedAt *internal.DateTime `json:"updated_at,omitempty"`
	}{
		embed:     embed(*m),
		CreatedAt: internal.NewOptionalDateTime(m.CreatedAt),
		UpdatedAt: internal.NewOptionalDateTime(m.UpdatedAt),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, m.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (m *McpServerTool) String() string {
	if m == nil {
		return "<nil>"
	}
	if len(m.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(m.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(m); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", m)
}

type McpServerToolAuthType string

const (
	McpServerToolAuthTypeNone     McpServerToolAuthType = "none"
	McpServerToolAuthTypeBearer   McpServerToolAuthType = "bearer"
	McpServerToolAuthTypeAPIKey   McpServerToolAuthType = "api_key"
	McpServerToolAuthTypeBasic    McpServerToolAuthType = "basic"
	McpServerToolAuthTypeSQLQuery McpServerToolAuthType = "sql_query"
)

func NewMcpServerToolAuthTypeFromString(s string) (McpServerToolAuthType, error) {
	switch s {
	case "none":
		return McpServerToolAuthTypeNone, nil
	case "bearer":
		return McpServerToolAuthTypeBearer, nil
	case "api_key":
		return McpServerToolAuthTypeAPIKey, nil
	case "basic":
		return McpServerToolAuthTypeBasic, nil
	case "sql_query":
		return McpServerToolAuthTypeSQLQuery, nil
	}
	var t McpServerToolAuthType
	return "", fmt.Errorf("%s is not a valid %T", s, t)
}

func (m McpServerToolAuthType) Ptr() *McpServerToolAuthType {
	return &m
}

type McpServerToolKind string

const (
	McpServerToolKindRest  McpServerToolKind = "rest"
	McpServerToolKindSQL   McpServerToolKind = "sql"
	McpServerToolKindMongo McpServerToolKind = "mongo"
	McpServerToolKindRedis McpServerToolKind = "redis"
)

func NewMcpServerToolKindFromString(s string) (McpServerToolKind, error) {
	switch s {
	case "rest":
		return McpServerToolKindRest, nil
	case "sql":
		return McpServerToolKindSQL, nil
	case "mongo":
		return McpServerToolKindMongo, nil
	case "redis":
		return McpServerToolKindRedis, nil
	}
	var t McpServerToolKind
	return "", fmt.Errorf("%s is not a valid %T", s, t)
}

func (m McpServerToolKind) Ptr() *McpServerToolKind {
	return &m
}

var (
	createMcpServerResponseFieldData      = big.NewInt(1 << 0)
	createMcpServerResponseFieldStatus    = big.NewInt(1 << 1)
	createMcpServerResponseFieldCode      = big.NewInt(1 << 2)
	createMcpServerResponseFieldMessage   = big.NewInt(1 << 3)
	createMcpServerResponseFieldTraceID   = big.NewInt(1 << 4)
	createMcpServerResponseFieldTimestamp = big.NewInt(1 << 5)
)

type CreateMcpServerResponse struct {
	Data      *McpServer     `json:"data,omitempty" url:"data,omitempty"`
	Status    EnvelopeStatus `json:"status" url:"status"`
	Code      string         `json:"code" url:"code"`
	Message   string         `json:"message" url:"message"`
	TraceID   string         `json:"trace_id" url:"trace_id"`
	Timestamp time.Time      `json:"timestamp" url:"timestamp"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (c *CreateMcpServerResponse) GetData() *McpServer {
	if c == nil {
		return nil
	}
	return c.Data
}

func (c *CreateMcpServerResponse) GetStatus() EnvelopeStatus {
	if c == nil {
		return ""
	}
	return c.Status
}

func (c *CreateMcpServerResponse) GetCode() string {
	if c == nil {
		return ""
	}
	return c.Code
}

func (c *CreateMcpServerResponse) GetMessage() string {
	if c == nil {
		return ""
	}
	return c.Message
}

func (c *CreateMcpServerResponse) GetTraceID() string {
	if c == nil {
		return ""
	}
	return c.TraceID
}

func (c *CreateMcpServerResponse) GetTimestamp() time.Time {
	if c == nil {
		return time.Time{}
	}
	return c.Timestamp
}

func (c *CreateMcpServerResponse) GetExtraProperties() map[string]interface{} {
	if c == nil {
		return nil
	}
	return c.extraProperties
}

func (c *CreateMcpServerResponse) require(field *big.Int) {
	if c.explicitFields == nil {
		c.explicitFields = big.NewInt(0)
	}
	c.explicitFields.Or(c.explicitFields, field)
}

// SetData sets the Data field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CreateMcpServerResponse) SetData(data *McpServer) {
	c.Data = data
	c.require(createMcpServerResponseFieldData)
}

// SetStatus sets the Status field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CreateMcpServerResponse) SetStatus(status EnvelopeStatus) {
	c.Status = status
	c.require(createMcpServerResponseFieldStatus)
}

// SetCode sets the Code field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CreateMcpServerResponse) SetCode(code string) {
	c.Code = code
	c.require(createMcpServerResponseFieldCode)
}

// SetMessage sets the Message field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CreateMcpServerResponse) SetMessage(message string) {
	c.Message = message
	c.require(createMcpServerResponseFieldMessage)
}

// SetTraceID sets the TraceID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CreateMcpServerResponse) SetTraceID(traceID string) {
	c.TraceID = traceID
	c.require(createMcpServerResponseFieldTraceID)
}

// SetTimestamp sets the Timestamp field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CreateMcpServerResponse) SetTimestamp(timestamp time.Time) {
	c.Timestamp = timestamp
	c.require(createMcpServerResponseFieldTimestamp)
}

func (c *CreateMcpServerResponse) UnmarshalJSON(data []byte) error {
	type embed CreateMcpServerResponse
	var unmarshaler = struct {
		embed
		Timestamp *internal.DateTime `json:"timestamp"`
	}{
		embed: embed(*c),
	}
	if err := json.Unmarshal(data, &unmarshaler); err != nil {
		return err
	}
	*c = CreateMcpServerResponse(unmarshaler.embed)
	c.Timestamp = unmarshaler.Timestamp.Time()
	extraProperties, err := internal.ExtractExtraProperties(data, *c)
	if err != nil {
		return err
	}
	c.extraProperties = extraProperties
	c.rawJSON = json.RawMessage(data)
	return nil
}

func (c *CreateMcpServerResponse) MarshalJSON() ([]byte, error) {
	type embed CreateMcpServerResponse
	var marshaler = struct {
		embed
		Timestamp *internal.DateTime `json:"timestamp"`
	}{
		embed:     embed(*c),
		Timestamp: internal.NewDateTime(c.Timestamp),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, c.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (c *CreateMcpServerResponse) String() string {
	if c == nil {
		return "<nil>"
	}
	if len(c.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(c.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(c); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", c)
}

var (
	createMcpServerToolResponseFieldData      = big.NewInt(1 << 0)
	createMcpServerToolResponseFieldStatus    = big.NewInt(1 << 1)
	createMcpServerToolResponseFieldCode      = big.NewInt(1 << 2)
	createMcpServerToolResponseFieldMessage   = big.NewInt(1 << 3)
	createMcpServerToolResponseFieldTraceID   = big.NewInt(1 << 4)
	createMcpServerToolResponseFieldTimestamp = big.NewInt(1 << 5)
)

type CreateMcpServerToolResponse struct {
	Data      *McpServerTool `json:"data,omitempty" url:"data,omitempty"`
	Status    EnvelopeStatus `json:"status" url:"status"`
	Code      string         `json:"code" url:"code"`
	Message   string         `json:"message" url:"message"`
	TraceID   string         `json:"trace_id" url:"trace_id"`
	Timestamp time.Time      `json:"timestamp" url:"timestamp"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (c *CreateMcpServerToolResponse) GetData() *McpServerTool {
	if c == nil {
		return nil
	}
	return c.Data
}

func (c *CreateMcpServerToolResponse) GetStatus() EnvelopeStatus {
	if c == nil {
		return ""
	}
	return c.Status
}

func (c *CreateMcpServerToolResponse) GetCode() string {
	if c == nil {
		return ""
	}
	return c.Code
}

func (c *CreateMcpServerToolResponse) GetMessage() string {
	if c == nil {
		return ""
	}
	return c.Message
}

func (c *CreateMcpServerToolResponse) GetTraceID() string {
	if c == nil {
		return ""
	}
	return c.TraceID
}

func (c *CreateMcpServerToolResponse) GetTimestamp() time.Time {
	if c == nil {
		return time.Time{}
	}
	return c.Timestamp
}

func (c *CreateMcpServerToolResponse) GetExtraProperties() map[string]interface{} {
	if c == nil {
		return nil
	}
	return c.extraProperties
}

func (c *CreateMcpServerToolResponse) require(field *big.Int) {
	if c.explicitFields == nil {
		c.explicitFields = big.NewInt(0)
	}
	c.explicitFields.Or(c.explicitFields, field)
}

// SetData sets the Data field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CreateMcpServerToolResponse) SetData(data *McpServerTool) {
	c.Data = data
	c.require(createMcpServerToolResponseFieldData)
}

// SetStatus sets the Status field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CreateMcpServerToolResponse) SetStatus(status EnvelopeStatus) {
	c.Status = status
	c.require(createMcpServerToolResponseFieldStatus)
}

// SetCode sets the Code field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CreateMcpServerToolResponse) SetCode(code string) {
	c.Code = code
	c.require(createMcpServerToolResponseFieldCode)
}

// SetMessage sets the Message field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CreateMcpServerToolResponse) SetMessage(message string) {
	c.Message = message
	c.require(createMcpServerToolResponseFieldMessage)
}

// SetTraceID sets the TraceID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CreateMcpServerToolResponse) SetTraceID(traceID string) {
	c.TraceID = traceID
	c.require(createMcpServerToolResponseFieldTraceID)
}

// SetTimestamp sets the Timestamp field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CreateMcpServerToolResponse) SetTimestamp(timestamp time.Time) {
	c.Timestamp = timestamp
	c.require(createMcpServerToolResponseFieldTimestamp)
}

func (c *CreateMcpServerToolResponse) UnmarshalJSON(data []byte) error {
	type embed CreateMcpServerToolResponse
	var unmarshaler = struct {
		embed
		Timestamp *internal.DateTime `json:"timestamp"`
	}{
		embed: embed(*c),
	}
	if err := json.Unmarshal(data, &unmarshaler); err != nil {
		return err
	}
	*c = CreateMcpServerToolResponse(unmarshaler.embed)
	c.Timestamp = unmarshaler.Timestamp.Time()
	extraProperties, err := internal.ExtractExtraProperties(data, *c)
	if err != nil {
		return err
	}
	c.extraProperties = extraProperties
	c.rawJSON = json.RawMessage(data)
	return nil
}

func (c *CreateMcpServerToolResponse) MarshalJSON() ([]byte, error) {
	type embed CreateMcpServerToolResponse
	var marshaler = struct {
		embed
		Timestamp *internal.DateTime `json:"timestamp"`
	}{
		embed:     embed(*c),
		Timestamp: internal.NewDateTime(c.Timestamp),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, c.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (c *CreateMcpServerToolResponse) String() string {
	if c == nil {
		return "<nil>"
	}
	if len(c.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(c.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(c); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", c)
}

var (
	listMcpServerToolsResponseFieldData      = big.NewInt(1 << 0)
	listMcpServerToolsResponseFieldStatus    = big.NewInt(1 << 1)
	listMcpServerToolsResponseFieldCode      = big.NewInt(1 << 2)
	listMcpServerToolsResponseFieldMessage   = big.NewInt(1 << 3)
	listMcpServerToolsResponseFieldTraceID   = big.NewInt(1 << 4)
	listMcpServerToolsResponseFieldTimestamp = big.NewInt(1 << 5)
)

type ListMcpServerToolsResponse struct {
	Data      []*McpServerTool `json:"data,omitempty" url:"data,omitempty"`
	Status    EnvelopeStatus   `json:"status" url:"status"`
	Code      string           `json:"code" url:"code"`
	Message   string           `json:"message" url:"message"`
	TraceID   string           `json:"trace_id" url:"trace_id"`
	Timestamp time.Time        `json:"timestamp" url:"timestamp"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (l *ListMcpServerToolsResponse) GetData() []*McpServerTool {
	if l == nil {
		return nil
	}
	return l.Data
}

func (l *ListMcpServerToolsResponse) GetStatus() EnvelopeStatus {
	if l == nil {
		return ""
	}
	return l.Status
}

func (l *ListMcpServerToolsResponse) GetCode() string {
	if l == nil {
		return ""
	}
	return l.Code
}

func (l *ListMcpServerToolsResponse) GetMessage() string {
	if l == nil {
		return ""
	}
	return l.Message
}

func (l *ListMcpServerToolsResponse) GetTraceID() string {
	if l == nil {
		return ""
	}
	return l.TraceID
}

func (l *ListMcpServerToolsResponse) GetTimestamp() time.Time {
	if l == nil {
		return time.Time{}
	}
	return l.Timestamp
}

func (l *ListMcpServerToolsResponse) GetExtraProperties() map[string]interface{} {
	if l == nil {
		return nil
	}
	return l.extraProperties
}

func (l *ListMcpServerToolsResponse) require(field *big.Int) {
	if l.explicitFields == nil {
		l.explicitFields = big.NewInt(0)
	}
	l.explicitFields.Or(l.explicitFields, field)
}

// SetData sets the Data field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *ListMcpServerToolsResponse) SetData(data []*McpServerTool) {
	l.Data = data
	l.require(listMcpServerToolsResponseFieldData)
}

// SetStatus sets the Status field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *ListMcpServerToolsResponse) SetStatus(status EnvelopeStatus) {
	l.Status = status
	l.require(listMcpServerToolsResponseFieldStatus)
}

// SetCode sets the Code field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *ListMcpServerToolsResponse) SetCode(code string) {
	l.Code = code
	l.require(listMcpServerToolsResponseFieldCode)
}

// SetMessage sets the Message field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *ListMcpServerToolsResponse) SetMessage(message string) {
	l.Message = message
	l.require(listMcpServerToolsResponseFieldMessage)
}

// SetTraceID sets the TraceID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *ListMcpServerToolsResponse) SetTraceID(traceID string) {
	l.TraceID = traceID
	l.require(listMcpServerToolsResponseFieldTraceID)
}

// SetTimestamp sets the Timestamp field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *ListMcpServerToolsResponse) SetTimestamp(timestamp time.Time) {
	l.Timestamp = timestamp
	l.require(listMcpServerToolsResponseFieldTimestamp)
}

func (l *ListMcpServerToolsResponse) UnmarshalJSON(data []byte) error {
	type embed ListMcpServerToolsResponse
	var unmarshaler = struct {
		embed
		Timestamp *internal.DateTime `json:"timestamp"`
	}{
		embed: embed(*l),
	}
	if err := json.Unmarshal(data, &unmarshaler); err != nil {
		return err
	}
	*l = ListMcpServerToolsResponse(unmarshaler.embed)
	l.Timestamp = unmarshaler.Timestamp.Time()
	extraProperties, err := internal.ExtractExtraProperties(data, *l)
	if err != nil {
		return err
	}
	l.extraProperties = extraProperties
	l.rawJSON = json.RawMessage(data)
	return nil
}

func (l *ListMcpServerToolsResponse) MarshalJSON() ([]byte, error) {
	type embed ListMcpServerToolsResponse
	var marshaler = struct {
		embed
		Timestamp *internal.DateTime `json:"timestamp"`
	}{
		embed:     embed(*l),
		Timestamp: internal.NewDateTime(l.Timestamp),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, l.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (l *ListMcpServerToolsResponse) String() string {
	if l == nil {
		return "<nil>"
	}
	if len(l.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(l.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(l); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", l)
}

var (
	listMcpServersResponseFieldData      = big.NewInt(1 << 0)
	listMcpServersResponseFieldStatus    = big.NewInt(1 << 1)
	listMcpServersResponseFieldCode      = big.NewInt(1 << 2)
	listMcpServersResponseFieldMessage   = big.NewInt(1 << 3)
	listMcpServersResponseFieldTraceID   = big.NewInt(1 << 4)
	listMcpServersResponseFieldTimestamp = big.NewInt(1 << 5)
)

type ListMcpServersResponse struct {
	Data      []*McpServer   `json:"data,omitempty" url:"data,omitempty"`
	Status    EnvelopeStatus `json:"status" url:"status"`
	Code      string         `json:"code" url:"code"`
	Message   string         `json:"message" url:"message"`
	TraceID   string         `json:"trace_id" url:"trace_id"`
	Timestamp time.Time      `json:"timestamp" url:"timestamp"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (l *ListMcpServersResponse) GetData() []*McpServer {
	if l == nil {
		return nil
	}
	return l.Data
}

func (l *ListMcpServersResponse) GetStatus() EnvelopeStatus {
	if l == nil {
		return ""
	}
	return l.Status
}

func (l *ListMcpServersResponse) GetCode() string {
	if l == nil {
		return ""
	}
	return l.Code
}

func (l *ListMcpServersResponse) GetMessage() string {
	if l == nil {
		return ""
	}
	return l.Message
}

func (l *ListMcpServersResponse) GetTraceID() string {
	if l == nil {
		return ""
	}
	return l.TraceID
}

func (l *ListMcpServersResponse) GetTimestamp() time.Time {
	if l == nil {
		return time.Time{}
	}
	return l.Timestamp
}

func (l *ListMcpServersResponse) GetExtraProperties() map[string]interface{} {
	if l == nil {
		return nil
	}
	return l.extraProperties
}

func (l *ListMcpServersResponse) require(field *big.Int) {
	if l.explicitFields == nil {
		l.explicitFields = big.NewInt(0)
	}
	l.explicitFields.Or(l.explicitFields, field)
}

// SetData sets the Data field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *ListMcpServersResponse) SetData(data []*McpServer) {
	l.Data = data
	l.require(listMcpServersResponseFieldData)
}

// SetStatus sets the Status field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *ListMcpServersResponse) SetStatus(status EnvelopeStatus) {
	l.Status = status
	l.require(listMcpServersResponseFieldStatus)
}

// SetCode sets the Code field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *ListMcpServersResponse) SetCode(code string) {
	l.Code = code
	l.require(listMcpServersResponseFieldCode)
}

// SetMessage sets the Message field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *ListMcpServersResponse) SetMessage(message string) {
	l.Message = message
	l.require(listMcpServersResponseFieldMessage)
}

// SetTraceID sets the TraceID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *ListMcpServersResponse) SetTraceID(traceID string) {
	l.TraceID = traceID
	l.require(listMcpServersResponseFieldTraceID)
}

// SetTimestamp sets the Timestamp field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *ListMcpServersResponse) SetTimestamp(timestamp time.Time) {
	l.Timestamp = timestamp
	l.require(listMcpServersResponseFieldTimestamp)
}

func (l *ListMcpServersResponse) UnmarshalJSON(data []byte) error {
	type embed ListMcpServersResponse
	var unmarshaler = struct {
		embed
		Timestamp *internal.DateTime `json:"timestamp"`
	}{
		embed: embed(*l),
	}
	if err := json.Unmarshal(data, &unmarshaler); err != nil {
		return err
	}
	*l = ListMcpServersResponse(unmarshaler.embed)
	l.Timestamp = unmarshaler.Timestamp.Time()
	extraProperties, err := internal.ExtractExtraProperties(data, *l)
	if err != nil {
		return err
	}
	l.extraProperties = extraProperties
	l.rawJSON = json.RawMessage(data)
	return nil
}

func (l *ListMcpServersResponse) MarshalJSON() ([]byte, error) {
	type embed ListMcpServersResponse
	var marshaler = struct {
		embed
		Timestamp *internal.DateTime `json:"timestamp"`
	}{
		embed:     embed(*l),
		Timestamp: internal.NewDateTime(l.Timestamp),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, l.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (l *ListMcpServersResponse) String() string {
	if l == nil {
		return "<nil>"
	}
	if len(l.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(l.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(l); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", l)
}
