// Code generated by Fern. DO NOT EDIT.

package api

import (
	json "encoding/json"
	fmt "fmt"
	internal "github.com/DTG-Corp/dtg-sdk-go/internal"
	big "math/big"
	time "time"
)

var (
	getOrganizationRequestFieldID = big.NewInt(1 << 0)
)

type GetOrganizationRequest struct {
	ID string `json:"-" url:"-"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
}

func (g *GetOrganizationRequest) require(field *big.Int) {
	if g.explicitFields == nil {
		g.explicitFields = big.NewInt(0)
	}
	g.explicitFields.Or(g.explicitFields, field)
}

// SetID sets the ID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GetOrganizationRequest) SetID(id string) {
	g.ID = id
	g.require(getOrganizationRequestFieldID)
}

var (
	listOrganizationMembersRequestFieldID = big.NewInt(1 << 0)
)

type ListOrganizationMembersRequest struct {
	ID string `json:"-" url:"-"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
}

func (l *ListOrganizationMembersRequest) require(field *big.Int) {
	if l.explicitFields == nil {
		l.explicitFields = big.NewInt(0)
	}
	l.explicitFields.Or(l.explicitFields, field)
}

// SetID sets the ID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *ListOrganizationMembersRequest) SetID(id string) {
	l.ID = id
	l.require(listOrganizationMembersRequestFieldID)
}

var (
	organizationFieldID          = big.NewInt(1 << 0)
	organizationFieldSlug        = big.NewInt(1 << 1)
	organizationFieldDisplayName = big.NewInt(1 << 2)
	organizationFieldDescription = big.NewInt(1 << 3)
)

type Organization struct {
	ID          *string `json:"id,omitempty" url:"id,omitempty"`
	Slug        *string `json:"slug,omitempty" url:"slug,omitempty"`
	DisplayName *string `json:"display_name,omitempty" url:"display_name,omitempty"`
	Description *string `json:"description,omitempty" url:"description,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (o *Organization) GetID() *string {
	if o == nil {
		return nil
	}
	return o.ID
}

func (o *Organization) GetSlug() *string {
	if o == nil {
		return nil
	}
	return o.Slug
}

func (o *Organization) GetDisplayName() *string {
	if o == nil {
		return nil
	}
	return o.DisplayName
}

func (o *Organization) GetDescription() *string {
	if o == nil {
		return nil
	}
	return o.Description
}

func (o *Organization) GetExtraProperties() map[string]interface{} {
	if o == nil {
		return nil
	}
	return o.extraProperties
}

func (o *Organization) require(field *big.Int) {
	if o.explicitFields == nil {
		o.explicitFields = big.NewInt(0)
	}
	o.explicitFields.Or(o.explicitFields, field)
}

// SetID sets the ID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (o *Organization) SetID(id *string) {
	o.ID = id
	o.require(organizationFieldID)
}

// SetSlug sets the Slug field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (o *Organization) SetSlug(slug *string) {
	o.Slug = slug
	o.require(organizationFieldSlug)
}

// SetDisplayName sets the DisplayName field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (o *Organization) SetDisplayName(displayName *string) {
	o.DisplayName = displayName
	o.require(organizationFieldDisplayName)
}

// SetDescription sets the Description field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (o *Organization) SetDescription(description *string) {
	o.Description = description
	o.require(organizationFieldDescription)
}

func (o *Organization) UnmarshalJSON(data []byte) error {
	type unmarshaler Organization
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*o = Organization(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *o)
	if err != nil {
		return err
	}
	o.extraProperties = extraProperties
	o.rawJSON = json.RawMessage(data)
	return nil
}

func (o *Organization) MarshalJSON() ([]byte, error) {
	type embed Organization
	var marshaler = struct {
		embed
	}{
		embed: embed(*o),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, o.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (o *Organization) String() string {
	if o == nil {
		return "<nil>"
	}
	if len(o.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(o.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(o); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", o)
}

var (
	organizationMemberFieldAccountID = big.NewInt(1 << 0)
	organizationMemberFieldEmail     = big.NewInt(1 << 1)
	organizationMemberFieldRole      = big.NewInt(1 << 2)
)

type OrganizationMember struct {
	AccountID *string                 `json:"account_id,omitempty" url:"account_id,omitempty"`
	Email     *string                 `json:"email,omitempty" url:"email,omitempty"`
	Role      *OrganizationMemberRole `json:"role,omitempty" url:"role,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (o *OrganizationMember) GetAccountID() *string {
	if o == nil {
		return nil
	}
	return o.AccountID
}

func (o *OrganizationMember) GetEmail() *string {
	if o == nil {
		return nil
	}
	return o.Email
}

func (o *OrganizationMember) GetRole() *OrganizationMemberRole {
	if o == nil {
		return nil
	}
	return o.Role
}

func (o *OrganizationMember) GetExtraProperties() map[string]interface{} {
	if o == nil {
		return nil
	}
	return o.extraProperties
}

func (o *OrganizationMember) require(field *big.Int) {
	if o.explicitFields == nil {
		o.explicitFields = big.NewInt(0)
	}
	o.explicitFields.Or(o.explicitFields, field)
}

// SetAccountID sets the AccountID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (o *OrganizationMember) SetAccountID(accountID *string) {
	o.AccountID = accountID
	o.require(organizationMemberFieldAccountID)
}

// SetEmail sets the Email field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (o *OrganizationMember) SetEmail(email *string) {
	o.Email = email
	o.require(organizationMemberFieldEmail)
}

// SetRole sets the Role field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (o *OrganizationMember) SetRole(role *OrganizationMemberRole) {
	o.Role = role
	o.require(organizationMemberFieldRole)
}

func (o *OrganizationMember) UnmarshalJSON(data []byte) error {
	type unmarshaler OrganizationMember
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*o = OrganizationMember(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *o)
	if err != nil {
		return err
	}
	o.extraProperties = extraProperties
	o.rawJSON = json.RawMessage(data)
	return nil
}

func (o *OrganizationMember) MarshalJSON() ([]byte, error) {
	type embed OrganizationMember
	var marshaler = struct {
		embed
	}{
		embed: embed(*o),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, o.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (o *OrganizationMember) String() string {
	if o == nil {
		return "<nil>"
	}
	if len(o.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(o.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(o); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", o)
}

type OrganizationMemberRole string

const (
	OrganizationMemberRoleOwner  OrganizationMemberRole = "owner"
	OrganizationMemberRoleAdmin  OrganizationMemberRole = "admin"
	OrganizationMemberRoleMember OrganizationMemberRole = "member"
	OrganizationMemberRoleReader OrganizationMemberRole = "reader"
)

func NewOrganizationMemberRoleFromString(s string) (OrganizationMemberRole, error) {
	switch s {
	case "owner":
		return OrganizationMemberRoleOwner, nil
	case "admin":
		return OrganizationMemberRoleAdmin, nil
	case "member":
		return OrganizationMemberRoleMember, nil
	case "reader":
		return OrganizationMemberRoleReader, nil
	}
	var t OrganizationMemberRole
	return "", fmt.Errorf("%s is not a valid %T", s, t)
}

func (o OrganizationMemberRole) Ptr() *OrganizationMemberRole {
	return &o
}

var (
	getOrganizationResponseFieldData      = big.NewInt(1 << 0)
	getOrganizationResponseFieldStatus    = big.NewInt(1 << 1)
	getOrganizationResponseFieldCode      = big.NewInt(1 << 2)
	getOrganizationResponseFieldMessage   = big.NewInt(1 << 3)
	getOrganizationResponseFieldTraceID   = big.NewInt(1 << 4)
	getOrganizationResponseFieldTimestamp = big.NewInt(1 << 5)
)

type GetOrganizationResponse struct {
	Data      *Organization  `json:"data,omitempty" url:"data,omitempty"`
	Status    EnvelopeStatus `json:"status" url:"status"`
	Code      string         `json:"code" url:"code"`
	Message   string         `json:"message" url:"message"`
	TraceID   string         `json:"trace_id" url:"trace_id"`
	Timestamp time.Time      `json:"timestamp" url:"timestamp"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (g *GetOrganizationResponse) GetData() *Organization {
	if g == nil {
		return nil
	}
	return g.Data
}

func (g *GetOrganizationResponse) GetStatus() EnvelopeStatus {
	if g == nil {
		return ""
	}
	return g.Status
}

func (g *GetOrganizationResponse) GetCode() string {
	if g == nil {
		return ""
	}
	return g.Code
}

func (g *GetOrganizationResponse) GetMessage() string {
	if g == nil {
		return ""
	}
	return g.Message
}

func (g *GetOrganizationResponse) GetTraceID() string {
	if g == nil {
		return ""
	}
	return g.TraceID
}

func (g *GetOrganizationResponse) GetTimestamp() time.Time {
	if g == nil {
		return time.Time{}
	}
	return g.Timestamp
}

func (g *GetOrganizationResponse) GetExtraProperties() map[string]interface{} {
	if g == nil {
		return nil
	}
	return g.extraProperties
}

func (g *GetOrganizationResponse) require(field *big.Int) {
	if g.explicitFields == nil {
		g.explicitFields = big.NewInt(0)
	}
	g.explicitFields.Or(g.explicitFields, field)
}

// SetData sets the Data field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GetOrganizationResponse) SetData(data *Organization) {
	g.Data = data
	g.require(getOrganizationResponseFieldData)
}

// SetStatus sets the Status field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GetOrganizationResponse) SetStatus(status EnvelopeStatus) {
	g.Status = status
	g.require(getOrganizationResponseFieldStatus)
}

// SetCode sets the Code field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GetOrganizationResponse) SetCode(code string) {
	g.Code = code
	g.require(getOrganizationResponseFieldCode)
}

// SetMessage sets the Message field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GetOrganizationResponse) SetMessage(message string) {
	g.Message = message
	g.require(getOrganizationResponseFieldMessage)
}

// SetTraceID sets the TraceID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GetOrganizationResponse) SetTraceID(traceID string) {
	g.TraceID = traceID
	g.require(getOrganizationResponseFieldTraceID)
}

// SetTimestamp sets the Timestamp field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GetOrganizationResponse) SetTimestamp(timestamp time.Time) {
	g.Timestamp = timestamp
	g.require(getOrganizationResponseFieldTimestamp)
}

func (g *GetOrganizationResponse) UnmarshalJSON(data []byte) error {
	type embed GetOrganizationResponse
	var unmarshaler = struct {
		embed
		Timestamp *internal.DateTime `json:"timestamp"`
	}{
		embed: embed(*g),
	}
	if err := json.Unmarshal(data, &unmarshaler); err != nil {
		return err
	}
	*g = GetOrganizationResponse(unmarshaler.embed)
	g.Timestamp = unmarshaler.Timestamp.Time()
	extraProperties, err := internal.ExtractExtraProperties(data, *g)
	if err != nil {
		return err
	}
	g.extraProperties = extraProperties
	g.rawJSON = json.RawMessage(data)
	return nil
}

func (g *GetOrganizationResponse) MarshalJSON() ([]byte, error) {
	type embed GetOrganizationResponse
	var marshaler = struct {
		embed
		Timestamp *internal.DateTime `json:"timestamp"`
	}{
		embed:     embed(*g),
		Timestamp: internal.NewDateTime(g.Timestamp),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, g.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (g *GetOrganizationResponse) String() string {
	if g == nil {
		return "<nil>"
	}
	if len(g.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(g.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(g); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", g)
}

var (
	listOrganizationMembersResponseFieldData      = big.NewInt(1 << 0)
	listOrganizationMembersResponseFieldStatus    = big.NewInt(1 << 1)
	listOrganizationMembersResponseFieldCode      = big.NewInt(1 << 2)
	listOrganizationMembersResponseFieldMessage   = big.NewInt(1 << 3)
	listOrganizationMembersResponseFieldTraceID   = big.NewInt(1 << 4)
	listOrganizationMembersResponseFieldTimestamp = big.NewInt(1 << 5)
)

type ListOrganizationMembersResponse struct {
	Data      []*OrganizationMember `json:"data,omitempty" url:"data,omitempty"`
	Status    EnvelopeStatus        `json:"status" url:"status"`
	Code      string                `json:"code" url:"code"`
	Message   string                `json:"message" url:"message"`
	TraceID   string                `json:"trace_id" url:"trace_id"`
	Timestamp time.Time             `json:"timestamp" url:"timestamp"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (l *ListOrganizationMembersResponse) GetData() []*OrganizationMember {
	if l == nil {
		return nil
	}
	return l.Data
}

func (l *ListOrganizationMembersResponse) GetStatus() EnvelopeStatus {
	if l == nil {
		return ""
	}
	return l.Status
}

func (l *ListOrganizationMembersResponse) GetCode() string {
	if l == nil {
		return ""
	}
	return l.Code
}

func (l *ListOrganizationMembersResponse) GetMessage() string {
	if l == nil {
		return ""
	}
	return l.Message
}

func (l *ListOrganizationMembersResponse) GetTraceID() string {
	if l == nil {
		return ""
	}
	return l.TraceID
}

func (l *ListOrganizationMembersResponse) GetTimestamp() time.Time {
	if l == nil {
		return time.Time{}
	}
	return l.Timestamp
}

func (l *ListOrganizationMembersResponse) GetExtraProperties() map[string]interface{} {
	if l == nil {
		return nil
	}
	return l.extraProperties
}

func (l *ListOrganizationMembersResponse) require(field *big.Int) {
	if l.explicitFields == nil {
		l.explicitFields = big.NewInt(0)
	}
	l.explicitFields.Or(l.explicitFields, field)
}

// SetData sets the Data field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *ListOrganizationMembersResponse) SetData(data []*OrganizationMember) {
	l.Data = data
	l.require(listOrganizationMembersResponseFieldData)
}

// SetStatus sets the Status field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *ListOrganizationMembersResponse) SetStatus(status EnvelopeStatus) {
	l.Status = status
	l.require(listOrganizationMembersResponseFieldStatus)
}

// SetCode sets the Code field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *ListOrganizationMembersResponse) SetCode(code string) {
	l.Code = code
	l.require(listOrganizationMembersResponseFieldCode)
}

// SetMessage sets the Message field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *ListOrganizationMembersResponse) SetMessage(message string) {
	l.Message = message
	l.require(listOrganizationMembersResponseFieldMessage)
}

// SetTraceID sets the TraceID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *ListOrganizationMembersResponse) SetTraceID(traceID string) {
	l.TraceID = traceID
	l.require(listOrganizationMembersResponseFieldTraceID)
}

// SetTimestamp sets the Timestamp field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *ListOrganizationMembersResponse) SetTimestamp(timestamp time.Time) {
	l.Timestamp = timestamp
	l.require(listOrganizationMembersResponseFieldTimestamp)
}

func (l *ListOrganizationMembersResponse) UnmarshalJSON(data []byte) error {
	type embed ListOrganizationMembersResponse
	var unmarshaler = struct {
		embed
		Timestamp *internal.DateTime `json:"timestamp"`
	}{
		embed: embed(*l),
	}
	if err := json.Unmarshal(data, &unmarshaler); err != nil {
		return err
	}
	*l = ListOrganizationMembersResponse(unmarshaler.embed)
	l.Timestamp = unmarshaler.Timestamp.Time()
	extraProperties, err := internal.ExtractExtraProperties(data, *l)
	if err != nil {
		return err
	}
	l.extraProperties = extraProperties
	l.rawJSON = json.RawMessage(data)
	return nil
}

func (l *ListOrganizationMembersResponse) MarshalJSON() ([]byte, error) {
	type embed ListOrganizationMembersResponse
	var marshaler = struct {
		embed
		Timestamp *internal.DateTime `json:"timestamp"`
	}{
		embed:     embed(*l),
		Timestamp: internal.NewDateTime(l.Timestamp),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, l.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (l *ListOrganizationMembersResponse) String() string {
	if l == nil {
		return "<nil>"
	}
	if len(l.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(l.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(l); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", l)
}
