// Code generated by Fern. DO NOT EDIT.

package gateway

import (
	context "context"

	dtgsdkgo "github.com/DTG-Corp/dtg-sdk-go"
	core "github.com/DTG-Corp/dtg-sdk-go/core"
	internal "github.com/DTG-Corp/dtg-sdk-go/internal"
	option "github.com/DTG-Corp/dtg-sdk-go/option"
)

type Client struct {
	WithRawResponse *RawClient

	options *core.RequestOptions
	baseURL string
	caller  *internal.Caller
}

func NewClient(options *core.RequestOptions) *Client {
	return &Client{
		WithRawResponse: NewRawClient(options),
		options:         options,
		baseURL:         options.BaseURL,
		caller: internal.NewCaller(
			&internal.CallerParams{
				Client:         options.HTTPClient,
				MaxAttempts:    options.MaxAttempts,
				DisableRetries: options.DisableRetries,
			},
		),
	}
}

// Example:
//
//	client.Gateway.ListModels(
//	    context.TODO(),
//	)
func (c *Client) ListModels(
	ctx context.Context,
	opts ...option.RequestOption,
) (*dtgsdkgo.ModelList, error) {
	response, err := c.WithRawResponse.ListModels(
		ctx,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

// Example:
//
//	request := &dtgsdkgo.ChatCompletionRequest{
//	    Model: "model",
//	    Messages: []*dtgsdkgo.ChatMessage{
//	        &dtgsdkgo.ChatMessage{
//	            Role: dtgsdkgo.ChatMessageRoleSystem,
//	            Content: "content",
//	        },
//	    },
//	}
//	client.Gateway.CreateChatCompletion(
//	    context.TODO(),
//	    request,
//	)
func (c *Client) CreateChatCompletion(
	ctx context.Context,
	request *dtgsdkgo.ChatCompletionRequest,
	opts ...option.RequestOption,
) (*dtgsdkgo.ChatCompletion, error) {
	response, err := c.WithRawResponse.CreateChatCompletion(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

// Example:
//
//	request := &dtgsdkgo.WebhookChatCompletionRequest{
//	    AgentID: "agent_id",
//	    Messages: []*dtgsdkgo.ChatMessage{
//	        &dtgsdkgo.ChatMessage{
//	            Role: dtgsdkgo.ChatMessageRoleSystem,
//	            Content: "content",
//	        },
//	    },
//	}
//	client.Gateway.CreateChatCompletionByAgentPath(
//	    context.TODO(),
//	    request,
//	)
func (c *Client) CreateChatCompletionByAgentPath(
	ctx context.Context,
	request *dtgsdkgo.WebhookChatCompletionRequest,
	opts ...option.RequestOption,
) (*dtgsdkgo.ChatCompletion, error) {
	response, err := c.WithRawResponse.CreateChatCompletionByAgentPath(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}
