// Code generated by Fern. DO NOT EDIT.

package apikeys

import (
	context "context"

	dtgsdkgo "github.com/DTG-Corp/dtg-sdk-go"
	core "github.com/DTG-Corp/dtg-sdk-go/core"
	internal "github.com/DTG-Corp/dtg-sdk-go/internal"
	option "github.com/DTG-Corp/dtg-sdk-go/option"
)

type Client struct {
	WithRawResponse *RawClient

	options *core.RequestOptions
	baseURL string
	caller  *internal.Caller
}

func NewClient(options *core.RequestOptions) *Client {
	return &Client{
		WithRawResponse: NewRawClient(options),
		options:         options,
		baseURL:         options.BaseURL,
		caller: internal.NewCaller(
			&internal.CallerParams{
				Client:         options.HTTPClient,
				MaxAttempts:    options.MaxAttempts,
				DisableRetries: options.DisableRetries,
			},
		),
	}
}

// Example:
//
//	client.APIKeys.ListAPIKeys(
//	    context.TODO(),
//	)
func (c *Client) ListAPIKeys(
	ctx context.Context,
	opts ...option.RequestOption,
) (*dtgsdkgo.ListAPIKeysResponse, error) {
	response, err := c.WithRawResponse.ListAPIKeys(
		ctx,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

// Example:
//
//	request := &dtgsdkgo.APIKeyCreateRequest{
//	    Name: "name",
//	}
//	client.APIKeys.CreateAPIKey(
//	    context.TODO(),
//	    request,
//	)
func (c *Client) CreateAPIKey(
	ctx context.Context,
	request *dtgsdkgo.APIKeyCreateRequest,
	opts ...option.RequestOption,
) (*dtgsdkgo.CreateAPIKeyResponse, error) {
	response, err := c.WithRawResponse.CreateAPIKey(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

// Example:
//
//	request := &dtgsdkgo.RevokeAPIKeyRequest{
//	    ID: "id",
//	}
//	client.APIKeys.RevokeAPIKey(
//	    context.TODO(),
//	    request,
//	)
func (c *Client) RevokeAPIKey(
	ctx context.Context,
	request *dtgsdkgo.RevokeAPIKeyRequest,
	opts ...option.RequestOption,
) (*dtgsdkgo.RevokeAPIKeyResponse, error) {
	response, err := c.WithRawResponse.RevokeAPIKey(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}
