// Code generated by Fern. DO NOT EDIT.

package apikeys

import (
	context "context"
	http "net/http"

	dtgagentsdk "github.com/DTG-Corp/dtg-agent-sdk"
	core "github.com/DTG-Corp/dtg-agent-sdk/core"
	internal "github.com/DTG-Corp/dtg-agent-sdk/internal"
	option "github.com/DTG-Corp/dtg-agent-sdk/option"
)

type RawClient struct {
	baseURL string
	caller  *internal.Caller
	options *core.RequestOptions
}

func NewRawClient(options *core.RequestOptions) *RawClient {
	return &RawClient{
		options: options,
		baseURL: options.BaseURL,
		caller: internal.NewCaller(
			&internal.CallerParams{
				Client:         options.HTTPClient,
				MaxAttempts:    options.MaxAttempts,
				DisableRetries: options.DisableRetries,
			},
		),
	}
}

func (r *RawClient) ListAPIKeys(
	ctx context.Context,
	opts ...option.RequestOption,
) (*core.Response[*dtgagentsdk.ListAPIKeysResponse], error) {
	options := core.NewRequestOptions(opts...)
	baseURL := internal.ResolveBaseURL(
		options.BaseURL,
		r.baseURL,
		"https://api.like.ai.vn",
	)
	endpointURL := baseURL + "/api/v1/api-keys"
	headers := internal.MergeHeaders(
		r.options.ToHeader(),
		options.ToHeader(),
	)
	var response *dtgagentsdk.ListAPIKeysResponse
	raw, err := r.caller.Call(
		ctx,
		&internal.CallParams{
			URL:             endpointURL,
			Method:          http.MethodGet,
			Headers:         headers,
			MaxAttempts:     options.MaxAttempts,
			DisableRetries:  options.DisableRetries,
			BodyProperties:  options.BodyProperties,
			QueryParameters: options.QueryParameters,
			Client:          options.HTTPClient,
			Response:        &response,
		},
	)
	if err != nil {
		return nil, err
	}
	return &core.Response[*dtgagentsdk.ListAPIKeysResponse]{
		StatusCode: raw.StatusCode,
		Header:     raw.Header,
		Body:       response,
	}, nil
}

func (r *RawClient) CreateAPIKey(
	ctx context.Context,
	request *dtgagentsdk.APIKeyCreateRequest,
	opts ...option.RequestOption,
) (*core.Response[*dtgagentsdk.CreateAPIKeyResponse], error) {
	options := core.NewRequestOptions(opts...)
	baseURL := internal.ResolveBaseURL(
		options.BaseURL,
		r.baseURL,
		"https://api.like.ai.vn",
	)
	endpointURL := baseURL + "/api/v1/api-keys"
	headers := internal.MergeHeaders(
		r.options.ToHeader(),
		options.ToHeader(),
	)
	if request.IdempotencyKey != nil {
		headers.Add("Idempotency-Key", *request.IdempotencyKey)
	}
	headers.Add("Content-Type", "application/json")
	var response *dtgagentsdk.CreateAPIKeyResponse
	raw, err := r.caller.Call(
		ctx,
		&internal.CallParams{
			URL:             endpointURL,
			Method:          http.MethodPost,
			Headers:         headers,
			MaxAttempts:     options.MaxAttempts,
			DisableRetries:  options.DisableRetries,
			BodyProperties:  options.BodyProperties,
			QueryParameters: options.QueryParameters,
			Client:          options.HTTPClient,
			Request:         request,
			Response:        &response,
		},
	)
	if err != nil {
		return nil, err
	}
	return &core.Response[*dtgagentsdk.CreateAPIKeyResponse]{
		StatusCode: raw.StatusCode,
		Header:     raw.Header,
		Body:       response,
	}, nil
}

func (r *RawClient) RevokeAPIKey(
	ctx context.Context,
	request *dtgagentsdk.RevokeAPIKeyRequest,
	opts ...option.RequestOption,
) (*core.Response[*dtgagentsdk.RevokeAPIKeyResponse], error) {
	options := core.NewRequestOptions(opts...)
	baseURL := internal.ResolveBaseURL(
		options.BaseURL,
		r.baseURL,
		"https://api.like.ai.vn",
	)
	endpointURL := internal.EncodeURL(
		baseURL+"/api/v1/api-keys/%v",
		request.ID,
	)
	headers := internal.MergeHeaders(
		r.options.ToHeader(),
		options.ToHeader(),
	)
	if request.IdempotencyKey != nil {
		headers.Add("Idempotency-Key", *request.IdempotencyKey)
	}

	var response *dtgagentsdk.RevokeAPIKeyResponse
	raw, err := r.caller.Call(
		ctx,
		&internal.CallParams{
			URL:             endpointURL,
			Method:          http.MethodDelete,
			Headers:         headers,
			MaxAttempts:     options.MaxAttempts,
			DisableRetries:  options.DisableRetries,
			BodyProperties:  options.BodyProperties,
			QueryParameters: options.QueryParameters,
			Client:          options.HTTPClient,
			Response:        &response,
			ErrorDecoder:    internal.NewErrorDecoder(dtgagentsdk.ErrorCodes),
		},
	)
	if err != nil {
		return nil, err
	}
	return &core.Response[*dtgagentsdk.RevokeAPIKeyResponse]{
		StatusCode: raw.StatusCode,
		Header:     raw.Header,
		Body:       response,
	}, nil
}
