// Code generated by Fern. DO NOT EDIT.

package mcpservers

import (
	context "context"
	http "net/http"

	dtgagentsdk "github.com/DTG-Corp/dtg-agent-sdk"
	core "github.com/DTG-Corp/dtg-agent-sdk/core"
	internal "github.com/DTG-Corp/dtg-agent-sdk/internal"
	option "github.com/DTG-Corp/dtg-agent-sdk/option"
)

type RawClient struct {
	baseURL string
	caller  *internal.Caller
	options *core.RequestOptions
}

func NewRawClient(options *core.RequestOptions) *RawClient {
	return &RawClient{
		options: options,
		baseURL: options.BaseURL,
		caller: internal.NewCaller(
			&internal.CallerParams{
				Client:         options.HTTPClient,
				MaxAttempts:    options.MaxAttempts,
				DisableRetries: options.DisableRetries,
			},
		),
	}
}

func (r *RawClient) ListMcpServers(
	ctx context.Context,
	opts ...option.RequestOption,
) (*core.Response[*dtgagentsdk.ListMcpServersResponse], error) {
	options := core.NewRequestOptions(opts...)
	baseURL := internal.ResolveBaseURL(
		options.BaseURL,
		r.baseURL,
		"https://agents.dtgsoft.vn",
	)
	endpointURL := baseURL + "/api/v1/mcp-servers"
	headers := internal.MergeHeaders(
		r.options.ToHeader(),
		options.ToHeader(),
	)
	var response *dtgagentsdk.ListMcpServersResponse
	raw, err := r.caller.Call(
		ctx,
		&internal.CallParams{
			URL:             endpointURL,
			Method:          http.MethodGet,
			Headers:         headers,
			MaxAttempts:     options.MaxAttempts,
			DisableRetries:  options.DisableRetries,
			BodyProperties:  options.BodyProperties,
			QueryParameters: options.QueryParameters,
			Client:          options.HTTPClient,
			Response:        &response,
		},
	)
	if err != nil {
		return nil, err
	}
	return &core.Response[*dtgagentsdk.ListMcpServersResponse]{
		StatusCode: raw.StatusCode,
		Header:     raw.Header,
		Body:       response,
	}, nil
}

func (r *RawClient) CreateMcpServer(
	ctx context.Context,
	request *dtgagentsdk.McpServerCreateRequest,
	opts ...option.RequestOption,
) (*core.Response[*dtgagentsdk.CreateMcpServerResponse], error) {
	options := core.NewRequestOptions(opts...)
	baseURL := internal.ResolveBaseURL(
		options.BaseURL,
		r.baseURL,
		"https://agents.dtgsoft.vn",
	)
	endpointURL := baseURL + "/api/v1/mcp-servers"
	headers := internal.MergeHeaders(
		r.options.ToHeader(),
		options.ToHeader(),
	)
	if request.IdempotencyKey != nil {
		headers.Add("Idempotency-Key", *request.IdempotencyKey)
	}
	headers.Add("Content-Type", "application/json")
	var response *dtgagentsdk.CreateMcpServerResponse
	raw, err := r.caller.Call(
		ctx,
		&internal.CallParams{
			URL:             endpointURL,
			Method:          http.MethodPost,
			Headers:         headers,
			MaxAttempts:     options.MaxAttempts,
			DisableRetries:  options.DisableRetries,
			BodyProperties:  options.BodyProperties,
			QueryParameters: options.QueryParameters,
			Client:          options.HTTPClient,
			Request:         request,
			Response:        &response,
		},
	)
	if err != nil {
		return nil, err
	}
	return &core.Response[*dtgagentsdk.CreateMcpServerResponse]{
		StatusCode: raw.StatusCode,
		Header:     raw.Header,
		Body:       response,
	}, nil
}

func (r *RawClient) ListMcpServerTools(
	ctx context.Context,
	request *dtgagentsdk.ListMcpServerToolsRequest,
	opts ...option.RequestOption,
) (*core.Response[*dtgagentsdk.ListMcpServerToolsResponse], error) {
	options := core.NewRequestOptions(opts...)
	baseURL := internal.ResolveBaseURL(
		options.BaseURL,
		r.baseURL,
		"https://agents.dtgsoft.vn",
	)
	endpointURL := internal.EncodeURL(
		baseURL+"/api/v1/mcp-servers/%v/tools",
		request.ID,
	)
	headers := internal.MergeHeaders(
		r.options.ToHeader(),
		options.ToHeader(),
	)
	var response *dtgagentsdk.ListMcpServerToolsResponse
	raw, err := r.caller.Call(
		ctx,
		&internal.CallParams{
			URL:             endpointURL,
			Method:          http.MethodGet,
			Headers:         headers,
			MaxAttempts:     options.MaxAttempts,
			DisableRetries:  options.DisableRetries,
			BodyProperties:  options.BodyProperties,
			QueryParameters: options.QueryParameters,
			Client:          options.HTTPClient,
			Response:        &response,
		},
	)
	if err != nil {
		return nil, err
	}
	return &core.Response[*dtgagentsdk.ListMcpServerToolsResponse]{
		StatusCode: raw.StatusCode,
		Header:     raw.Header,
		Body:       response,
	}, nil
}

func (r *RawClient) CreateMcpServerTool(
	ctx context.Context,
	request *dtgagentsdk.CreateMcpServerToolRequest,
	opts ...option.RequestOption,
) (*core.Response[*dtgagentsdk.CreateMcpServerToolResponse], error) {
	options := core.NewRequestOptions(opts...)
	baseURL := internal.ResolveBaseURL(
		options.BaseURL,
		r.baseURL,
		"https://agents.dtgsoft.vn",
	)
	endpointURL := internal.EncodeURL(
		baseURL+"/api/v1/mcp-servers/%v/tools",
		request.ID,
	)
	headers := internal.MergeHeaders(
		r.options.ToHeader(),
		options.ToHeader(),
	)
	if request.IdempotencyKey != nil {
		headers.Add("Idempotency-Key", *request.IdempotencyKey)
	}
	headers.Add("Content-Type", "application/json")
	var response *dtgagentsdk.CreateMcpServerToolResponse
	raw, err := r.caller.Call(
		ctx,
		&internal.CallParams{
			URL:             endpointURL,
			Method:          http.MethodPost,
			Headers:         headers,
			MaxAttempts:     options.MaxAttempts,
			DisableRetries:  options.DisableRetries,
			BodyProperties:  options.BodyProperties,
			QueryParameters: options.QueryParameters,
			Client:          options.HTTPClient,
			Request:         request,
			Response:        &response,
		},
	)
	if err != nil {
		return nil, err
	}
	return &core.Response[*dtgagentsdk.CreateMcpServerToolResponse]{
		StatusCode: raw.StatusCode,
		Header:     raw.Header,
		Body:       response,
	}, nil
}
