// Code generated by Fern. DO NOT EDIT.

package knowledge

import (
	context "context"

	dtgsdkgo "github.com/DTG-Corp/dtg-sdk-go"
	core "github.com/DTG-Corp/dtg-sdk-go/core"
	internal "github.com/DTG-Corp/dtg-sdk-go/internal"
	option "github.com/DTG-Corp/dtg-sdk-go/option"
)

type Client struct {
	WithRawResponse *RawClient

	options *core.RequestOptions
	baseURL string
	caller  *internal.Caller
}

func NewClient(options *core.RequestOptions) *Client {
	return &Client{
		WithRawResponse: NewRawClient(options),
		options:         options,
		baseURL:         options.BaseURL,
		caller: internal.NewCaller(
			&internal.CallerParams{
				Client:         options.HTTPClient,
				MaxAttempts:    options.MaxAttempts,
				DisableRetries: options.DisableRetries,
			},
		),
	}
}

// Example:
//
//	client.Knowledge.ListKnowledge(
//	    context.TODO(),
//	)
func (c *Client) ListKnowledge(
	ctx context.Context,
	opts ...option.RequestOption,
) (*dtgsdkgo.ListKnowledgeResponse, error) {
	response, err := c.WithRawResponse.ListKnowledge(
		ctx,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

// Example:
//
//	request := &dtgsdkgo.KnowledgeCreateRequest{
//	    Title: "title",
//	    Content: "content",
//	}
//	client.Knowledge.CreateKnowledge(
//	    context.TODO(),
//	    request,
//	)
func (c *Client) CreateKnowledge(
	ctx context.Context,
	request *dtgsdkgo.KnowledgeCreateRequest,
	opts ...option.RequestOption,
) (*dtgsdkgo.CreateKnowledgeResponse, error) {
	response, err := c.WithRawResponse.CreateKnowledge(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

// Example:
//
//	request := &dtgsdkgo.GetKnowledgeRequest{
//	    ID: "id",
//	}
//	client.Knowledge.GetKnowledge(
//	    context.TODO(),
//	    request,
//	)
func (c *Client) GetKnowledge(
	ctx context.Context,
	request *dtgsdkgo.GetKnowledgeRequest,
	opts ...option.RequestOption,
) (*dtgsdkgo.GetKnowledgeResponse, error) {
	response, err := c.WithRawResponse.GetKnowledge(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

// Example:
//
//	request := &dtgsdkgo.DeleteKnowledgeRequest{
//	    ID: "id",
//	}
//	client.Knowledge.DeleteKnowledge(
//	    context.TODO(),
//	    request,
//	)
func (c *Client) DeleteKnowledge(
	ctx context.Context,
	request *dtgsdkgo.DeleteKnowledgeRequest,
	opts ...option.RequestOption,
) (*dtgsdkgo.DeleteKnowledgeResponse, error) {
	response, err := c.WithRawResponse.DeleteKnowledge(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}
