// Code generated by Fern. DO NOT EDIT.

package agents_test

import (
	bytes "bytes"
	context "context"
	json "encoding/json"
	http "net/http"
	os "os"
	testing "testing"

	dtgagentsdk "github.com/DTG-Corp/dtg-agent-sdk"
	client "github.com/DTG-Corp/dtg-agent-sdk/client"
	option "github.com/DTG-Corp/dtg-agent-sdk/option"
	require "github.com/stretchr/testify/require"
)

func VerifyRequestCount(
	t *testing.T,
	testId string,
	method string,
	urlPath string,
	queryParams map[string]any,
	expected int,
) {
	wiremockURL := os.Getenv("WIREMOCK_URL")
	if wiremockURL == "" {
		wiremockURL = "http://localhost:8080"
	}
	WiremockAdminURL := wiremockURL + "/__admin"
	var reqBody bytes.Buffer
	reqBody.WriteString(`{"method":"`)
	reqBody.WriteString(method)
	reqBody.WriteString(`","urlPath":"`)
	reqBody.WriteString(urlPath)
	reqBody.WriteString(`","headers":{"X-Test-Id":{"equalTo":"`)
	reqBody.WriteString(testId)
	reqBody.WriteString(`"}}`)
	if len(queryParams) > 0 {
		reqBody.WriteString(`,"queryParameters":{`)
		first := true
		for key, value := range queryParams {
			if !first {
				reqBody.WriteString(",")
			}
			reqBody.WriteString(`"`)
			reqBody.WriteString(key)
			switch v := value.(type) {
			case string:
				reqBody.WriteString(`":{"equalTo":"`)
				reqBody.WriteString(v)
				reqBody.WriteString(`"}`)
			case []string:
				reqBody.WriteString(`":{"hasExactly":[`)
				for i, item := range v {
					if i > 0 {
						reqBody.WriteString(",")
					}
					reqBody.WriteString(`{"equalTo":"`)
					reqBody.WriteString(item)
					reqBody.WriteString(`"}`)
				}
				reqBody.WriteString(`]}`)
			}
			first = false
		}
		reqBody.WriteString("}")
	}
	reqBody.WriteString("}")
	resp, err := http.Post(WiremockAdminURL+"/requests/find", "application/json", &reqBody)
	require.NoError(t, err)
	var result struct {
		Requests []interface{} `json:"requests"`
	}
	json.NewDecoder(resp.Body).Decode(&result)
	require.Equal(t, expected, len(result.Requests))
}

func TestAgentsListAgentsWithWireMock(
	t *testing.T,
) {
	WireMockBaseURL := os.Getenv("WIREMOCK_URL")
	if WireMockBaseURL == "" {
		WireMockBaseURL = "http://localhost:8080"
	}
	client := client.NewClient(
		option.WithBaseURL(WireMockBaseURL),
		option.WithToken("test-token"),
	)
	_, invocationErr := client.Agents.ListAgents(
		context.TODO(),
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestAgentsListAgentsWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestAgentsListAgentsWithWireMock", "GET", "/api/v1/agents", nil, 1)
}

func TestAgentsCreateAgentWithWireMock(
	t *testing.T,
) {
	WireMockBaseURL := os.Getenv("WIREMOCK_URL")
	if WireMockBaseURL == "" {
		WireMockBaseURL = "http://localhost:8080"
	}
	client := client.NewClient(
		option.WithBaseURL(WireMockBaseURL),
		option.WithToken("test-token"),
	)
	request := &dtgagentsdk.AgentCreateRequest{
		DisplayName: "display_name",
	}
	_, invocationErr := client.Agents.CreateAgent(
		context.TODO(),
		request,
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestAgentsCreateAgentWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestAgentsCreateAgentWithWireMock", "POST", "/api/v1/agents", nil, 1)
}

func TestAgentsGetAgentWithWireMock(
	t *testing.T,
) {
	WireMockBaseURL := os.Getenv("WIREMOCK_URL")
	if WireMockBaseURL == "" {
		WireMockBaseURL = "http://localhost:8080"
	}
	client := client.NewClient(
		option.WithBaseURL(WireMockBaseURL),
		option.WithToken("test-token"),
	)
	request := &dtgagentsdk.GetAgentRequest{
		ID: "id",
	}
	_, invocationErr := client.Agents.GetAgent(
		context.TODO(),
		request,
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestAgentsGetAgentWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestAgentsGetAgentWithWireMock", "GET", "/api/v1/agents/id", nil, 1)
}

func TestAgentsDeleteAgentWithWireMock(
	t *testing.T,
) {
	WireMockBaseURL := os.Getenv("WIREMOCK_URL")
	if WireMockBaseURL == "" {
		WireMockBaseURL = "http://localhost:8080"
	}
	client := client.NewClient(
		option.WithBaseURL(WireMockBaseURL),
		option.WithToken("test-token"),
	)
	request := &dtgagentsdk.DeleteAgentRequest{
		ID: "id",
	}
	_, invocationErr := client.Agents.DeleteAgent(
		context.TODO(),
		request,
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestAgentsDeleteAgentWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestAgentsDeleteAgentWithWireMock", "DELETE", "/api/v1/agents/id", nil, 1)
}

func TestAgentsUpdateAgentWithWireMock(
	t *testing.T,
) {
	WireMockBaseURL := os.Getenv("WIREMOCK_URL")
	if WireMockBaseURL == "" {
		WireMockBaseURL = "http://localhost:8080"
	}
	client := client.NewClient(
		option.WithBaseURL(WireMockBaseURL),
		option.WithToken("test-token"),
	)
	request := &dtgagentsdk.AgentUpdateRequest{
		ID: "id",
	}
	_, invocationErr := client.Agents.UpdateAgent(
		context.TODO(),
		request,
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestAgentsUpdateAgentWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestAgentsUpdateAgentWithWireMock", "PATCH", "/api/v1/agents/id", nil, 1)
}

func TestAgentsStartAgentWithWireMock(
	t *testing.T,
) {
	WireMockBaseURL := os.Getenv("WIREMOCK_URL")
	if WireMockBaseURL == "" {
		WireMockBaseURL = "http://localhost:8080"
	}
	client := client.NewClient(
		option.WithBaseURL(WireMockBaseURL),
		option.WithToken("test-token"),
	)
	request := &dtgagentsdk.StartAgentRequest{
		ID: "id",
	}
	_, invocationErr := client.Agents.StartAgent(
		context.TODO(),
		request,
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestAgentsStartAgentWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestAgentsStartAgentWithWireMock", "POST", "/api/v1/agents/id/start", nil, 1)
}

func TestAgentsStopAgentWithWireMock(
	t *testing.T,
) {
	WireMockBaseURL := os.Getenv("WIREMOCK_URL")
	if WireMockBaseURL == "" {
		WireMockBaseURL = "http://localhost:8080"
	}
	client := client.NewClient(
		option.WithBaseURL(WireMockBaseURL),
		option.WithToken("test-token"),
	)
	request := &dtgagentsdk.StopAgentRequest{
		ID: "id",
	}
	_, invocationErr := client.Agents.StopAgent(
		context.TODO(),
		request,
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestAgentsStopAgentWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestAgentsStopAgentWithWireMock", "POST", "/api/v1/agents/id/stop", nil, 1)
}

func TestAgentsGetAgentChannelsWithWireMock(
	t *testing.T,
) {
	WireMockBaseURL := os.Getenv("WIREMOCK_URL")
	if WireMockBaseURL == "" {
		WireMockBaseURL = "http://localhost:8080"
	}
	client := client.NewClient(
		option.WithBaseURL(WireMockBaseURL),
		option.WithToken("test-token"),
	)
	request := &dtgagentsdk.GetAgentChannelsRequest{
		ID: "id",
	}
	_, invocationErr := client.Agents.GetAgentChannels(
		context.TODO(),
		request,
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestAgentsGetAgentChannelsWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestAgentsGetAgentChannelsWithWireMock", "GET", "/api/v1/agents/id/channels", nil, 1)
}

func TestAgentsUpdateAgentChannelsWithWireMock(
	t *testing.T,
) {
	WireMockBaseURL := os.Getenv("WIREMOCK_URL")
	if WireMockBaseURL == "" {
		WireMockBaseURL = "http://localhost:8080"
	}
	client := client.NewClient(
		option.WithBaseURL(WireMockBaseURL),
		option.WithToken("test-token"),
	)
	request := &dtgagentsdk.UpdateAgentChannelsRequest{
		ID: "id",
	}
	_, invocationErr := client.Agents.UpdateAgentChannels(
		context.TODO(),
		request,
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestAgentsUpdateAgentChannelsWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestAgentsUpdateAgentChannelsWithWireMock", "PUT", "/api/v1/agents/id/channels", nil, 1)
}

func TestAgentsListAgentModelsWithWireMock(
	t *testing.T,
) {
	WireMockBaseURL := os.Getenv("WIREMOCK_URL")
	if WireMockBaseURL == "" {
		WireMockBaseURL = "http://localhost:8080"
	}
	client := client.NewClient(
		option.WithBaseURL(WireMockBaseURL),
		option.WithToken("test-token"),
	)
	_, invocationErr := client.Agents.ListAgentModels(
		context.TODO(),
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestAgentsListAgentModelsWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestAgentsListAgentModelsWithWireMock", "GET", "/api/v1/models", nil, 1)
}
