// Code generated by Fern. DO NOT EDIT.

package agents

import (
	context "context"
	http "net/http"

	dtgsdkgo "github.com/DTG-Corp/dtg-sdk-go"
	core "github.com/DTG-Corp/dtg-sdk-go/core"
	internal "github.com/DTG-Corp/dtg-sdk-go/internal"
	option "github.com/DTG-Corp/dtg-sdk-go/option"
)

type RawClient struct {
	baseURL string
	caller  *internal.Caller
	options *core.RequestOptions
}

func NewRawClient(options *core.RequestOptions) *RawClient {
	return &RawClient{
		options: options,
		baseURL: options.BaseURL,
		caller: internal.NewCaller(
			&internal.CallerParams{
				Client:         options.HTTPClient,
				MaxAttempts:    options.MaxAttempts,
				DisableRetries: options.DisableRetries,
			},
		),
	}
}

func (r *RawClient) ListAgents(
	ctx context.Context,
	opts ...option.RequestOption,
) (*core.Response[*dtgsdkgo.ListAgentsResponse], error) {
	options := core.NewRequestOptions(opts...)
	baseURL := internal.ResolveBaseURL(
		options.BaseURL,
		r.baseURL,
		"https://api.like.ai.vn",
	)
	endpointURL := baseURL + "/api/v1/agents"
	headers := internal.MergeHeaders(
		r.options.ToHeader(),
		options.ToHeader(),
	)
	var response *dtgsdkgo.ListAgentsResponse
	raw, err := r.caller.Call(
		ctx,
		&internal.CallParams{
			URL:             endpointURL,
			Method:          http.MethodGet,
			Headers:         headers,
			MaxAttempts:     options.MaxAttempts,
			DisableRetries:  options.DisableRetries,
			BodyProperties:  options.BodyProperties,
			QueryParameters: options.QueryParameters,
			Client:          options.HTTPClient,
			Response:        &response,
			ErrorDecoder:    internal.NewErrorDecoder(dtgsdkgo.ErrorCodes),
		},
	)
	if err != nil {
		return nil, err
	}
	return &core.Response[*dtgsdkgo.ListAgentsResponse]{
		StatusCode: raw.StatusCode,
		Header:     raw.Header,
		Body:       response,
	}, nil
}

func (r *RawClient) CreateAgent(
	ctx context.Context,
	request *dtgsdkgo.AgentCreateRequest,
	opts ...option.RequestOption,
) (*core.Response[*dtgsdkgo.CreateAgentResponse], error) {
	options := core.NewRequestOptions(opts...)
	baseURL := internal.ResolveBaseURL(
		options.BaseURL,
		r.baseURL,
		"https://api.like.ai.vn",
	)
	endpointURL := baseURL + "/api/v1/agents"
	headers := internal.MergeHeaders(
		r.options.ToHeader(),
		options.ToHeader(),
	)
	if request.IdempotencyKey != nil {
		headers.Add("Idempotency-Key", *request.IdempotencyKey)
	}
	headers.Add("Content-Type", "application/json")
	var response *dtgsdkgo.CreateAgentResponse
	raw, err := r.caller.Call(
		ctx,
		&internal.CallParams{
			URL:             endpointURL,
			Method:          http.MethodPost,
			Headers:         headers,
			MaxAttempts:     options.MaxAttempts,
			DisableRetries:  options.DisableRetries,
			BodyProperties:  options.BodyProperties,
			QueryParameters: options.QueryParameters,
			Client:          options.HTTPClient,
			Request:         request,
			Response:        &response,
			ErrorDecoder:    internal.NewErrorDecoder(dtgsdkgo.ErrorCodes),
		},
	)
	if err != nil {
		return nil, err
	}
	return &core.Response[*dtgsdkgo.CreateAgentResponse]{
		StatusCode: raw.StatusCode,
		Header:     raw.Header,
		Body:       response,
	}, nil
}

func (r *RawClient) GetAgent(
	ctx context.Context,
	request *dtgsdkgo.GetAgentRequest,
	opts ...option.RequestOption,
) (*core.Response[*dtgsdkgo.GetAgentResponse], error) {
	options := core.NewRequestOptions(opts...)
	baseURL := internal.ResolveBaseURL(
		options.BaseURL,
		r.baseURL,
		"https://api.like.ai.vn",
	)
	endpointURL := internal.EncodeURL(
		baseURL+"/api/v1/agents/%v",
		request.ID,
	)
	headers := internal.MergeHeaders(
		r.options.ToHeader(),
		options.ToHeader(),
	)
	var response *dtgsdkgo.GetAgentResponse
	raw, err := r.caller.Call(
		ctx,
		&internal.CallParams{
			URL:             endpointURL,
			Method:          http.MethodGet,
			Headers:         headers,
			MaxAttempts:     options.MaxAttempts,
			DisableRetries:  options.DisableRetries,
			BodyProperties:  options.BodyProperties,
			QueryParameters: options.QueryParameters,
			Client:          options.HTTPClient,
			Response:        &response,
			ErrorDecoder:    internal.NewErrorDecoder(dtgsdkgo.ErrorCodes),
		},
	)
	if err != nil {
		return nil, err
	}
	return &core.Response[*dtgsdkgo.GetAgentResponse]{
		StatusCode: raw.StatusCode,
		Header:     raw.Header,
		Body:       response,
	}, nil
}

func (r *RawClient) DeleteAgent(
	ctx context.Context,
	request *dtgsdkgo.DeleteAgentRequest,
	opts ...option.RequestOption,
) (*core.Response[*dtgsdkgo.DeleteAgentResponse], error) {
	options := core.NewRequestOptions(opts...)
	baseURL := internal.ResolveBaseURL(
		options.BaseURL,
		r.baseURL,
		"https://api.like.ai.vn",
	)
	endpointURL := internal.EncodeURL(
		baseURL+"/api/v1/agents/%v",
		request.ID,
	)
	headers := internal.MergeHeaders(
		r.options.ToHeader(),
		options.ToHeader(),
	)
	if request.IdempotencyKey != nil {
		headers.Add("Idempotency-Key", *request.IdempotencyKey)
	}

	var response *dtgsdkgo.DeleteAgentResponse
	raw, err := r.caller.Call(
		ctx,
		&internal.CallParams{
			URL:             endpointURL,
			Method:          http.MethodDelete,
			Headers:         headers,
			MaxAttempts:     options.MaxAttempts,
			DisableRetries:  options.DisableRetries,
			BodyProperties:  options.BodyProperties,
			QueryParameters: options.QueryParameters,
			Client:          options.HTTPClient,
			Response:        &response,
			ErrorDecoder:    internal.NewErrorDecoder(dtgsdkgo.ErrorCodes),
		},
	)
	if err != nil {
		return nil, err
	}
	return &core.Response[*dtgsdkgo.DeleteAgentResponse]{
		StatusCode: raw.StatusCode,
		Header:     raw.Header,
		Body:       response,
	}, nil
}

func (r *RawClient) UpdateAgent(
	ctx context.Context,
	request *dtgsdkgo.AgentUpdateRequest,
	opts ...option.RequestOption,
) (*core.Response[*dtgsdkgo.UpdateAgentResponse], error) {
	options := core.NewRequestOptions(opts...)
	baseURL := internal.ResolveBaseURL(
		options.BaseURL,
		r.baseURL,
		"https://api.like.ai.vn",
	)
	endpointURL := internal.EncodeURL(
		baseURL+"/api/v1/agents/%v",
		request.ID,
	)
	headers := internal.MergeHeaders(
		r.options.ToHeader(),
		options.ToHeader(),
	)
	if request.IdempotencyKey != nil {
		headers.Add("Idempotency-Key", *request.IdempotencyKey)
	}
	headers.Add("Content-Type", "application/json")
	var response *dtgsdkgo.UpdateAgentResponse
	raw, err := r.caller.Call(
		ctx,
		&internal.CallParams{
			URL:             endpointURL,
			Method:          http.MethodPatch,
			Headers:         headers,
			MaxAttempts:     options.MaxAttempts,
			DisableRetries:  options.DisableRetries,
			BodyProperties:  options.BodyProperties,
			QueryParameters: options.QueryParameters,
			Client:          options.HTTPClient,
			Request:         request,
			Response:        &response,
			ErrorDecoder:    internal.NewErrorDecoder(dtgsdkgo.ErrorCodes),
		},
	)
	if err != nil {
		return nil, err
	}
	return &core.Response[*dtgsdkgo.UpdateAgentResponse]{
		StatusCode: raw.StatusCode,
		Header:     raw.Header,
		Body:       response,
	}, nil
}

func (r *RawClient) StartAgent(
	ctx context.Context,
	request *dtgsdkgo.StartAgentRequest,
	opts ...option.RequestOption,
) (*core.Response[*dtgsdkgo.StartAgentResponse], error) {
	options := core.NewRequestOptions(opts...)
	baseURL := internal.ResolveBaseURL(
		options.BaseURL,
		r.baseURL,
		"https://api.like.ai.vn",
	)
	endpointURL := internal.EncodeURL(
		baseURL+"/api/v1/agents/%v/start",
		request.ID,
	)
	headers := internal.MergeHeaders(
		r.options.ToHeader(),
		options.ToHeader(),
	)
	if request.IdempotencyKey != nil {
		headers.Add("Idempotency-Key", *request.IdempotencyKey)
	}

	var response *dtgsdkgo.StartAgentResponse
	raw, err := r.caller.Call(
		ctx,
		&internal.CallParams{
			URL:             endpointURL,
			Method:          http.MethodPost,
			Headers:         headers,
			MaxAttempts:     options.MaxAttempts,
			DisableRetries:  options.DisableRetries,
			BodyProperties:  options.BodyProperties,
			QueryParameters: options.QueryParameters,
			Client:          options.HTTPClient,
			Response:        &response,
		},
	)
	if err != nil {
		return nil, err
	}
	return &core.Response[*dtgsdkgo.StartAgentResponse]{
		StatusCode: raw.StatusCode,
		Header:     raw.Header,
		Body:       response,
	}, nil
}

func (r *RawClient) StopAgent(
	ctx context.Context,
	request *dtgsdkgo.StopAgentRequest,
	opts ...option.RequestOption,
) (*core.Response[*dtgsdkgo.StopAgentResponse], error) {
	options := core.NewRequestOptions(opts...)
	baseURL := internal.ResolveBaseURL(
		options.BaseURL,
		r.baseURL,
		"https://api.like.ai.vn",
	)
	endpointURL := internal.EncodeURL(
		baseURL+"/api/v1/agents/%v/stop",
		request.ID,
	)
	headers := internal.MergeHeaders(
		r.options.ToHeader(),
		options.ToHeader(),
	)
	if request.IdempotencyKey != nil {
		headers.Add("Idempotency-Key", *request.IdempotencyKey)
	}

	var response *dtgsdkgo.StopAgentResponse
	raw, err := r.caller.Call(
		ctx,
		&internal.CallParams{
			URL:             endpointURL,
			Method:          http.MethodPost,
			Headers:         headers,
			MaxAttempts:     options.MaxAttempts,
			DisableRetries:  options.DisableRetries,
			BodyProperties:  options.BodyProperties,
			QueryParameters: options.QueryParameters,
			Client:          options.HTTPClient,
			Response:        &response,
		},
	)
	if err != nil {
		return nil, err
	}
	return &core.Response[*dtgsdkgo.StopAgentResponse]{
		StatusCode: raw.StatusCode,
		Header:     raw.Header,
		Body:       response,
	}, nil
}

func (r *RawClient) GetAgentChannels(
	ctx context.Context,
	request *dtgsdkgo.GetAgentChannelsRequest,
	opts ...option.RequestOption,
) (*core.Response[*dtgsdkgo.GetAgentChannelsResponse], error) {
	options := core.NewRequestOptions(opts...)
	baseURL := internal.ResolveBaseURL(
		options.BaseURL,
		r.baseURL,
		"https://api.like.ai.vn",
	)
	endpointURL := internal.EncodeURL(
		baseURL+"/api/v1/agents/%v/channels",
		request.ID,
	)
	headers := internal.MergeHeaders(
		r.options.ToHeader(),
		options.ToHeader(),
	)
	var response *dtgsdkgo.GetAgentChannelsResponse
	raw, err := r.caller.Call(
		ctx,
		&internal.CallParams{
			URL:             endpointURL,
			Method:          http.MethodGet,
			Headers:         headers,
			MaxAttempts:     options.MaxAttempts,
			DisableRetries:  options.DisableRetries,
			BodyProperties:  options.BodyProperties,
			QueryParameters: options.QueryParameters,
			Client:          options.HTTPClient,
			Response:        &response,
		},
	)
	if err != nil {
		return nil, err
	}
	return &core.Response[*dtgsdkgo.GetAgentChannelsResponse]{
		StatusCode: raw.StatusCode,
		Header:     raw.Header,
		Body:       response,
	}, nil
}

func (r *RawClient) UpdateAgentChannels(
	ctx context.Context,
	request *dtgsdkgo.UpdateAgentChannelsRequest,
	opts ...option.RequestOption,
) (*core.Response[*dtgsdkgo.UpdateAgentChannelsResponse], error) {
	options := core.NewRequestOptions(opts...)
	baseURL := internal.ResolveBaseURL(
		options.BaseURL,
		r.baseURL,
		"https://api.like.ai.vn",
	)
	endpointURL := internal.EncodeURL(
		baseURL+"/api/v1/agents/%v/channels",
		request.ID,
	)
	headers := internal.MergeHeaders(
		r.options.ToHeader(),
		options.ToHeader(),
	)
	if request.IdempotencyKey != nil {
		headers.Add("Idempotency-Key", *request.IdempotencyKey)
	}
	headers.Add("Content-Type", "application/json")
	var response *dtgsdkgo.UpdateAgentChannelsResponse
	raw, err := r.caller.Call(
		ctx,
		&internal.CallParams{
			URL:             endpointURL,
			Method:          http.MethodPut,
			Headers:         headers,
			MaxAttempts:     options.MaxAttempts,
			DisableRetries:  options.DisableRetries,
			BodyProperties:  options.BodyProperties,
			QueryParameters: options.QueryParameters,
			Client:          options.HTTPClient,
			Request:         request,
			Response:        &response,
		},
	)
	if err != nil {
		return nil, err
	}
	return &core.Response[*dtgsdkgo.UpdateAgentChannelsResponse]{
		StatusCode: raw.StatusCode,
		Header:     raw.Header,
		Body:       response,
	}, nil
}

func (r *RawClient) ListAgentModels(
	ctx context.Context,
	opts ...option.RequestOption,
) (*core.Response[*dtgsdkgo.ModelList], error) {
	options := core.NewRequestOptions(opts...)
	baseURL := internal.ResolveBaseURL(
		options.BaseURL,
		r.baseURL,
		"https://api.like.ai.vn",
	)
	endpointURL := baseURL + "/api/v1/models"
	headers := internal.MergeHeaders(
		r.options.ToHeader(),
		options.ToHeader(),
	)
	var response *dtgsdkgo.ModelList
	raw, err := r.caller.Call(
		ctx,
		&internal.CallParams{
			URL:             endpointURL,
			Method:          http.MethodGet,
			Headers:         headers,
			MaxAttempts:     options.MaxAttempts,
			DisableRetries:  options.DisableRetries,
			BodyProperties:  options.BodyProperties,
			QueryParameters: options.QueryParameters,
			Client:          options.HTTPClient,
			Response:        &response,
		},
	)
	if err != nil {
		return nil, err
	}
	return &core.Response[*dtgsdkgo.ModelList]{
		StatusCode: raw.StatusCode,
		Header:     raw.Header,
		Body:       response,
	}, nil
}
