// Code generated by Fern. DO NOT EDIT.

package organizations

import (
	context "context"
	http "net/http"

	dtgagentsdk "github.com/DTG-Corp/dtg-agent-sdk"
	core "github.com/DTG-Corp/dtg-agent-sdk/core"
	internal "github.com/DTG-Corp/dtg-agent-sdk/internal"
	option "github.com/DTG-Corp/dtg-agent-sdk/option"
)

type RawClient struct {
	baseURL string
	caller  *internal.Caller
	options *core.RequestOptions
}

func NewRawClient(options *core.RequestOptions) *RawClient {
	return &RawClient{
		options: options,
		baseURL: options.BaseURL,
		caller: internal.NewCaller(
			&internal.CallerParams{
				Client:         options.HTTPClient,
				MaxAttempts:    options.MaxAttempts,
				DisableRetries: options.DisableRetries,
			},
		),
	}
}

func (r *RawClient) GetOrganization(
	ctx context.Context,
	request *dtgagentsdk.GetOrganizationRequest,
	opts ...option.RequestOption,
) (*core.Response[*dtgagentsdk.GetOrganizationResponse], error) {
	options := core.NewRequestOptions(opts...)
	baseURL := internal.ResolveBaseURL(
		options.BaseURL,
		r.baseURL,
		"https://api.like.ai.vn",
	)
	endpointURL := internal.EncodeURL(
		baseURL+"/api/v1/organizations/%v",
		request.ID,
	)
	headers := internal.MergeHeaders(
		r.options.ToHeader(),
		options.ToHeader(),
	)
	var response *dtgagentsdk.GetOrganizationResponse
	raw, err := r.caller.Call(
		ctx,
		&internal.CallParams{
			URL:             endpointURL,
			Method:          http.MethodGet,
			Headers:         headers,
			MaxAttempts:     options.MaxAttempts,
			DisableRetries:  options.DisableRetries,
			BodyProperties:  options.BodyProperties,
			QueryParameters: options.QueryParameters,
			Client:          options.HTTPClient,
			Response:        &response,
			ErrorDecoder:    internal.NewErrorDecoder(dtgagentsdk.ErrorCodes),
		},
	)
	if err != nil {
		return nil, err
	}
	return &core.Response[*dtgagentsdk.GetOrganizationResponse]{
		StatusCode: raw.StatusCode,
		Header:     raw.Header,
		Body:       response,
	}, nil
}

func (r *RawClient) ListOrganizationMembers(
	ctx context.Context,
	request *dtgagentsdk.ListOrganizationMembersRequest,
	opts ...option.RequestOption,
) (*core.Response[*dtgagentsdk.ListOrganizationMembersResponse], error) {
	options := core.NewRequestOptions(opts...)
	baseURL := internal.ResolveBaseURL(
		options.BaseURL,
		r.baseURL,
		"https://api.like.ai.vn",
	)
	endpointURL := internal.EncodeURL(
		baseURL+"/api/v1/organizations/%v/members",
		request.ID,
	)
	headers := internal.MergeHeaders(
		r.options.ToHeader(),
		options.ToHeader(),
	)
	var response *dtgagentsdk.ListOrganizationMembersResponse
	raw, err := r.caller.Call(
		ctx,
		&internal.CallParams{
			URL:             endpointURL,
			Method:          http.MethodGet,
			Headers:         headers,
			MaxAttempts:     options.MaxAttempts,
			DisableRetries:  options.DisableRetries,
			BodyProperties:  options.BodyProperties,
			QueryParameters: options.QueryParameters,
			Client:          options.HTTPClient,
			Response:        &response,
			ErrorDecoder:    internal.NewErrorDecoder(dtgagentsdk.ErrorCodes),
		},
	)
	if err != nil {
		return nil, err
	}
	return &core.Response[*dtgagentsdk.ListOrganizationMembersResponse]{
		StatusCode: raw.StatusCode,
		Header:     raw.Header,
		Body:       response,
	}, nil
}
