// Code generated by Fern. DO NOT EDIT.

package cameras

import (
	context "context"

	dtgsdkgo "github.com/DTG-Corp/dtg-sdk-go"
	core "github.com/DTG-Corp/dtg-sdk-go/core"
	internal "github.com/DTG-Corp/dtg-sdk-go/internal"
	option "github.com/DTG-Corp/dtg-sdk-go/option"
)

type Client struct {
	WithRawResponse *RawClient

	options *core.RequestOptions
	baseURL string
	caller  *internal.Caller
}

func NewClient(options *core.RequestOptions) *Client {
	return &Client{
		WithRawResponse: NewRawClient(options),
		options:         options,
		baseURL:         options.BaseURL,
		caller: internal.NewCaller(
			&internal.CallerParams{
				Client:         options.HTTPClient,
				MaxAttempts:    options.MaxAttempts,
				DisableRetries: options.DisableRetries,
			},
		),
	}
}

// Example:
//
//	client.Cameras.ListCameras(
//	    context.TODO(),
//	)
func (c *Client) ListCameras(
	ctx context.Context,
	opts ...option.RequestOption,
) (*dtgsdkgo.ListCamerasResponse, error) {
	response, err := c.WithRawResponse.ListCameras(
		ctx,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

// Example:
//
//	request := &dtgsdkgo.CameraCreateRequest{
//	    DisplayName: "display_name",
//	    Vendor: dtgsdkgo.CameraCreateRequestVendorGenericRtsp,
//	    RtspURL: "rtsp_url",
//	}
//	client.Cameras.CreateCamera(
//	    context.TODO(),
//	    request,
//	)
func (c *Client) CreateCamera(
	ctx context.Context,
	request *dtgsdkgo.CameraCreateRequest,
	opts ...option.RequestOption,
) (*dtgsdkgo.CreateCameraResponse, error) {
	response, err := c.WithRawResponse.CreateCamera(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

// Example:
//
//	request := &dtgsdkgo.GetCameraRequest{
//	    ID: "id",
//	}
//	client.Cameras.GetCamera(
//	    context.TODO(),
//	    request,
//	)
func (c *Client) GetCamera(
	ctx context.Context,
	request *dtgsdkgo.GetCameraRequest,
	opts ...option.RequestOption,
) (*dtgsdkgo.GetCameraResponse, error) {
	response, err := c.WithRawResponse.GetCamera(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

// Example:
//
//	request := &dtgsdkgo.DeleteCameraRequest{
//	    ID: "id",
//	}
//	client.Cameras.DeleteCamera(
//	    context.TODO(),
//	    request,
//	)
func (c *Client) DeleteCamera(
	ctx context.Context,
	request *dtgsdkgo.DeleteCameraRequest,
	opts ...option.RequestOption,
) (*dtgsdkgo.DeleteCameraResponse, error) {
	response, err := c.WithRawResponse.DeleteCamera(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

// Example:
//
//	request := &dtgsdkgo.CameraUpdateRequest{
//	    ID: "id",
//	}
//	client.Cameras.UpdateCamera(
//	    context.TODO(),
//	    request,
//	)
func (c *Client) UpdateCamera(
	ctx context.Context,
	request *dtgsdkgo.CameraUpdateRequest,
	opts ...option.RequestOption,
) (*dtgsdkgo.UpdateCameraResponse, error) {
	response, err := c.WithRawResponse.UpdateCamera(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}
